- _unittest/test_07_Object3D.py
- _unittest/test_Icepak.py
- pyaedt/application/Analysis.py
- pyaedt/edb_core/general.py
- pyaedt/hfss3dlayout.py
- pyaedt/icepak.py
- pyaedt/modeler/Object3d.py
- pyaedt/modeler/Primitives.py
- pyaedt/modules/Boundary.py
- pyaedt/modules/Material.py
- pyaedt/modules/MeshIcepak.py
> Added Methods needed in Icepak Automation Flow

- _unittest/test_Circuit_DynamicLink.py
- pyaedt/circuit.py
- pyaedt/modeler/PrimitivesNexxim.py
Two new functions in circuit.py
Cleaning circuit.py with style conventions
> SL Circuit Solution in HFSS Component and Export Touchstone

- _unittest/test_Circuit.py
- pyaedt/modeler/PrimitivesNexxim.py
Add Export TouchStone Unit Test, it needs one Design solved.
Fixing Unit Test numbering
Added Small change in PrimitivesNexxim.py
> UnitTest for Export TouchStone in Circuit

- _unittest/test_Circuit_DynamicLink.py
- pyaedt/modeler/PrimitivesNexxim.py
Push Excitations command typo fixed
UnitTest for Updating the Circuit Setup
Sin excitation modified to be compatible with Push Excitations
> SL circuit sin excitation bug and push excitation

- doc/source/Resources/Installation.rst
This PR adds a simple reminder to add a todo regarding installation from the unified install.
> Add todo regarding install from unified installer

- _unittest/test_01EDB.py
- pyaedt/edb_core/components.py
- pyaedt/modeler/Primitives3DLayout.py
Fixed bug in Edb methods that use GetProductProperty.
GetProductProperty returns a response structured differently in CPython.
Improved unittest.
> Fixed bug in Edb methods that use GetProductProperty.

- pyaedt/desktop.py
- pyaedt/generic/LoadAEDTFile.py
- pyaedt/modeler/Primitives.py
- Optimizations in desktop.py (removed Garbage collection warnings)
- Optimizations in LoadAEDTFile.py (removed Garbage collection warnings)
- HFSS files exported from 3DLayout have a very old format (v2017) and MaterialValue doesn't exists.
- Solved bug in Primitives delete method (without the update, `hfss.modeler.primitives.get_all_solids_names()` and `hfss.modeler.primitives.solids` were giving different results).
> Optimizations to removed Garbage collection warnings. Solved bug in Primitives delete method.

- _unittest/test_Icepak.py
- pyaedt/icepak.py
- pyaedt/modules/MeshIcepak.py
Icepak Mesh Region creation and assignment refactored, some typos found
> Sl icepak mesh region

- pyaedt/desktop.py
Change AEDT default version in update_aedt_registry method from 193 to 211, discussed in #305.
> Update AEDT default version in update_aedt_registry

- pyaedt/modules/PostProcessor.py
Test failing locally due to incorrect reference to messenger
> Fix reference to messenger

- pyaedt/hfss.py
Add example for `discrete_sweep()`
> Add example for discrete sweep.

- _unittest/test_Circuit.py
- _unittest/test_Maxwell2D.py
- pyaedt/application/AnalysisNexxim.py
- pyaedt/application/AnalysisSimplorer.py
- pyaedt/circuit.py
- pyaedt/maxwell.py
- pyaedt/modeler/Modeler.py
- pyaedt/modeler/Primitives.py
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/SetupTemplates.py
- pyaedt/modules/SolveSetup.py
Fixed a bug in Maxwell 2d
Added nexxim Setup for Eye Analysis
> Nexxim improvements

- doc/source/API/Application.rst
- doc/source/API/CoreModules.rst
- doc/source/API/DesktopMessenger.rst
- pyaedt/application/Analysis.py
- pyaedt/application/Analysis3D.py
- pyaedt/application/Design.py
- pyaedt/application/Variables.py
- pyaedt/edb.py
- pyaedt/edb_core/EDB_Data.py
- pyaedt/edb_core/components.py
- pyaedt/edb_core/hfss.py
- pyaedt/edb_core/layout.py
- pyaedt/edb_core/nets.py
- pyaedt/edb_core/padstack.py
- pyaedt/edb_core/siwave.py
- pyaedt/edb_core/stackup.py
- pyaedt/hfss3dlayout.py
- pyaedt/icepak.py
- pyaedt/mechanical.py
- pyaedt/modules/DesignXPloration.py
- pyaedt/modules/MeshIcepak.py
- pyaedt/modules/SolveSetup.py
- pyaedt/siwave.py
Think that's enough for one PR!
> Doc/edits general Tuesday morning

- _unittest/test_3dlayout_modeler.py
- _unittest/test_Circuit.py
- _unittest/test_Icepak.py
- examples/00-basic-examples/HFSS3DLayout_Via.py
- examples/00-basic-examples/Q3D_Example.py
- examples/00-basic-examples/SBR_Example.py
- examples/01-advanced-postprocessing/Maxwell2D_Eddy.py
- examples/01-advanced-postprocessing/Maxwell2D_Transient.py
- pyaedt/application/Analysis.py
- pyaedt/maxwell.py
- pyaedt/modeler/PrimitivesNexxim.py
Fix #333.
Replace 'analyse' by 'analyze' in pyAEDT.
> Replace 'analyse' by 'analyze'.

- pyaedt/modeler/Modeler.py
Fixes bullet points and parameters styling.
> Fix change_cs_mode styling

- pyaedt/edb.py
In `open_edb` correctly sets `self._active_cell` to default cell if `cellname` is not specified.
Minor code clean-up.
> Fix: sets self._active_cell to default cell if cell name is not specified.

- pyaedt/edb.py
Correct layout import method
add support for tgz
> Correct the code to convert layout file into edb.

- _unittest/test_Materials.py
- pyaedt/modules/Material.py
Added material appearance property to materials. 
Created unit tests.
> Added material appearance property to materials.

- _setup_common.py
- examples/00-basic-examples/edb_example.py
- pyaedt/edb_core/hfss.py
- setup.py
> Added 3.9 support

- .flake8
- _unittest/test_08_Primitives3D.py
- _unittest/test_Icepak.py
- _unittest/test_zEDB.py
- pyaedt/application/AnalsyisEmit.py
- pyaedt/application/AnalysisRMxprt.py
- pyaedt/application/DataHandlers.py
- pyaedt/conftest.py
- pyaedt/edb_core/general.py
- pyaedt/generic/LoadAEDTFile.py
- pyaedt/generic/TouchstoneParser.py
- pyaedt/generic/filesystem.py
- pyaedt/generic/general_methods.py
- pyaedt/generic/list_handling.py
- pyaedt/modeler/Model3D.py
- pyaedt/modeler/PrimitivesSimplorer.py
- pyaedt/modules/Boundary.py
- pyaedt/modules/LayerStackup.py
- pyaedt/modules/SetupTemplates.py
- pyaedt/modules/SolveSetup.py
Remove whitespace on blank lines.
> Formatting - whitespace on blank lines

- pyaedt/application/AEDT_File_Management.py
- pyaedt/application/Analysis.py
- pyaedt/application/Analysis3D.py
- pyaedt/application/Analysis3DLayout.py
- pyaedt/application/AnalysisIcepak.py
- pyaedt/application/AnalysisNexxim.py
- pyaedt/application/Design.py
- pyaedt/application/MessageManager.py
- pyaedt/application/Variables.py
- pyaedt/circuit.py
- pyaedt/desktop.py
- pyaedt/edb.py
- pyaedt/generic/LoadAEDTFile.py
- pyaedt/generic/TouchstoneParser.py
- pyaedt/generic/filesystem.py
- pyaedt/generic/general_methods.py
- pyaedt/generic/list_handling.py
- pyaedt/generic/process.py
- pyaedt/hfss.py
- pyaedt/hfss3dlayout.py
- pyaedt/icepak.py
- pyaedt/maxwell.py
- pyaedt/mechanical.py
- pyaedt/q3d.py
- pyaedt/rmxprt.py
- pyaedt/siwave.py
PR 2 of 3 to fix line length.
Addresses:
- top level pyaedt files
- pyaedt/application files
- pyaedt/generic files
PR 3 will add the line length directive to the flake8 config.
> Formatting - fix line length part 2

- pyaedt/edb.py
Remove extra line that is now causing a flake8 error.
> Fix extra line between methods for flake8

- .github/workflows/ci-build.yml
- .gitignore
- doc/Makefile
- doc/print_errors.py
- doc/source/conf.py
This PR modifies the CI/CD to show all the errors from sphinx docbuild rather than the first one.
> show all warnings

- _unittest/test_Circuit.py
- pyaedt/circuit.py
Fixed bug in push_excitation method.
Added unit test for push_excitation.
> push_excitation fix

- .github/workflows/ci-build.yml
- .github/workflows/style.yml
This PR limits our CI/CD checks for just PRs rather pushes and PRs.﻿
> Run doc and style checks only for PRs

- pyaedt/modeler/Modeler.py
Fixed bug in Modeler.edit_region_dimensions. 
Just one TAB was missing.
> Fixed bug in Modeler.edit_region_dimensions.

- .github/workflows/nightly-docs.yml
- .github/workflows/unit_tests.yml
Remove doctest run from unit test CI to the nightly doc build.
> Move doctest to nightly build

- pyaedt/desktop.py
Change the name of some variables.
Set the value for the "i" in the while loop of the `force_close_desktop()` function.
> Change the name of some variables.

- _unittest/test_24_3dlayout_modeler.py
- pyaedt/modeler/Model3DLayout.py
- added set_temperature_dependence in 3dlayout
- added unittests
> added set_temperature_dependence in 3dlayout

- _unittest/test_35_LoadAEDTFile.py
- _unittest_ironpython/test_35_LoadAEDTFile.py
- pyaedt/generic/LoadAEDTFile.py
> Test35 ironpython

- _unittest/test_24_3dlayout_modeler.py
- pyaedt/hfss3dlayout.py
Fixed 3dlayout create_single_point_sweep.
Modified unit test to catch this error.
> Fixed 3dlayout create_single_point_sweep

- _unittest/test_25_Icepak.py
- pyaedt/application/AnalysisIcepak.py
Fixed apply_icepak_settings not accepting floats. Improved unit tests.
> Fixed apply_icepak_settings.

- doc/source/Resources/Contributing.rst
Fix some typo for the code example.
> Fix code typo.

- pyaedt/edb_core/padstack.py
> set solder ball

- pyaedt/common_rpc.py
- pyaedt/rpc/rpyc_services.py
- setup.py
Updated the max chunk size to 256MB
> Update the disconnect on linux. the release_desktop is not needed.

- pyaedt/maxwell.py
it applies also to assign_current, assign_voltage and assign_voltage_drop
> Fixed Issue 367

- _unittest/test_00_EDB.py
- _unittest/test_20_HFSS.py
- pyaedt/edb_core/padstack.py
- pyaedt/generic/general_methods.py
- pyaedt/hfss.py
- pyaedt/modeler/Modeler.py
- pyaedt/modules/Boundary.py
> Added new methods for Floquet Ports and Lattice Pairs

- pyaedt/generic/general_methods.py
Refactor the way we get the ANSYSEM path and version.
It will avoid code duplication which is error prone.
> ANSYSEM path and version.

- _unittest/test_27_Maxwell2D.py
- _unittest/test_28_Maxwell3D.py
- doc/source/API/Constants.rst
- pyaedt/application/Design.py
- pyaedt/hfss.py
- pyaedt/icepak.py
- pyaedt/maxwell.py
- pyaedt/modules/Boundary.py
> Added Motion Methods to Maxell

- _unittest/test_12_PostProcessing.py
- examples/01-advanced-postprocessing/Advanced_Far_Field.py
- pyaedt/application/Analysis.py
- pyaedt/application/Analysis3D.py
- pyaedt/application/Design.py
- pyaedt/generic/general_methods.py
- pyaedt/modules/PostProcessor.py
> Add csv exporter to solution data

- _unittest/test_00_EDB.py
- pyaedt/edb_core/layout.py
- pyaedt/edb_core/padstack.py
Add_void add primitives to an exsiting shape.
> add_void method

- pyaedt/generic/general_methods.py
All log lines are now written into the file with the same format.
> Use the same format for all log lines

- examples/01-advanced-postprocessing/Maxwell3D TEAM7.py
…So, This contains changes of Maxwell2D>Maxwell3D and another Maxwell2D to Maxwell3D change as raised by Bo in Issue614
I've added more details to the description and changed the name of the file for good measure
> Against Issue 614

- _unittest/test_28_Maxwell3D.py
- pyaedt/maxwell.py
> Fixed assign_current method

- pyaedt/application/AEDT_File_Management.py
@maxcapodi78 The edits here are the same as in PR#639 from yesterday. I couldn't merge that PR because it was from a fork rather than a branch. These edits comes from a branch--as Maxime helped me get set up properly and granted me the needed permissions.
> Edits to AEDT_File_Management.py to see if I can do a PR

- doc/source/API/SetupTemplates.rst
- doc/source/Resources/Contributing.rst
- examples/00-EDB/01_edb_example.py
- examples/01-Modeling-Setup/HFSS_CoordinateSystem.py
- examples/01-Modeling-Setup/Polyline_Primitives.py
- examples/02-HFSS/Readme.txt
- examples/02-Maxwell/Readme.txt
- examples/04-Icepak/Icepak_Example.py
- examples/06-Multiphysics/Hfss_Icepak_Coupling.py
Correct some misspellings in the documentation examples.
Fix issue #678 .
> Correct some misspellings in the documentation examples.

- pyaedt/modeler/parts.py
FFD import for SBR+ from JSON file
> Json with ffd source bug664

- doc/source/Resources/Contributing.rst
Fixes formatting issue and makes last sentence parallel in structure to previous sentence.
> Fix minor issues in Contributing topic

- _unittest/test_00_EDB.py
- pyaedt/edb_core/padstack.py
This method will be used for via parameterization.
> Duplicate an existing padstack definition

- _unittest/test_00_EDB.py
- pyaedt/edb_core/EDB_Data.py
- pyaedt/edb_core/padstack.py
A minor update on padstack instance.
> Padstack inst update

- _unittest/test_20_HFSS.py
- pyaedt/application/Analysis.py
- pyaedt/application/Analysis2D.py
- pyaedt/hfss.py
- pyaedt/modeler/Modeler.py
Improved Terminal Naming in HFSS Port Creation
> Improved Terminal Name assignment.

- _unittest/test_07_Object3D.py
- pyaedt/modeler/Object3d.py
Added bounding_dimension property to 3D objects to get the bounding box dimension
> Added bounding_dimension property to 3D objects

- _unittest/test_28_Maxwell3D.py
- pyaedt/application/Analysis.py
- pyaedt/application/Design.py
- pyaedt/application/design_solutions.py
- pyaedt/generic/filesystem.py
- pyaedt/modeler/Object3d.py
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/SetupTemplates.py
This work for ironpython and cpython from 2021.2
> Now bounding box is computed using obj file.

- _unittest/test_35_MaxwellCircuit.py
- _unittest_ironpython/test_35_MaxwellCircuit.py
- pyaedt/__init__.py
- pyaedt/application/Analysis.py
- pyaedt/application/AnalysisMaxwellCircuit.py
- pyaedt/application/Design.py
- pyaedt/application/design_solutions.py
- pyaedt/generic/design_types.py
- pyaedt/maxwellcircuit.py
- pyaedt/modeler/Circuit.py
- pyaedt/modeler/Object3d.py
- pyaedt/modeler/PrimitivesMaxwellCircuit.py
Expose Maxwell Circuit Editor Design
> Expose Maxwell Circuit Editor

- _setup_common.py
Improve the Description in the _setup_common.py file.
> Improve the Description in the _setup_common.py file.

- _unittest/test_27_Maxwell2D.py
- _unittest/test_28_Maxwell3D.py
- pyaedt/hfss.py
- pyaedt/icepak.py
- pyaedt/maxwell.py
- pyaedt/mechanical.py
- pyaedt/modeler/Modeler.py
- pyaedt/modules/Mesh.py
- pyaedt/q3d.py
`_convert_list_to_ids` is being deprecated. Using `convert_to_selections` instead.
> Deprecate `_convert_list_to_ids`

- README.rst
- _unittest/test_00_EDB.py
- _unittest/test_20_HFSS.py
- doc/source/API/Application.rst
- doc/source/API/ClientServer.rst
- doc/source/API/index.rst
- doc/source/Resources/Contributing.rst
- doc/source/Resources/Installation.rst
- doc/source/Resources/User_Guide.rst
- pyaedt/application/Analysis.py
- pyaedt/application/Analysis2D.py
- pyaedt/application/Analysis3D.py
- pyaedt/application/Analysis3DLayout.py
- pyaedt/application/AnalysisTwinBuilder.py
- pyaedt/application/Design.py
- pyaedt/application/JobManager.py
- pyaedt/application/design_solutions.py
- pyaedt/circuit.py
- pyaedt/desktop.py
- pyaedt/edb.py
- pyaedt/hfss.py
- pyaedt/modeler/Model3D.py
- pyaedt/modeler/Model3DLayout.py
The AEDT documentation has had a lot of new text added and old text edited. I'm beginning an editorial review of all the doc. This is my first PR, and I'm going to push it because there are edits already in 18 files. However, I see that there are black and flake 8 checks failing. I will attempt to fix the errors in the morning because it is after 6 PM here. Sorry!
P.S. I intend to try to submit one PR per day, but if you prefer some other way to incorporate doc edits, please advise. Thanks!
> Edits to AEDT doc - Part 1

- pyaedt/edb.py
Add information in the docstring to describe GDS import when an Edb object
is instantiated.
> Update Edb documentation

- pyaedt/modeler/Object3d.py
Improved export_profile and export_convergence method to support Q3d and Q2D custom methods.
> Added Model properties to Circuit Component with update method

- .github/workflows/ironpython.yml
Increase timeout for IronPython tests.
> Increase timeout for IronPython tests.

- pyaedt/modeler/Model3D.py
> Fixed issue on 3d component with Terminal Solution.

- _unittest/test_02_3D_modeler.py
- pyaedt/modeler/Modeler.py
Method to move a face of a specific object.
> Move Faces method. From an specific object move selected faces

- _unittest/test_42_configuration_files.py
- _unittest_ironpython/test_42_configuration_files.py
- doc/source/API/CoreModules.rst
- examples/01-Modeling-Setup/Configurations.py
- pyaedt/application/Analysis2D.py
- pyaedt/application/Analysis3D.py
- pyaedt/application/AnalysisIcepak.py
- pyaedt/application/Design.py
- pyaedt/application/Variables.py
- pyaedt/generic/configurations.py
- pyaedt/generic/general_methods.py
- pyaedt/hfss.py
- pyaedt/maxwell.py
- pyaedt/modeler/Modeler.py
- pyaedt/modules/Boundary.py
- pyaedt/modules/MaterialLib.py
- pyaedt/modules/Mesh.py
- pyaedt/modules/SolveSetup.py
- requirements_test.txt
First Implementation of Configuration Files import and export to json format.
Configuration file is actually supported by the following applications:
* Hfss
* Q2d and Q3d
* Maxwell
* Icepak
* Mechanical
The sections covered are:
* Variables
* Mesh Operations (except Icepak)
* Setup and Optimetrics
* Material Properties
* Object Properties
* Boundaries and Excitations
When a boundary is attached to a face the tool will try to match it with a
FaceByPosition on the same object name on the target design.
If, for any reason, that face position has changed or object name in the target design has changed,
the boundary will fail to apply.
> Configuration files

- README.rst
Adds a title to the `README.rst` file and includes a `PyAnsys` badge.
> Add README.rst title and PyAnsys badge

- _unittest/example_models/material_sample.amat
- _unittest/test_13_LoadAEDTFile.py
- pyaedt/generic/LoadAEDTFile.py
- pyaedt/modules/MaterialLib.py
LoadAEDTFile now supports .amat files.
It is possible to add materials directly from an .amat file.
> Read material .amat files

- _unittest/test_20_HFSS.py
- pyaedt/hfss.py
- pyaedt/modeler/Modeler.py
- pyaedt/modeler/Primitives.py
Now it is possible to set impedance for Lumped ports and Wave ports in Terminal mode.
> Impedance support for Lumped ports and Wave ports in Terminal mode.

- _unittest/test_12_PostProcessing.py
- doc/source/API/Post.rst
- ignore_words.txt
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/report_templates.py
A new class has been added to manage Spectral Reports.
> Added Spectral reports

- pyaedt/maxwell.py
> Fixed bug with motion setup name

- _unittest/test_00_EDB.py
- pyaedt/edb.py
- pyaedt/edb_core/stackup.py
Add a duplicate_material function in edb_core/stack_up so for Edb materials
> Enhancement/edb core/add material management function

- _unittest/test_12_PostProcessing.py
- doc/source/API/Post.rst
- pyaedt/generic/constants.py
- pyaedt/modules/report_templates.py
Added Report Trace Editors.
two new property, traces and limit_lines are available for each created report.
Those properties are lists of available traces and allows to edit any parameters of the traces in the reports.
> Trace management

- junit/test-results.xml
Remove the junit test results.
> Remove the junit test results.

- _unittest/test_00_EDB.py
- _unittest/test_02_2D_modeler.py
- _unittest/test_02_3D_modeler.py
- _unittest/test_07_Object3D.py
- _unittest/test_08_Primitives3D.py
- _unittest/test_12_PostProcessing.py
- pyaedt/edb_core/stackup.py
- pyaedt/modeler/Modeler.py
- pyaedt/modeler/Object3d.py
- pyaedt/modeler/Primitives2D.py
- pyaedt/modeler/Primitives3D.py
- pyaedt/modules/report_templates.py
- pyaedt/q3d.py
To handle object creation from edge, object creation from face, edge normal movement and find top/bottom edges.
> Added new methods to Object3d FacePrimitive and EdgePrimitive classes

- _unittest/test_00_EDB.py
- requirements.txt
- setup.py
Revert rpyc version from 5.1.0 to 5.0.1.
Fix #1135 .
> Revert rpyc version from 5.1.0 to 5.0.1.

- _unittest/test_00_EDB.py
- _unittest/test_11_Setup.py
- pyaedt/generic/configurations.py
- pyaedt/modules/SetupTemplates.py
- pyaedt/modules/SolveSetup.py
enable_adaptive_setup_multifrequency
enable_adaptive_setup_broadband
enable_adaptive_setup_single
> Added few method to edit Adaptive Frequency Strategy in Hfss

- _unittest/test_28_Maxwell3D.py
- pyaedt/application/Analysis3D.py
- pyaedt/maxwell.py
- pyaedt/modules/SolveSetup.py
In this PR Eddy Effects settings have been fixed such that:
- When eddy_effect_on(list, False) the list of specified object will have eddy effects turned off.
- When eddy_effect_on(list, True) the list of specified object will have eddy effects turned on.
> Maxwell3D EddyEffect

- _unittest/test_03_Materials.py
- _unittest/test_08_Primitives3D.py
- _unittest/test_41_3dlayout_modeler.py
- _unittest/test_98_Icepak.py
- pyaedt/application/Analysis3D.py
- pyaedt/desktop.py
- pyaedt/generic/configurations.py
- pyaedt/hfss.py
- pyaedt/icepak.py
- pyaedt/modeler/Circuit.py
- pyaedt/modeler/Model3D.py
- pyaedt/modeler/Object3d.py
- pyaedt/modeler/Primitives.py
- pyaedt/modeler/Primitives3D.py
- pyaedt/modules/MaterialLib.py
> Material refactoring

- pyaedt/modeler/Modeler.py
@Samuelopez-ansys we found a bug in user_list. Please give a look at the fix
> Fix User List Init

- .github/workflows/releases.yml
Remove wheels and pdf from the release assets.
> Remove wheels and pdf from the release assets.

- _unittest/test_09_Primitives2D.py
- _unittest/test_40_3dlayout_edb.py
- pyaedt/application/Analysis3D.py
- pyaedt/modules/LayerStackup.py
Improved assign_material for huge number of assignments.
> fixed signal_layers and diel_layers properties in Hfss3dLayout modeler

- _unittest/test_01_Design.py
- _unittest/test_07_Object3D.py
- _unittest/test_11_Setup.py
- pyaedt/application/Design.py
- pyaedt/modeler/Object3d.py
- pyaedt/modules/Boundary.py
- Duplicate design refresh pyaedt object
- Fix small bug in End Connection boundary
> Refresh pyaedt object when design duplication

- _unittest/test_02_3D_modeler.py
- _unittest/test_07_Object3D.py
- examples/02-Maxwell/Maxwell2D_Transient.py
- pyaedt/modeler/Model3D.py
- pyaedt/modeler/Object3d.py
In this PR:
- new method to check objects in a bounding box
- some fixes for faces_by_area method
- new method edges_by_length
- + unit tests
> Objects in bounding box

- pyaedt/desktop.py
No support at the momento for Edb API
> Linux grpc support to pyaedt

- .github/labeler.yml
- .github/labels.yml
- .github/workflows/label.yml
Labels are added automatically when a new pull request is created.
Fix #1295 .
> Labels are added automatically when a new pull request is created.

- .github/ISSUE_TEMPLATE/feature.yml
Add a template for the new feature in the issue section.
Fix #1293 .
Here is the final rendering.
> Add a template for the new feature in the issue section.

- _unittest/test_12_PostProcessing.py
- pyaedt/modules/solutions.py
- Small bug when overwrite is False
- Add UT for this case
> Fixed Overwrite option in FFData

- pyaedt/modeler/stackup_3d.py
> fix to import numpy error

- _unittest/test_27_Maxwell2D.py
- pyaedt/application/Design.py
read MotionSetup when getting boundaries data in Design
> read motion setup in Maxwell2D

- pyaedt/modules/solutions.py
> Fixed issue 1266. now plot support no formula to talke only real solution data

- pyaedt/modules/solutions.py
If the face id belongs to a non model object the syntax has to be changed
> Added a check in the create Field plot method on the face ids. 

- README.rst
- doc/source/API/Application.rst
- doc/source/API/Boundaries.rst
- doc/source/API/ClientServer.rst
- doc/source/API/Common.rst
- doc/source/API/Configuration.rst
- doc/source/API/CoreEdb.rst
- doc/source/API/CoreModules.rst
- doc/source/API/DesktopMessenger.rst
- doc/source/API/MaterialManagement.rst
- doc/source/API/Mesh.rst
- doc/source/API/MultiPartComponent.rst
- doc/source/API/Post.rst
- doc/source/API/Primitives.rst
- doc/source/API/Setup.rst
- doc/source/API/SetupTemplates.rst
- doc/source/API/Stackup3D.rst
- doc/source/API/index.rst
- doc/source/index.rst
Trying to prepare for implementation of Vale docstyle linter, which requires sentence case headings.
> Change headings to snake case for source/docs folder

- _unittest/test_08_Primitives3D.py
- pyaedt/modeler/Object3d.py
It finds for object that touch at least one vertex or face center or edge midpoint
> added new object3d property touching_objects

- _unittest/test_98_Icepak.py
- pyaedt/icepak.py
This method assigns a monitor point in the centroid of the specific object and returns the name of the monitor created
> New method to define monitor point in Icepak for an specific object

- examples/00-EDB/00_EDB_Create_VIA.py
- examples/00-EDB/01_edb_example.py
- examples/00-EDB/02_edb_to_ipc2581.py
- examples/00-EDB/03_5G_antenna_example.py
- examples/00-EDB/04_edb_parametrized_design.py
- examples/00-EDB/05_Plot_nets.py
- examples/00-EDB/06_Advanced_EDB.py
- examples/00-EDB/07_WPF_Merge_Utility.py
- examples/00-EDB/Readme.txt
- examples/01-Modeling-Setup/Readme.txt
- examples/02-HFSS/Readme.txt
- examples/02-Maxwell/Readme.txt
- examples/03-Circuit/Readme.txt
- examples/04-Icepak/Readme.txt
- examples/05-Q3D/Readme.txt
- examples/06-Multiphysics/Readme.txt
- examples/07-TwinBuilder/Readme.txt
- examples/Readme.txt
After you review and merge this PR, I will edit the Modeling-Setup examples. I also need someone to tell me how to edit the captions and alternate captions. I edited them in doc\source\examples\index.rst, but Git shows no changes to commit. Obviously the captions that appear in index.rst come from somewhere else.
> Doc/edit example landing page and EDB examples

- examples/00-EDB/01_edb_example.py
- examples/00-EDB/03_5G_antenna_example.py
- examples/00-EDB/05_Plot_nets.py
- examples/00-EDB/06_Advanced_EDB.py
- examples/00-EDB/07_WPF_Merge_Utility.py
- examples/01-Modeling-Setup/Configurations.py
- examples/01-Modeling-Setup/HFSS_CoordinateSystem.py
- examples/01-Modeling-Setup/Optimetrics.py
- examples/01-Modeling-Setup/Polyline_Primitives.py
Minor edits were also made to some EDB examples
> Edits to Modeler and Setup examples

- pyaedt/modeler/Modeler.py
> Added number_of_segments argument to sweep_around_axis

- examples/02-Maxwell/Maxwell2D_NissanLeaf.py
- examples/02-Maxwell/Maxwell3DTeam3.py
- examples/02-Maxwell/Maxwell3DTeam7.py
- pyaedt/modeler/Model2D.py
- pyaedt/modeler/Modeler.py
- pyaedt/modeler/stackup_3d.py
legacy values are still handled but a deprecation warning appears
> harmonized keep_originals arguments

- pyaedt/edb_core/nets.py
> plot_bug_fix

- _unittest/test_01_Design.py
- pyaedt/application/Design.py
- pyaedt/application/Variables.py
icepak and Maxwell 3D allows 3D Dataset at design level
> Add 3DDataset in Icepak and Maxwell at design level

- doc/source/API/ClientServer.rst
- pyaedt/application/AEDT_File_Management.py
- pyaedt/application/Analysis.py
- pyaedt/application/Analysis3D.py
- pyaedt/application/Design.py
- pyaedt/application/Variables.py
- pyaedt/circuit.py
- pyaedt/common_rpc.py
- pyaedt/desktop.py
- pyaedt/generic/LoadAEDTFile.py
- pyaedt/generic/general_methods.py
- pyaedt/generic/ibis_reader.py
- pyaedt/generic/near_field_import.py
- pyaedt/generic/plot.py
- pyaedt/hfss.py
- pyaedt/hfss3dlayout.py
- pyaedt/icepak.py
- pyaedt/maxwell.py
- pyaedt/maxwellcircuit.py
- pyaedt/modeler/Model3DLayout.py
- pyaedt/modeler/Object3d.py
- pyaedt/modeler/Primitives3D.py
- pyaedt/modeler/PrimitivesCircuit.py
- pyaedt/modeler/PrimitivesNexxim.py
- pyaedt/modules/AdvancedPostProcessing.py
- pyaedt/modules/MaterialLib.py
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/solutions.py
- pyaedt/rpc/local_server.py
- pyaedt/rpc/rpyc_services.py
New methods:
pyaedt_service_manager is a server listening on port 17878 and that must run on the server.
create_session the client create a new session on the server. The new session is used:
- for file transfer
- to start edb
- to start aedt
> Improved file management between client and server.

- _unittest/test_02_3D_modeler.py
- pyaedt/application/Design.py
- pyaedt/modeler/Modeler.py
- Improve delete CS method. If a CS is relative to another one and it is removed, the list of CS now is correctly refreshed
- If project saved force to reread aedt file
> Improve delete CS method

- _unittest/test_98_Icepak.py
- pyaedt/icepak.py
- pyaedt/modules/Boundary.py
> Fixed update_assignment method

- _unittest/test_08_Primitives3D.py
- pyaedt/modeler/Object3d.py
now every face has a property to find touching objects
> Added touching_object property to Faces

- _unittest/test_07_Object3D.py
- pyaedt/modeler/Object3d.py
- pyaedt/modeler/Primitives.py
> fixed bug in unclassified_objects

- _unittest/test_00_EDB.py
- pyaedt/edb_core/EDB_Data.py
Implemented setter as for #1468
> Added setter to hole_plating_thickness

- _unittest/test_12_PostProcessing.py
- pyaedt/modules/SetupTemplates.py
Those are obtained from solution file. 
So project has to be saved in order to get them
> Added 2 properties to SetupHfss frequencies and basis_frequencies

- _unittest/test_00_EDB.py
- pyaedt/edb.py
- pyaedt/generic/process.py
> Added hidden mode

- _unittest/test_28_Maxwell3D.py
- pyaedt/modules/Boundary.py
- pyaedt/modules/PostProcessor.py
> Added join_series and join_parallel methods to matrix

- README.rst
> Update the introduction page of the documentation.

- _unittest/test_27_Maxwell2D.py
- _unittest/test_28_Maxwell3D.py
- pyaedt/application/Analysis.py
> Implement export rl matrix

- _unittest/test_00_downloads.py
- examples/07-TwinBuilder/03-Dynamic_ROM_Creation_And_Visualization.py
- pyaedt/examples/downloads.py
adding data extraction for a new example under construction
> Add new TB Example for Dynamic ROM Creation

- examples/07-TwinBuilder/04-Static_ROM_Creation_And_Visualization.py
Start with baseline Static ROM generation using data from fluent
To be extended with views
> New Example for Building a Static ROM in Twin Builder

- pyaedt/modules/Boundary.py
> Add documentation for the classes located in 'boundary' module.

- pyaedt/modeler/Object3d.py
Remaining modification from #1306 .
> Update the documentation of the edge length property.

- _unittest/test_00_EDB.py
- pyaedt/desktop.py
- pyaedt/edb_core/components.py
to add_voltage_source and add_current_source methods
> removed the generate_unique_name when a name is provided 

- pyaedt/modeler/Primitives.py
> fixed typo error in unclassified object retrivial

- _unittest/test_02_3D_modeler.py
- pyaedt/modeler/Modeler.py
- pyaedt/modeler/Primitives.py
> Improved the speedup of create_object_list by improving the check speed on names

- examples/04-Icepak/Sherlock_Example.py
- examples/06-Multiphysics/Hfss_Icepak_Coupling.py
- pyaedt/icepak.py
- pyaedt/modules/SetupTemplates.py
Fixed icepak name in some docs
> Fix icepak typo with 'C'

- _unittest/test_01_Design.py
- pyaedt/application/Design.py
- pyaedt/generic/general_methods.py
> implemented force_error_on_missing_project flag

- _unittest/test_28_Maxwell3D.py
- examples/02-Maxwell/Maxwell2D_NissanLeaf.py
- pyaedt/modeler/Primitives.py
> Allow python script for User Defined Part (UDP)

- _unittest/test_41_3dlayout_modeler.py
- pyaedt/hfss3dlayout.py
- pyaedt/modeler/Object3d.py
- pyaedt/modeler/Primitives3DLayout.py
> Fixed bug in padstack layers initialization

- _unittest/test_02_3D_modeler.py
- pyaedt/modeler/Modeler.py
- pyaedt/modeler/Object3d.py
> Implemented 3d Object Sheet wrapping either in Modeler and in Object3d

- _unittest/test_08_Primitives3D.py
- pyaedt/modeler/Object3d.py
- pyaedt/modeler/Primitives.py
> create_object_from_face and create_object_from_edge now supports list of faces as input and also allows to create nonmodel objects.

- _unittest/test_02_3D_modeler.py
- pyaedt/application/Design.py
- pyaedt/modeler/Modeler.py
- pyaedt/modeler/Object3d.py
> Implemented 3d Object returns unite/Intersect/Split methods

- _unittest/test_00_EDB.py
- pyaedt/edb_core/EDB_Data.py
- pyaedt/edb_core/stackup.py
> 1064 add layer

- _unittest/test_00_EDB.py
- pyaedt/edb_core/siwave.py
> Implemented create_dc_terminal method in core_siwave class (#1624]

- _unittest/test_41_3dlayout_modeler.py
- doc/source/API/Boundaries.rst
- pyaedt/application/Design.py
- pyaedt/hfss3dlayout.py
- pyaedt/modules/Boundary.py
> Added a new Boundary Class for hfss3dlayout.py ports.

- pyaedt/edb_core/stackup.py
> Fix place_a3dcomp_3d_placement documentation

- _unittest/test_28_Maxwell3D.py
- pyaedt/modules/Material.py
> Add material properties for lamination in Maxwell.

- pyaedt/icepak.py
- pyaedt/modules/PostProcessor.py
Fixed bug in power_budget method when 3dcomponent is created from pyaedt.
> Added power_in field to create_pcb_from_3dlayout method.

- pyaedt/modeler/Primitives3D.py
> Retry point creation in Primitives3D.

- pyaedt/modules/MaterialLib.py
Expose public properties for the material names.
Fix #1683.
> Expose public properties for the material names.

- examples/03-Circuit/Circuit_Transient.py
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/SetupTemplates.py
- pyaedt/modules/SolveSetup.py
- pyaedt/modules/solutions.py
now get_solution_data accept None as argument for expression which will provide all available traces for that solution in report category.
fix few bugs in is_solved flag for time domain analysis
> minor improvement on get_solution_data

- requirements.txt
- setup.py
Increate pythonnet to version 3.0.0rc5.
> Increate pythonnet to version 3.0.0rc5.

- _unittest/example_models/TEDB/bom_example_2.csv
- _unittest/test_00_EDB.py
- pyaedt/edb_core/EDB_Data.py
- pyaedt/edb_core/components.py
This method reflects the real application better
> import bom 

- pyaedt/modules/report_templates.py
> Fixed edit_x_axis_scaling and edit_y_axis_scaling methods

- _unittest/test_01_Design.py
- pyaedt/desktop.py
- pyaedt/siwave.py
> Return PyAEDT app object from Desktop object

- pyaedt/application/design_solutions.py
- pyaedt/edb_core/layout.py
Circuit solution type now is correctly setted
edb primitives object used to contain everything. now it contains only polygons, rectangles, circles and path.
> Fixed a bug in solution_type and a bug in primitives in edb

- _unittest/test_01_Design.py
- pyaedt/desktop.py
> Fix bug in clear messages method

- doc/source/API/ClientServer.rst
> Comment out some description in documentation code snippets.

- pyaedt/edb_core/stackup.py
bug, fail to import stackup if no stackup exist in edb.
> import stackup bug fix

- doc/source/API/Post.rst
- pyaedt/modules/PostProcessor.py
Added Circuit PostProcessor class to Docstrings
> Fix post docs

- _unittest/test_08_Primitives3D.py
- _unittest/test_40_3dlayout_edb.py
- pyaedt/application/Analysis.py
- pyaedt/generic/DataHandlers.py
- pyaedt/hfss3dlayout.py
…eate differential ports in Hfss 3d Layout
> Added new methods to create ports on nets of the components and to create differential ports in Hfss 3d Layout

- _unittest/test_14_AedtLogger.py
- pyaedt/aedt_logger.py
This timer can be reset by using new method logger.reset_timer
New method is called logger.info_timer
> Added new method to write a log message with elapsed time and a variable in logger.

- doc/source/User_guide/postprocessing.rst
- pyaedt/modeler/Primitives3DLayout.py
- pyaedt/modules/LayerStackup.py
> Improved documentation and fixed some h3dlayout stackup properties

- _unittest/example_models/T43/cable_modeling_231.aedt
- _unittest/test_01_Design.py
- _unittest/test_02_3D_modeler.py
- _unittest/test_41_3dlayout_modeler.py
- _unittest/test_43_CableModeling.py
- pyaedt/generic/plot.py
- pyaedt/hfss3dlayout.py
- pyaedt/modeler/Primitives3DLayout.py
- pyaedt/modules/SetupTemplates.py
Some methods have been improved and made compatible with 23R1 and some UT has been changed
> Full support to 23R1

- _unittest/test_00_GeometryOperators.py
- pyaedt/generic/constants.py
improve so unit converter accepts both float and list
> improve unit converter

- _unittest/test_28_Maxwell3D.py
- pyaedt/maxwell.py
Eddy effects are now available for both "Transient" and "EddyCurrent" solutions.
Fix #1825 .
> Eddy effects available for Maxwell transient.

- _unittest/test_00_EDB.py
- pyaedt/edb.py
- pyaedt/edb_core/EDB_Data.py
- pyaedt/edb_core/components.py
- pyaedt/edb_core/padstack.py
- pyaedt/edb_core/pingroups.py
- requirements_docs.txt
New property terminals part of edb
Refactoring of pingroups from list of Edb Object to dictionary of PinGroup Class
> New class PinGroup and Terminal

- pyaedt/icepak.py
> Improved create_network_block method

- README.rst
- doc/source/Contributing.rst
- pyaedt/generic/general_methods.py
> Documentation must reference aedt.docs.pyansys.com.

- _unittest/test_11_Setup.py
- _unittest/test_20_HFSS.py
- _unittest/test_41_3dlayout_modeler.py
- pyaedt/modules/SetupTemplates.py
- pyaedt/modules/SolveSetup.py
We used the same approach as in Setup with Sweep templates.
> Refactored Hfss Sweep and Hfss3dLayout sweep to support Siwave and new version properties

- _unittest/test_98_Icepak.py
- pyaedt/icepak.py
- pyaedt/modeler/Primitives.py
- pyaedt/modeler/PrimitivesMaxwellCircuit.py
- pyaedt/modules/MaterialLib.py
- pyaedt/modules/Mesh.py
- requirements_test.txt
Add an example for the heat sink in Icepak.
Improve test for the heat sink in Icepak.
Use snake_case in icepak.py
Remove unnecessary 'pass' statement.
Remove new line in icepak tests.
> Add an example for the heat sink in Icepak.

- _unittest/test_30_Q2D.py
- _unittest/test_31_Q3D.py
- pyaedt/modules/Boundary.py
- pyaedt/q3d.py
Pass Net, source and Sink as an argument. This will give more control to the insert matrix method. In addition, JoinParallel operation now allows Net selection and not only Source selection
> Improve Insert Matrix method in Q3D and Q2D 

- README.rst
Link to contribute section was not working
> Fix link to contribute section in Readme.rst

- pyaedt/modules/PostProcessor.py
If is_log=True then log scale should be set.
Close #1929
> Fix change_field_plot_scale bug

- _unittest/test_14_AedtLogger.py
- pyaedt/edb.py
- pyaedt/generic/general_methods.py
Fix bug in create_cutout_multithread which was causing self-intersection validation issue.
> Fix extent bug

- pyaedt/modeler/Modeler.py
- pyaedt/modules/PostProcessor.py
> Add example to method "export_field_file_on_grid"

- .pre-commit-config.yaml
- pyaedt/edb_core/hfss.py
- pyaedt/generic/TouchstoneParser.py
- pyaedt/icepak.py
As title says.
I also formatted your .pre-commit-config.yaml file and ran ``pre-commit autoupdate`` yo update the hooks on your pre-commit file. It is important to keep them up to date =)
> Solving flake8 issues regarding source import

- .github/workflows/cpython_linux.yml
- .github/workflows/full_documentation.yml
- .pre-commit-config.yaml
- _unittest/test_01_Design.py
- pyaedt/__init__.py
- pyaedt/application/Design.py
- pyaedt/edb.py
- pyaedt/edb_core/edb_data/sources.py
- pyaedt/edb_core/hfss.py
- pyaedt/edb_core/stackup.py
- pyaedt/generic/TouchstoneParser.py
- pyaedt/icepak.py
- pyaedt/modeler/Modeler.py
- pyaedt/modules/PostProcessor.py
Materials need to be created within this method.
> Bug fix create a symmetric stackup

- _unittest/test_00_EDB.py
- pyaedt/edb.py
now is possible to add defeaturing to the cutout extent creation in create_cutout_multithread method
> Cutout extent defeaturing options

- pyaedt/generic/general_methods.py
Co-authored-by: @gmalinve , @maxcapodi78 .
> Use absolute path when opening a file.

- pyaedt/application/Analysis.py
Included bug fix from previous PR
1. Fixed Bug in anaylyze_setup
2. Added NumVariationsToDistribute to analyze_setup
> analyze_setup(...) small fix and feature

- pyaedt/desktop.py
- pyaedt/generic/general_methods.py
-removed tasklist command with psutil
-refactored grpc call.
> refactored Desktop.py

- pyaedt/modeler/Object3d.py
> fixed pins list in circuit when Port in name

- _unittest/test_31_Q3D.py
- pyaedt/q3d.py
to get the list of objects that belongs to a nets. Those can be also filtered by material.
#2040
> Added new method objects_from_nets to Q3d

- pyaedt/hfss.py
> Add Eigenmode option

- pyaedt/hfss.py
> Symmetry is only available with 'Modal' and 'Eigenmode'.

- pyaedt/application/Analysis.py
- pyaedt/application/JobManager.py
needed to modify update_hpc_option() to set this property
> Feature: set DSOJobDistributionInfo's 'AllowedDistributiontypes' with analyze_setup()

- _unittest/test_00_EDB.py
- doc/source/API/CoreEdb.rst
- pyaedt/application/Design.py
- pyaedt/desktop.py
- pyaedt/edb.py
- pyaedt/edb_core/edb_data/hfss_simulation_setup_data.py
- pyaedt/edb_core/edb_data/siwave_simulation_setup_data.py
- pyaedt/edb_core/general.py
- pyaedt/edb_core/siwave.py
> hfss_simulation_setup refactor

- pyaedt/edb.py
- pyaedt/edb_core/nets.py
> Fix cutout

- pyaedt/modeler/Primitives.py
> bug fix insert segment after segmented spline

- pyaedt/edb_core/stackup.py
This happens only in case of solder balls setup. Now there are 2 methods implemented which should cover all the cases
#2124
> fix bug in Edb stackup when in some cases Outline layer was disappearing after a new layer addon. 

- _unittest/test_00_EDB.py
- examples/00-EDB/00_EDB_Create_VIA.py
- examples/00-EDB/06_Advanced_EDB.py
- pyaedt/edb.py
- pyaedt/edb_core/components.py
- pyaedt/edb_core/edb_data/primitives_data.py
- pyaedt/edb_core/layout.py
Added create_polygon_from_points and create_circle methods to core_primitives class. Refactored output of create_rectangle method
Implemented 
#2140 
#2141 
#2142 
#2143
> Added boolean operation to EDBPrimitive Class (unite, intersect and subtract).

- _unittest/test_20_HFSS.py
- pyaedt/aedt_logger.py
- pyaedt/edb.py
- pyaedt/edb_core/nets.py
- pyaedt/modules/SolveSetup.py
Refactored method add_derivatives and extended support to all HFSS setups.
#2133
> Added method to get_derivative_variables to Hfss Setup classes

- .github/workflows/full_documentation.yml
- doc/source/conf.py
The release and version value are not read from the `version.txt` file anymore.
> Use the __version__ attribute to set the release and version value.

- pyaedt/aedt_logger.py
> Logger message can now support several args.

- pyaedt/modules/report_templates.py
> Field solution data not in polyline

- doc/source/Contributing.rst
> Update the links in the contribute section of the documentation.

- _unittest/test_12_PostProcessing.py
- _unittest/test_17_SBR.py
- examples/02-SBR+/SBR_City_Import.py
- pyaedt/modeler/Model3D.py
- pyaedt/modeler/Modeler.py
- pyaedt/modeler/oms.py
- pyaedt/modules/PostProcessor.py
- requirements/requirements_docs.txt
- requirements/requirements_test.txt
- setup.py
Added a new method that downloads data from Open Street Maps and build automatically a 3D stl of terrain, buildings and roads
> Added new method import_from_openstreet_map 

- .github/ISSUE_TEMPLATE/syntax.yml
> Add new issue template for the enhancements of the API design.

- .pre-commit-config.yaml
In addition update hooks version.
> Add blacken-docs to pre-commit.

- README.rst
> Update Documentation and issues links.

- _unittest/test_02_3D_modeler.py
- pyaedt/modeler/cad/Modeler.py
> Scale geometry feature

- pyaedt/modules/SolveSetup.py
Fix small typo in the derivatives method
> Fix derivatives method typo

- _unittest/conftest.py
- _unittest/test_00_EDB.py
- doc/source/EDBAPI/DataEdb.rst
- pyaedt/edb_core/edb_data/primitives_data.py
Implemented:
#2267 
#2268 
#2269 
#2270 
#2271 
#2272
> Implemented new methods in EDBPrimitives and new class to manage Primitves Arc Data

- _unittest/test_98_Icepak.py
- pyaedt/application/Analysis3D.py
- pyaedt/generic/configurations.py
- pyaedt/modules/MonitorIcepak.py
Reformat code
Naming of monitor objects more robust
> Monitor Class enhancements

- _unittest/test_20_HFSS.py
- pyaedt/hfss.py
- pyaedt/modeler/cad/Primitives3D.py
> Add new feature to assign coating method. User can specify an object or face ID

- doc/source/Getting_started/Installation.rst
- doc/source/Resources/pyaedt_with_IDE.bat
Spyder is now optional.
Added 23R1 and 23R2
> Improved batch file.

- _unittest/conftest.py
- examples/02-HFSS/Array.py
- examples/02-HFSS/HFSS_Spiral.py
- examples/02-HFSS3DLayout/EDB_in_3DLayout.py
- examples/02-SBR+/SBR_Time_Plot.py
- examples/03-Maxwell/Maxwell2D_Transient.py
- examples/03-Maxwell/Maxwell3DTeam3.py
- examples/03-Maxwell/Maxwell_Magnet.py
- examples/07-Circuit/Circuit_AMI.py
- examples/07-Circuit/Circuit_Subcircuit_Example.py
- examples/07-Circuit/Circuit_Transient.py
- examples/07-Circuit/EMIT_Example.py
- examples/07-Circuit/Reports.py
Fixing doc errors in examples shown below:
> Minor doc fixes and simplification of code

- examples/01-Modeling-Setup/Configurations.py
- examples/02-HFSS/Machine_learning_applied_to_Patch.py
- pyaedt/generic/design_types.py
- pyaedt/modeler/cad/Primitives3D.py
- pyaedt/modeler/circuits/PrimitivesNexxim.py
Made some minor updates to docstrings and grammar.
> Documentation Updates

- pyaedt/icepak.py
Docstrings update,suggestions by @PipKat
Close #2303
> assign_stationary_wall documentation update

- requirements/requirements_docs.txt
With version >6.1, numerous issues appeared.
> Downgrade Sphinx version.

- _unittest/test_00_EDB.py
- pyaedt/application/Design.py
- pyaedt/desktop.py
- pyaedt/generic/general_methods.py
- requirements/requirements_test.txt
Fixed minor issue that was blocking Desktop to start on 22.1 and below.
> Added Desktop Back Compatibility to v221-

- _unittest/test_00_GeometryOperators.py
- pyaedt/modeler/geometry_operators.py
- orient_polygon docstring fixed.
- orient_polygon returns the points unchanged if the polygon has only 2 points (degenerate).
Fixes issue #2363
> Resolve #2363

- pyaedt/generic/constants.py
> Fix unit_converter bug 

- .github/workflows/unit_tests.yml
- pyaedt/hfss3dlayout.py
> Allow brd import go use a control file

- _unittest/test_26_emit.py
- examples/07-EMIT/ComputeProtectionLevels.py
update unit test and an example to use the new powerAtRx resultType available in the API
> Update emit example due to new powerAtRx result type

- .pre-commit-config.yaml
- _unittest/test_12_PostProcessing.py
- pyaedt/application/design_solutions.py
- pyaedt/modules/AdvancedPostProcessing.py
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/SolveSetup.py
Implemented new method to plot with pyvista and create automatically plot and another method to retrieve default intrinsics from setup.
> New plot_field method in AdvancedPostProcessor

- pyaedt/edb_core/nets.py
- Fix retrieve of TOP/BOTTOM Layers
- Fix issue when no net is defined (case of IDF import)
> 2452 : Fix issue with plot of top/bottom components

- pyaedt/edb_core/nets.py
- Allows to plot a layer not related to a net
- If layer name is "Outline" plot it as a contour
> 2454 : Plot brd outline

- _unittest/test_21_Circuit.py
- pyaedt/modeler/circuits/PrimitivesCircuit.py
- pyaedt/modeler/circuits/object3dcircuit.py
add points property in wire object
> Points property wire

- pyaedt/modules/PostProcessor.py
- pyaedt/modules/report_templates.py
now context supports Source Group for Hfss Report Templates
> added source_group to report_templates.py

- .github/workflows/full_documentation.yml
- .github/workflows/ironpython.yml
- .github/workflows/unit_test_prerelease.yml
- .github/workflows/unit_tests.yml
- _unittest/conftest.py
- _unittest/test_00_EDB.py
- _unittest/test_02_2D_modeler.py
- _unittest/test_08_Primitives3D.py
- _unittest/test_10_Advanced_EDB.py
- _unittest/test_12_PostProcessing.py
- _unittest/test_17_SBR.py
- _unittest/test_20_HFSS.py
- _unittest/test_21_Circuit.py
- _unittest/test_27_Maxwell2D.py
- _unittest/test_43_CableModeling.py
- _unittest/test_98_Icepak.py
- pyaedt/application/Analysis3D.py
- pyaedt/emit_core/__init__.py
- pyaedt/modeler/cad/Modeler.py
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/report_templates.py
- requirements/requirements.txt
- requirements/requirements_test.txt
Configured build machine for prerelease to work with Python 3.7.
> Updated unit test to support 23R2

- _unittest/test_07_Object3D.py
- pyaedt/modeler/cad/Primitives3D.py
> Non model in circle

- pyaedt/modeler/cad/components_3d.py
Edit definition issue in Linux fixed
> Fix edit definition issue

- examples/00-EDB/01_edb_example.py
- pyaedt/generic/process.py
> Fix subprocess

- _unittest/test_12_PostProcessing.py
- pyaedt/generic/plot.py
- pyaedt/modules/AdvancedPostProcessing.py
The user could choose between to which number multiple the field values (10, 20...)
> Add multiplier to the log plot.

- pyaedt/modeler/cad/components_3d.py
- pyaedt/modeler/modeler3d.py
> Fix typo GetDesigns in edit_definition

- pyaedt/modeler/cad/Modeler.py
> added additional parameters to import_3d_cad method.

- doc/source/API/index.rst
- doc/source/Contributing.rst
- doc/source/EDBAPI/index.rst
> fixed broken link to contributing pages

- pyaedt/desktop.py
- pyaedt/edb.py
- pyaedt/generic/general_methods.py
- pyaedt/modeler/modelerpcb.py
> Changed way to check if script is running Ironpython inside desktop

- _unittest/test_01_Design.py
- pyaedt/application/Design.py
- pyaedt/generic/design_types.py
- pyaedt/generic/general_methods.py
> Pyaedt applications will check if the file is locked and if the file is already loaded

- _unittest/test_20_HFSS.py
- _unittest/test_41_3dlayout_modeler.py
- pyaedt/modules/SolveSetup.py
> implemented get_sweep for Hfss and 3D Layout

- README.rst
> Correct typo in documentation

- pyaedt/misc/Console.py_build
- pyaedt/misc/Jupyter.py_build
- pyaedt/misc/Run_PyAEDT_Script.py_build
Error message improvements for Graceful checks and Error dialogs if Toolkit files are missing (Ref #2703)
Improving error message in the 2 toolkits which were not updated.
> Error message improvements for Graceful checks and Error dialogs if Toolkit files are missing (Ref #2703)

- README.rst
- _unittest/test_31_Q3D.py
- pyaedt/q3d.py
- Make all variation solved available in export_equivalent_circuit
- Fix typo in README.rst
- Add example
Close #2602
> Fix solved variations bug in export_equivalent_circuit method

- pyaedt/desktop.py
- pyaedt/misc/Run_PyAEDT_Script.py_build
- pyaedt/misc/Run_PyAEDT_Toolkit_Script.py_build
- pyaedt/misc/install_extra_toolkits.py
Report errors if toolkit source files not found and misc. cleanup & fixes of toolkit setup files (Ref #2733)
> Report errors if toolkit source files not found and misc. cleanup & fixes of toolkit setup files (Ref #2733)

- pyaedt/maxwell.py
> Assign current in ElectroDCConduction solution type

- _unittest/test_12_PostProcessing.py
- pyaedt/application/Analysis.py
- pyaedt/modules/solutions.py
- pyproject.toml
- If show is False, return Plotter object not shown
- Fix submit job issue
- Add 'all' to toml
Close #2598 
Close #2644
> polar_plot_3d_pyvista return Plotter object and fix submit job bug

- pyaedt/modeler/advanced_cad/parts.py
> Fix rotations axis in create_sbr_radar_from_json

- _unittest/test_00_Advanced_EDB.py
- pyaedt/edb_core/edb_data/components_data.py
> Improved assign_rlc_model method

- _unittest/test_41_3dlayout_modeler.py
- pyaedt/modeler/pcb/object3dlayout.py
> Implement CenterLine into h3d modeler

- _unittest/test_08_Primitives3D.py
- _unittest/test_20_HFSS.py
- examples/01-Modeling-Setup/Optimetrics.py
- examples/02-HFSS/Flex_CPWG.py
- examples/02-HFSS/HFSS_Choke.py
- examples/02-HFSS/HFSS_Spiral.py
- examples/02-HFSS/Waveguide_Filter.py
- examples/06-Multiphysics/Hfss_Icepak_Coupling.py
- pyaedt/hfss.py
- pyaedt/modeler/advanced_cad/stackup_3d.py
- wave_port
- lumped_port
- circuit_port to simplify the port creation
> New methods in hfss to simplify ports creation

- examples/05-Q3D/Q3D_from_EDB.py
- pyaedt/edb_core/stackup.py
I've added your suggestions of previous PR which I've erroneously merged.
> docstrings fix

- _unittest/test_08_Primitives3D.py
- pyaedt/maxwell.py
- pyaedt/modeler/cad/Modeler.py
- pyaedt/modeler/cad/Primitives.py
- pyaedt/modeler/cad/Primitives3D.py
- pyaedt/modeler/cad/components_3d.py
- pyaedt/modeler/cad/elements3d.py
- pyaedt/modeler/cad/object3d.py
- pyaedt/modeler/cad/polylines.py
- pyaedt/modeler/circuits/object3dcircuit.py
- pyaedt/modeler/pcb/object3dlayout.py
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/SolveSetup.py
- pyaedt/modules/solutions.py
made hidden some private methods (like m_Editor)
added property objects_by_names since most of users knows the object name and not the id
> Object 3d refactoring.

- _unittest/test_26_emit.py
- pyaedt/emit_core/results/results.py
- pyaedt/emit_core/results/revision.py
Fixes B776164: revision changes not saved
Fixes S770448: revamp Revisions
Fixes B813304: issues saving to directory with multiple aedt projects
> add some functions to Revisions and fix some bugs

- _unittest/test_00_EDB.py
- pyaedt/edb_core/components.py
- pyaedt/edb_core/edb_data/components_data.py
Now user can run
edb.components.instances["C1"].is_enabled = False
to disable the component
#2779
> Added property is_enabled with getters and setters in Compontents.

- _unittest/test_00_EDB.py
- pyaedt/edb.py
- pyaedt/edb_core/nets.py
find_and_fix_disjoint_nets which has now a new argument order_by_area which rename based on area.
#2788
> fix cutout method that in some cases was causing dc shorts and find_and_fix_disjoint_nets

- _unittest/test_22_Circuit_DynamicLink.py
- pyaedt/desktop.py
- pyaedt/edb.py
- pyaedt/generic/general_methods.py
- pyaedt/modeler/circuits/PrimitivesCircuit.py
Sometimes the GRPC API fails to connect to a new AEDT Session. This new method launches AEDT in a separate thread and then tries to connect to it on a given port.
> Launch desktop from cmd

- pyaedt/application/Analysis.py
> Wait for batch job to release queue file properly.

- _unittest/test_20_HFSS.py
- doc/source/API/PrimitivesCircuit.rst
- pyaedt/edb_core/edb_data/simulation_configuration.py
- pyaedt/hfss.py
- pyaedt/modeler/circuits/PrimitivesEmit.py
- pyaedt/modeler/circuits/PrimitivesNexxim.py
- pyaedt/modeler/circuits/object3dcircuit.py
- pyaedt/modeler/schematic.py
- pyaedt/modules/PostProcessor.py
- Add Nexxim Schematic classes to the documentation
- Add option to disable the auto renaming of the terminals
> Add Circuit schematic to the documentation

- _unittest/test_41_3dlayout_modeler.py
- pyaedt/modeler/cad/Primitives.py
- pyaedt/modeler/modelerpcb.py
- pyaedt/modeler/pcb/object3dlayout.py
- pyaedt/modeler/schematic.py
- pyaedt/modules/LayerStackup.py
This is not possible directly, so we remove and recreate the line.
> Added 2 new methods in Line in 3d Layout to add and remove points.

- doc/source/Resources/pyaedt_with_IDE.bat
- pyaedt/misc/aedtlib_personalib_install.py
> When Pyaedt is installed from Button in 23R2 there is no need to launch a new session of Desktop.

- pyaedt/edb.py
In case multiple polygons are generated the one with biggest area is taken as extent
> fix extent creation when multiple polygons are generated from the computation.

- README.rst
Update the support email address in the README and do an overall edit. (The support email address in the project's TOML file was already updated.)
> Doc/update support email and do an overall edit of the README

- .github/dependabot.yml
- doc/source/conf.py
- pyproject.toml
Update the switcher config for gh-pages layout.
Update the dependabot location for package manifest
> Doc: update the switcher ``conf`` to pyansys-action-v4 layout.

- _unittest/test_28_Maxwell3D.py
- pyaedt/modeler/modeler3d.py
> add additional bool to apply mesh sheets - objects segmentation

- _unittest/test_09_VariableManager.py
- pyaedt/application/Design.py
- pyaedt/application/Variables.py
> Independent design and project variable refactoring

- _unittest/test_00_EDB.py
- examples/00-EDB/00_EDB_Create_VIA.py
- pyaedt/edb_core/layout.py
> Added support of Arch Heights to create_polygon and create_polygon_from_points methods.

- pyaedt/application/Analysis.py
In linux sometimes it gives SameFileError.
> added try except to shutil copy file for analyze method.

- pyaedt/desktop.py
> Fix Student Version 22R2 launcher

- pyaedt/maxwell.py
learning to update documentation
> fix documentation typos

- _unittest/test_00_EDB.py
- pyaedt/generic/general_methods.py
- pyaedt/modeler/cad/Primitives3D.py
Used this new method in create_layoutcomponent method
> added new method to normalize path slashes.

- doc/source/Getting_started/Installation.rst
- doc/source/Resources/PyAEDTInstallerFromDesktop.py
- pyaedt/misc/install_extra_toolkits.py
Modify python installer script to work in 2023R1
> Add ansys new repository to toolkits

- _unittest/test_98_Icepak.py
- pyaedt/icepak.py
> New block assignment function

- pyaedt/circuit.py
- pyaedt/edb.py
- pyaedt/edb_core/hfss.py
The initial multizone was not preserved and has been fixed.
> True siwave multizone support + bug fix

- pyaedt/modeler/circuits/PrimitivesCircuit.py
> Add new touchstone format. It was working only with Ansys output format "! Port"

- _unittest/test_02_3D_modeler.py
- pyaedt/modeler/cad/Modeler.py
> Fix bug in delete coordinate system referred to different coordinate system

- pyaedt/hfss.py
> Add documentation for the hybrid solution.

- pyaedt/common_rpc.py
Service Manager: Log location of AEDT (helpful if multiple AEDTs on a machine); use logger instead of prints
> Service Manager: Log location of AEDT (helpful if multiple AEDTs on a machine); use logger instead of prints

- _unittest/test_41_3dlayout_modeler.py
- pyaedt/modeler/modelerpcb.py
Add method to run oEditor.GeometryCheckAndAutofix in HFSS 3D Layout
> Geometry check

- doc/source/EDBAPI/NetsEdb.rst
> EDB Nets class fix for doc

- pyaedt/modules/SolveSetup.py
export to hfss with net name bug fix
> export to hfss with net name bug fix

- pyaedt/edb_core/edb_data/primitives_data.py
The layer_name setter from primitive was crashing due to stackup refactoring
> primitive layer_name setter bug fix

- _unittest/test_00_EDB.py
- pyaedt/edb_core/padstack.py
Adding rectangle shape support for antipad when creating padstack definition.
> support padsatck with rectangle shape for antipads

- pyaedt/edb_core/edb_data/primitives_data.py
#3173 
@svandenb-dev please run additional test on it
> Improve subtract

- _unittest/test_00_EDB.py
- pyaedt/edb.py
- pyaedt/edb_core/components.py
Added new check to pingroup creation to check if the pingroup exists and is identical to the original one.
> added new property terminals to Edb

- _unittest/test_00_EDB.py
- pyaedt/edb_core/edb_data/primitives_data.py
Some boolean bug fix, intersect + primitive clone
> Edb boolean bug fix

- _unittest/test_12_PostProcessing.py
- pyaedt/modules/PostProcessor.py
> added options to export_field_jpg to export selections of objects, axis, grid, ruler and region

- _unittest/test_20_HFSS.py
- pyaedt/hfss.py
> added method set_radiated_power_calc_method

- _unittest/test_41_3dlayout_modeler.py
- pyaedt/hfss3dlayout.py
> added argument air_horizontal_padding to edit_hfss_extent method in Hfss 3D Layout

- pyaedt/modeler/cad/Primitives3D.py
> Add axis in bondwire

- _unittest/test_20_HFSS.py
- pyaedt/hfss.py
> Add impedance multiplier

- _unittest/test_12_1_PostProcessing.py
- examples/03-Maxwell/Maxwell2D_Transient.py
- examples/06-Multiphysics/Hfss_Icepak_Coupling.py
- pyaedt/modules/AdvancedPostProcessing.py
moved method animate_fileds_from_aedtplt_2 to deprecated
> added new method plot_animated_field

- _unittest/test_21_Circuit.py
- pyaedt/application/AnalysisNexxim.py
- pyaedt/modeler/calculators.py
app.excitations in circuit returns a dictionary. These methods and property were not working.
> Fix get sparameter in circuit

- _unittest/conftest.py
- _unittest/example_models/TMaxwell/Transient_StrandedWindings.aedt
- _unittest/test_20_HFSS.py
- _unittest/test_28_Maxwell3D.py
- _unittest/test_31_Q3D.py
- pyaedt/__init__.py
- pyaedt/application/Analysis.py
- pyaedt/application/Design.py
- pyaedt/application/Variables.py
- pyaedt/common_rpc.py
- pyaedt/desktop.py
- pyaedt/edb_core/dotnet/database.py
- pyaedt/edb_core/edb_data/control_file.py
- pyaedt/emit_core/__init__.py
Removed global messages from unit tests
> remove aedt_logger from pyaedt init.

- examples/05-Q3D/Q3D_DC_IR.py
Bug fixing:
1. Typos
2. removed hard-coded text wherever possible
3. Exported the obj file and png file from Q3D after placing inductors and resistors.
> DC_IR_bug fix

- _unittest/test_20_HFSS.py
- pyaedt/hfss.py
> Support perfect 'E' and 'H' for sheets with eigenmode.

- pyaedt/modeler/circuits/PrimitivesCircuit.py
> Add new touchstone format

- pyaedt/modeler/modeler3d.py
> All variables in 3DComponent creation by default

- .github/workflows/full_documentation.yml
- .github/workflows/nightly-docs.yml
get the html artifact for EDBAPI indexing to fix https://github.com/ansys/pyaedt/actions/runs/5959317787
> fix : upload EDBAPI artifact while indexing

- pyaedt/generic/general_methods.py
This update ensures correct version formatting when the version number is less than 221.
> Changed version comparison from "222" to "221" 

- _unittest/test_12_1_PostProcessing.py
- _unittest/test_12_PostProcessing.py
- pyaedt/modules/PostProcessor.py
Get the list of available solutions that can be used for the reports. 
This list differs from the one obtained with ``app.existing_analysis_sweeps``, because it includes additional elements like "AdaptivePass"
> added post.available_report_solutions

- pyaedt/application/Analysis3D.py
- pyaedt/generic/plot.py
- pyaedt/modeler/modeler3d.py
- pyaedt/modules/AdvancedPostProcessing.py
fixed bug in create_3d_components when multiple coordinate where present.
> Added Dark mode to plot in pyvista

- pyaedt/desktop.py
- pyaedt/modeler/cad/components_3d.py
Fix 3d component edit_definition
> Fix student version issue which was causing error in version check

- pyaedt/edb_core/siwave.py
Corrects typos in documentation for certain EdbSiwave methods
> Improve documentation

- _unittest_solvers/test_26_emit.py
D888528: fix pyaedt test for n-1 run behavior change
> D888528 fixes 2

- pyaedt/icepak.py
Close #3542. Documentation fix for create_network_block
> Close #3542. Documentation fix for create_network_block

- _unittest/test_01_3dlayout_edb.py
- pyaedt/application/Analysis3DLayout.py
Call DesignOptions instead of SetDesignSettings for HFSS 3D Layout designs.
Fixes #3632
> Fix change_design_settings for HFSS 3D Layout

- doc/source/Resources/PyAEDTInstallerFromDesktop.py
- pyaedt/generic/clr_module.py
> Remove Delcross from reference

- _unittest/test_11_Setup.py
- _unittest_solvers/test_31_Q3D.py
- pyaedt/application/Analysis.py
- pyaedt/modeler/cad/Modeler.py
- pyaedt/modeler/cad/Primitives.py
- pyaedt/modules/MeshIcepak.py
- pyaedt/modules/SolveSetup.py
- pyaedt/q3d.py
> improved method create_frequency_sweep to support all optional arguments.

- _unittest/test_98_Icepak.py
- examples/04-Icepak/Sherlock_Example.py
- pyaedt/icepak.py
> Fix bug in import PCB in Icepak to support Hfss3d Layout extent

- _unittest/test_01_3dlayout_edb.py
- pyaedt/modeler/pcb/Primitives3DLayout.py
> Added possibility to change the z location of a 3d component when placed in 3d Layout

- pyaedt/hfss.py
> doc: Improve documentation for lumped port.

- pyaedt/application/Analysis.py
- pyaedt/circuit.py
- pyaedt/hfss.py
- pyaedt/hfss3dlayout.py
this fixes #3299, enhancing S2P export by renormalization option as well as Gamma/Imp comments
> fix issue #3299

- examples/06-Multiphysics/MRI.py
- pyaedt/application/Analysis.py
- pyaedt/misc/pyaedt_local_config.acf
> Fix analyze method

- _unittest/test_00_EDB.py
- pyaedt/edb_core/edb_data/primitives_data.py
```
trace = edb.modeler.create_trace([[0, 0], [0, 10e-3]], "1_Top", "0.1mm", "trace_with_via_fence")
edb.padstacks.create_padstack("via_0")
trace.create_via_fence("1mm", "1mm", "via_0")
```
> Method to create via fence on both sides of the trace

- pyaedt/modeler/cad/Primitives2D.py
> clean create_region method

- _unittest/test_28_Maxwell3D.py
- pyaedt/maxwell.py
ADD Maxwell assign radiation
oModule = oDesign.GetModule("BoundarySetup")
oModule.AssignRadiation(
[
"NAME:Radiation1",
"Objects:=" , ["Region"]
])
Close #3764
> ADD Maxwell assign radiation

- _unittest/test_01_Design.py
- pyaedt/application/Analysis.py
> improve nominal variation

- pyaedt/aedt_logger.py
- pyaedt/modeler/cad/elements3d.py
> Clear error when GetFaceCenter fails

- pyaedt/misc/Run_PyAEDT_Script.py_build
- pyaedt/misc/Run_PyAEDT_Toolkit_Script.py_build
> Add GRPC port

- pyaedt/modules/Material.py
> Non linear method private

- CONTRIBUTING.md
Reuse some of the content available in a past [PyAEDT discussion](https://github.com/ansys/pyaedt/discussions/3809#discussion-5783012).
This will be helpful to guide our users willing to either report issues, or enhance the code themselves.
Thanks @Samuelopez-ansys for writing the content.
> DOC: Explain how to contribute in details in the CONTRIBUTION.md file.

- _unittest/test_20_HFSS.py
- doc/styles/Vocab/ANSYS/accept.txt
- pyaedt/application/Design.py
- pyaedt/application/design_solutions.py
- pyaedt/hfss.py
- pyaedt/modules/Boundary.py
Object-oriented not implemented in AEDT API when Hybrid region
> Assign FEBI method

- pyaedt/application/Analysis.py
- pyaedt/modules/Material.py
- added "PhysicsTypes" property on Surface material creation.
- fixed `value_with_units` in case `units=""`
> Bugfix on Surface material creation and value_with_units 

- _unittest/test_98_Icepak.py
- pyaedt/icepak.py
> Add resistance boundary

- pyaedt/edb_core/edb_data/primitives_data.py
Add a new input parameter net_name.
> Create via fence bug fix

- examples/01-Modeling-Setup/HFSS_CoordinateSystem.py
> create object cs in example

- .github/workflows/build_documentation.yml
- .github/workflows/full_documentation.yml
- .github/workflows/nightly-docs.yml
> MAINT: update ansys action to v5

- pyaedt/modeler/cad/components_3d.py
- pyaedt/modeler/cad/object3d.py
Refactored object3d group_name property to be updated in real time if changes are done in the UI.
> group_name property gets updates from the UI

- .github/workflows/build_documentation.yml
- pyproject.toml
This update consists in using a previous dependency of ansys-sphinx-theme (aka pydata-sphinx-theme) whose latest version (0.15.1) broke the side bar of the documentation page.
> DOC: Update ansys-sphinx-theme to fix documentation build

- _unittest/example_models/T98/one_native_component.aedt
- _unittest/test_98_Icepak.py
- pyaedt/application/Analysis.py
Close  #4066
When just one component is loaded, the command` data_vals=list(data_vals)` keeps just the keys of the dictionary. We need instead `data_vals=[data_vals]`.
> Fix native component loading 

- _unittest/test_11_Setup.py
- pyaedt/modules/SolveSetup.py
Add two methods `get_sweeps` and `delete_sweep` to the `SetupHFSS` class according to the scripting guide.
Related tests are included.
> Add `get_sweeps` and `delete_sweep` to `SetupHFSS`

- .github/labeler.yml
> CI: fix labeler to match v5 structure

- examples/04-Icepak/Icepak_CSV_Import.py
- pyaedt/icepak.py
I improve the example with these modifications:
- remove 2R network assignment function from the example to use the one already present in pyAEDT
- remove the board side column from the csv file and remove the line for the board creation (https://github.com/ansys/example-data/pull/220)
- remove and substitution of deprecated methods
- coding styles improvements
> Icepak csv example improvement

- AUTHORS
> MISC: follow pyansys repo guidelines

- .pre-commit-config.yaml
- README.md
- doc/source/Getting_started/Contributing.rst
- doc/source/Getting_started/index.rst
- doc/source/User_guide/index.rst
- Readme
- Add missing margin for grids
- update broken links
> Update readme and broken links

- pyaedt/icepak.py
"Mapping HFSS EM losses." --> "Mapping EM losses."
> Changed info message wording:

- _unittest/test_01_Design.py
- pyaedt/application/Variables.py
> Design dataset 'delete' function fixed

- pyaedt/desktop.py
- pyaedt/generic/settings.py
> Add custom LSF

- _unittest/test_launch_desktop.py
- pyaedt/application/Analysis.py
- pyaedt/application/Analysis3D.py
- pyaedt/application/Analysis3DLayout.py
- pyaedt/application/AnalysisMaxwellCircuit.py
- pyaedt/application/AnalysisNexxim.py
- pyaedt/application/AnalysisRMxprt.py
- pyaedt/application/AnalysisTwinBuilder.py
- pyaedt/generic/settings.py
> Add lazy load flag

- pyaedt/application/Analysis3D.py
- pyaedt/application/Design.py
- pyaedt/circuit.py
- pyaedt/generic/LoadAEDTFile.py
- pyaedt/generic/plot.py
- pyaedt/hfss.py
- pyaedt/modeler/cad/Primitives.py
- pyaedt/modules/Boundary.py
- pyaedt/modules/PostProcessor.py
- pyaedt/modules/SolveSetup.py
- pyproject.toml
- pytest.ini
Remove pytest.ini file to put filterwarnings in pyproject.toml file.
Add UserWarning to avoid unwanted warnings when testing.
Closes #4222
> TESTS: Refact warnings filtering

- examples/07-TwinBuilder/02-Wiring_A_Rectifier.py
It was correct in the documentation ("degrees") but it was not correct until now.
> Fix angle in degrees example

- .github/workflows/cpython_linux.yml
- .github/workflows/full_documentation.yml
- .github/workflows/ironpython.yml
- .github/workflows/nightly-docs.yml
- .github/workflows/unit_tests.yml
> CI: Update license

- _unittest_solvers/test_00_analyze.py
- pyaedt/generic/spisim.py
- pyaedt/misc/spisim_com_configuration_files/com_parameters.py
Minor update to improve usability
> Com enhancement

- _unittest/test_98_Icepak.py
- pyaedt/modeler/cad/Primitives.py
> Fix for subregion with multiple objects

- _unittest/test_20_HFSS.py
- pyaedt/hfss.py
Add anisotropic impedance boundary
> Add multiple faces option to impedance boundary

- _unittest/test_04_SBR.py
- pyaedt/hfss.py
> Add name in create sbr antenna method

- _unittest_solvers/test_31_Q3D.py
- pyaedt/emit_core/results/revision.py
- pyaedt/generic/compliance.py
- pyaedt/generic/ibis_reader.py
- pyaedt/modeler/cad/Primitives3D.py
- pyaedt/modeler/cad/elements3d.py
- pyaedt/modeler/circuits/PrimitivesCircuit.py
- pyaedt/modeler/circuits/PrimitivesEmit.py
- pyaedt/modeler/circuits/PrimitivesNexxim.py
- pyaedt/modeler/circuits/object3dcircuit.py
- pyaedt/modeler/modeler3d.py
- pyaedt/modeler/pcb/Primitives3DLayout.py
- pyaedt/modules/AdvancedPostProcessing.py
Add `assert` statement in tests.
Remove unused variables.
Do not use mutable variables in method's signatures.
> MAINT: Fix various code issues like the direct iteration over dictionaries.

- pyaedt/modeler/cad/object3d.py
Opening a PR in the name of @marcobiasizzo as CICD cannot run from forks.
See https://github.com/ansys/pyaedt/pull/4478
> DOC: Fix typo in bottom edge function description

- pyaedt/modules/Mesh.py
- setup name needed instead of the design name
- added example
> fixed generate_mesh function documentation:

- pyaedt/maxwell.py
> FIX: Add the missing 3D solution types in the assign_insulating function.

- _unittest/test_03_Materials.py
- _unittest/test_13_LoadAEDTFile.py
- _unittest/test_28_Maxwell3D.py
- examples/03-Maxwell/Maxwell_Transformer_Coreloss.py
- pyaedt/modeler/advanced_cad/stackup_3d.py
- pyaedt/modules/Material.py
- pyaedt/modules/MaterialLib.py
Materials and Material arguement refactoring
> Refactoring arguments in Material Class

- pyaedt/generic/general_methods.py
- pyaedt/generic/plot.py
> fixed plot vectors

- examples/05-Q3D/Q3D_DC_IR.py
- pyaedt/modules/solutions.py
Add intrinsics in DCIR example
Close #4577
> REFACT: Add SurfaceOnly

- _unittest/test_28_Maxwell3D.py
- examples/03-Maxwell/Maxwell2D_Electrostatic.py
- pyaedt/modules/AdvancedPostProcessing.py
Fix export field plot streamlines
fix maxwell test
fix maxwell example
> fix export field plot streamline 

- _unittest_solvers/test_00_analyze.py
Follow up of #4618 where the restriction was performed on 2024.2
> TESTS: Limit skip to AEDT 2024.1

- .github/workflows/nightly-docs.yml
As title says. An incorrect job need was used in the YAML file.
> CI: Fix nightly-docs needs

- doc/styles/Vocab/ANSYS/accept.txt
As title say. Should fix CI for #4640
> DOCS: Fix vale report on doc style

- pyaedt/modeler/modeler3d.py
- pyaedt/workflows/project/import_nastran.py
When only solids where present in the model, it was not importing in AEDT.
> FIX: improve nastran method. 

- pyaedt/modeler/modeler3d.py
When a nastran file contained number with exponentials in some cases it failed to parse points
> FIX: grid points import where e letter is already part of the nas file

- _unittest/test_21_Circuit.py
- pyaedt/modeler/circuits/object3dcircuit.py
Cherry-pick branch:
https://github.com/ansys/pyaedt/pull/4662
@HaiwenZhang
> FEAT: enforce touchstone model passive

- pyaedt/modules/Mesh.py
> FIX: Skin depth deprecation warning bug

- pyaedt/icepak.py
> FIX: Assign conducting plate bug

- pyaedt/generic/plot.py
- pyaedt/modules/AdvancedPostProcessing.py
- pyaedt/modules/solutions.py
Expose the keyword argument "show" for all methods that create matplotlib figures. Default behavior is unchanged. Plots will be rendered when the method is called.
> CHORE: expose show for plotting

- pyaedt/desktop.py
> FIX: submit_job improvement to allow the possibility to pass a server path

- .pre-commit-config.yaml
- doc/styles/Vocab/ANSYS/accept.txt
- pyaedt/emit_core/results/revision.py
- pyaedt/generic/compliance.py
- pyaedt/modeler/cad/Primitives3D.py
> CHORE: Update codespell version

- _unittest/test_20_HFSS.py
- pyaedt/modeler/modeler3d.py
- pyaedt/modules/solutions.py
- pyproject.toml
replaced fast-simplification with decimate_pro alghoritm from pyvista
added pyvista preview to the importer
added pyvista preview to simplify_mesh method
> FEAT: replaced fast-simplification with decimate_pro alghoritm from pyvista

- _unittest_solvers/test_31_Q3D.py
- doc/source/Getting_started/ClientServer.rst
- pyaedt/q3d.py
> FEAT: Auto Identify Net only if conductor exist

- _unittest/test_07_Object3D.py
- _unittest/test_08_Primitives3D.py
- _unittest/test_09_Primitives2D.py
- _unittest/test_14_AedtLogger.py
- pyaedt/modeler/cad/Primitives.py
- pyaedt/modeler/cad/object3d.py
to apply to more than one edge/vertice at the same time
> FEAT: Added chamfers and fillet methods to Object3d 

- pyaedt/application/Analysis.py
> FEAT: Allow add specific variation list to export_results

- _unittest/test_01_Design.py
- pyaedt/application/Analysis.py
- pyaedt/application/Design.py
- pyaedt/application/Variables.py
- pyaedt/modeler/cad/elements3d.py
- pyaedt/modules/SolveSetup.py
Close #4801 
By default is sorting with X values, but in 3D Dataset could be dangerous, so we have added a disable of the sorting.
> FEAT: Sort flag in dataset

- _unittest/test_04_SBR.py
- pyaedt/sbrplus/hdm_parser.py
Refactor HDM parser to remove vulnerabilities.
> REFACTOR: HDM parser

- pyproject.toml
TOML topic failed again with @SMoraisAnsys modifications. I have triggered again the release, I think it should work with these modifications.
https://github.com/ansys/pyaedt/actions/runs/9587855486
Once the release is created, we can merger this PR.
> CHORE: Fix TOML Topic

- pyaedt/misc/misc.py
- pyaedt/rpc/rpyc_services.py
- pyproject.toml
Refactor Rpyc services parser to remove vulnerabilities.
Note that we execute the content of a file so this can also be a point of vulnerability. However, that's the purpose of some of the service so we can't do much there.
> REFACTOR: Rpyc services

- _unittest/test_28_Maxwell3D.py
- examples/03-Maxwell/Maxwell3D_Team3_bath_plate.py
- pyaedt/generic/plot.py
- pyaedt/modules/PostProcessor.py
> FIX: context maxwell

- .github/workflows/ci_cd.yml
- pyaedt/circuit.py
- pyaedt/emit.py
- pyaedt/hfss.py
- pyaedt/hfss3dlayout.py
- pyaedt/icepak.py
- pyaedt/maxwell.py
- pyaedt/maxwellcircuit.py
- pyaedt/mechanical.py
- pyaedt/q3d.py
- pyaedt/rmxprt.py
- pyaedt/twinbuilder.py
new_desktop_session deprecation warning was missed in App initialization
> FIX: Missed deprecation warning

- pyaedt/workflows/hfss3dlayout/export_layout.py
use the new method to export bom.
> REFACTOR: export bom

- _unittest/test_01_Design.py
- pyaedt/application/Design.py
Duplicate of https://github.com/ansys/pyaedt/pull/4857 to allow secrets to be working correctly.
> FIX: Design save project mkdir

- pyaedt/modeler/advanced_cad/stackup_3d.py
(cherry picked from commit 3194f09a50a6a010d2c61d04c5f5e38c9f23cbbf)
@fwlfHS I have cherry picked your commits to launch the GitHub actions. Thank you for your contribution!
> DOCS: Fix Docstring and Examples for stackup_3d loc advanced_cad

- examples/06-Multiphysics/Circuit-HFSS-Icepak-coupling.py
Adding Circuit-HFSS-Icepak coupling example
> DOCS: Adding Circuit-HFSS-Icepak coupling example

- pyaedt/modules/MeshIcepak.py
> FIX: read mesh settings

- pyaedt/modules/AdvancedPostProcessing.py
> FIX: Object field summary method

- _unittest/example_models/T32/assm_test.aedt
- _unittest/test_32_RMxprt.py
- examples/03-Maxwell/RMxprt.py
- pyaedt/application/Analysis.py
- pyaedt/application/AnalysisRMxprt.py
- pyaedt/application/Design.py
- pyaedt/rmxprt.py
> FEAT: Improved rmxprt robustness

- pyaedt/desktop.py
Was causing an error in dotnet approach
> FIX: added check in desktop_release

- pyaedt/modules/PostProcessor.py
> FEAT: Add missed option in ExportToFile 

- _unittest/test_08_Primitives3D.py
- pyaedt/modeler/cad/Primitives3D.py
I have cherry-picked this PR: #5036
> FEAT: Create equationbased surface

- _unittest_solvers/test_00_analyze.py
- src/ansys/aedt/core/application/analysis.py
> FIX: Solve setup in optimetrics

- doc/source/conf.py
- pyproject.toml
> DOCS: Use new ansys-sphinx-theme

- _unittest/example_models/T12/template.rpt
- _unittest/test_12_PostProcessing.py
- src/ansys/aedt/core/modeler/cad/components_3d.py
- src/ansys/aedt/core/modeler/cad/primitives.py
- src/ansys/aedt/core/modeler/modeler_3d.py
- src/ansys/aedt/core/modules/post_processor.py
- src/ansys/aedt/core/modules/report_templates.py
GetChildNames("Groups") was returning a tuple in previous versions, casting to list to have consistent results.
Add ApplyReportTemplate
> FIX: Cast GetChildNames("Groups") to list

- _unittest/test_12_PostProcessing.py
- src/ansys/aedt/core/modules/post_processor.py
Close #5068 
I have added the CreateReportFromTemplate inside the method create_report_from_configuration, this method imports the report from the  AEDT format: .RPT
> FEAT: CreateReportFromTemplate inside create_report_from_configuration

- src/ansys/aedt/core/modules/post_processor.py
> FEAT: Add paste option

- doc/source/User_guide/index.rst
Settings refactoring was not added into the documentation and this PR should fix that problem.
> DOCS: Add missing settings section

- _unittest/test_08_Primitives3D.py
- src/ansys/aedt/core/modeler/cad/primitives_3d.py
> FIX: Create cone with same inner and outer radius

- README.md
As title says. Follows #5154 which was incomplete.
> DOCS: Fix pyaedt logo in README.md

- src/ansys/aedt/core/desktop.py
This PR adds the automatic desktop closure at python exit.
This should be useful for people not remembering about closing the desktop (all the more when using `grpc`) or when an exception is raised.
> FEAT: Close desktop at exit

- doc/source/index.rst
- doc/source/release_1_0.rst
As title says. This PR update the documentation on breaking changes about the python version deprecation.
> DOCS: Python version deprecation breaking change

- _unittest/test_01_3dlayout_edb.py
- src/ansys/aedt/core/modeler/pcb/object_3d_layout.py
Added new method in HFSS 3D Layout nets to plot using matplotlib the net.
> FEAT: Added method to plot nets in Hfss 3d Layout which uses Edb Plot

- examples/04-Icepak/Icepak_ECAD_Import.py
- src/ansys/aedt/core/aedt_logger.py
- src/ansys/aedt/core/application/design.py
- src/ansys/aedt/core/generic/grpc_plugin_dll_class.py
- src/ansys/aedt/core/modeler/cad/primitives.py
- src/ansys/aedt/core/modeler/modeler_pcb.py
settings.enable_debug_grpc_api_logger = True 
will log all methods to the log as debug lines.
> FEAT: LOG messages

- src/ansys/aedt/core/modeler/cad/primitives_3d.py
> FIX: Remove unused lines

- .github/workflows/manual_draft.yml
- .github/workflows/nightly-docs.yml
Follow up of #5260 where changes weren't applied on every workflow.
> CI: Update artifact action on every workflows

- src/ansys/aedt/core/modules/material_lib.py
> FIX: Remove confusing/erroneous info message

- doc/source/Resources/pyaedt_installer_from_aedt.py
Extend the `pyaedt` installer with a disclaimer about third party software.
Close #5277
> DOCS: Add disclaimer to pyaedt installer

- src/ansys/aedt/core/workflows/templates/pyaedt_utils.py
> FIX: Remove Konsole from the terminal list

- src/ansys/aedt/core/visualization/post/post_common_3d.py
This PR fix the bug when plotting DC field on layer which doesn't exist field data.
> FIX: Field plot

- .pre-commit-config.yaml
This will allow PRs created to update pre-commit to comply with PyAnsys standard.
> CHORE: Improve pre-commit PR title

- src/ansys/aedt/core/filtersolutions_core/export_to_aedt.py
This PR moves the function from a wrong place.
> FIX: Replace a function from wrong position

- src/ansys/aedt/core/filtersolutions_core/export_to_aedt.py
This PR corrects a typo in the function that is fixed in the DLL.
> FIX: Typo correction

- _unittest/test_02_3D_modeler.py
- src/ansys/aedt/core/desktop.py
- src/ansys/aedt/core/modeler/cad/primitives.py
Changes:
- add a return value to a method to ease testing;
- add tests on method that didn't have any;
- add "no cover" on cases difficult to reproduce and logging.
Follow up of https://github.com/ansys/pyaedt/pull/5332.
> CHORE: Improve code coverage

- src/ansys/aedt/core/visualization/advanced/farfield_visualization.py
- src/ansys/aedt/core/visualization/advanced/misc.py
- src/ansys/aedt/core/visualization/advanced/touchstone_parser.py
- src/ansys/aedt/core/visualization/post/field_data.py
- src/ansys/aedt/core/visualization/post/field_summary.py
As title says. Applies the following template
```python
try:
import ... as ...
except ImportError:
warnings.warn("....")
```
This will help for testing with fewer dependencies.
> REFACTOR: Homogeneize imports of extra deps

- src/ansys/aedt/core/visualization/advanced/misc.py
- src/ansys/aedt/core/visualization/plot/pyvista.py
- src/ansys/aedt/core/visualization/report/common.py
Changes fixing issues raised by bandit.
> REFACTOR: Regular code improvement

- .github/workflows/ci_cd.yml
- .github/workflows/nightly-docs.yml
- doc/source/conf.py
- pyproject.toml
Changes include removing deprecated options (meiliserach related) and adding new options related to static search.
Close #5316
> BUILD: Update ansys theme version

- src/ansys/aedt/core/visualization/report/common.py
- tests/system/general/test_12_1_PostProcessing.py
> FEAT: Display units option in X and Y axis

- .github/workflows/ci_cd.yml
Codecov doesn't like to be passed multiple flags atm...
> CI: Change flags in codecov

- src/ansys/aedt/core/workflows/templates/run_extension_manager.py_build
- src/ansys/aedt/core/workflows/templates/run_pyaedt_toolkit_script.py_build
> FIX: Fix hardcoded path

- doc/source/API/Application.rst
- doc/source/API/FilterSolutions.rst
- doc/source/API/index.rst
- src/ansys/aedt/core/filtersolutions.py
This PR adds FilterSolutions section to the API Reference page.
> FIX: FilterSolutions Sphinx Update

- src/ansys/aedt/core/modeler/cad/primitives.py
- tests/system/general/test_07_Object3D.py
> FIX: Check _object_names_to_ids keys are the same than existing object names

- src/ansys/aedt/core/visualization/post/post_3dlayout.py
corrected the way we identify the nets automatically from the sources.
> FIX: corrected the way we identify the nets automatically from the sources.

- src/ansys/aedt/core/modeler/modeler_pcb.py
- tests/system/general/test_41_3dlayout_modeler.py
> FIX: Duplicate modeler PCB

- .github/workflows/ci_cd.yml
Follow up of dotnet changes. Delcross in so longer required in LD_LIBRARY_PATH.
> CI: Update env variable to not use Delcross

- doc/source/User_guide/extensions.rst
- doc/source/User_guide/pyaedt_extensions_doc/circuit/import_schematic.rst
- doc/source/User_guide/pyaedt_extensions_doc/circuit/index.rst
- doc/source/User_guide/pyaedt_extensions_doc/hfss/choke_designer.rst
- doc/source/User_guide/pyaedt_extensions_doc/hfss/push_excitation.rst
- doc/source/User_guide/pyaedt_extensions_doc/hfss3dlayout/arbitrary_wave_port.rst
- doc/source/User_guide/pyaedt_extensions_doc/hfss3dlayout/cutout.rst
- doc/source/User_guide/pyaedt_extensions_doc/hfss3dlayout/export_3d.rst
- doc/source/User_guide/pyaedt_extensions_doc/hfss3dlayout/export_layout.rst
- doc/source/User_guide/pyaedt_extensions_doc/hfss3dlayout/parametrize_edb.rst
- doc/source/User_guide/pyaedt_extensions_doc/hfss3dlayout/push_excitation.rst
- doc/source/User_guide/pyaedt_extensions_doc/icepak/create_power_map.rst
- doc/source/User_guide/pyaedt_extensions_doc/project/import_nastran.rst
- doc/source/User_guide/pyaedt_extensions_doc/project/kernel_convert.rst
- doc/source/User_guide/pyaedt_extensions_doc/twinbuilder/convert_to_circuit.rst
Follow up of #5549 containing minor changes.
None
> DOCS: Improve extension consistancy

- src/ansys/aedt/core/q3d.py
- tests/system/general/test_30_Q2D.py
- tests/system/solvers/test_31_Q3D.py
> FIX: export eq circuit- model name

- src/ansys/aedt/core/__init__.py
> CHORE: Update v0.13.dev0

- src/ansys/aedt/core/__init__.py
> CHORE: Update v0.14.dev0

- doc/source/Getting_started/Installation.rst
> DOCS: Fix some typos in the installation guide.

- src/ansys/aedt/core/visualization/report/standard.py
- tests/system/general/test_12_PostProcessing.py
> FEAT: Improve freq domain tdr adding maximum_time and step_time parameters - issue #5635

- .github/workflows/ci_cd.yml
This changes should fix the release issue below
None
> CI: Fix permission to release

- src/ansys/aedt/core/hfss.py
- tests/system/general/test_04_SBR.py
- tests/system/general/test_08_Primitives3D.py
- tests/system/general/test_20_HFSS.py
Follow up of #5695 applied to `Hfss`
#5504
> REFACTOR: Add Hfss improvements

- src/ansys/aedt/core/application/analysis.py
Missed f-string in export_results method
Close #5681
> FIX: Missed f-string in export_results

- src/ansys/aedt/core/application/analysis.py
- src/ansys/aedt/core/generic/constants.py
- src/ansys/aedt/core/hfss.py
- src/ansys/aedt/core/modules/setup_templates.py
- src/ansys/aedt/core/modules/solve_setup.py
- tests/system/general/test_20_HFSS.py
- tests/system/general/test_28_Maxwell3D.py
Wave port integration line
Fix template
Close #4887
> FEAT: Wave port integration line 

- src/ansys/aedt/core/desktop.py
- src/ansys/aedt/core/generic/general_methods.py
Avoid checking license on CI CD actions
> FIX: Do not check license on CI CD

- src/ansys/aedt/core/__init__.py
> CHORE: Bump dev version into v0.15.dev0

- src/ansys/aedt/core/desktop.py
- src/ansys/aedt/core/modeler/schematic.py
- src/ansys/aedt/core/visualization/post/compliance.py
- src/ansys/aedt/core/visualization/post/post_circuit.py
Desktop release was causing in some cases zombie processes due to the API still linked to the process.
> FIX: Improve desktop release

- .github/workflows/nightly-docs.yml
Fix documentation dev build
Close #5778
> CHORE: Fix night doc build

- src/ansys/aedt/core/visualization/advanced/rcs_visualization.py
- src/ansys/aedt/core/visualization/post/rcs_exporter.py
- tests/integration/test_monostatic_rcs_data.py
- tests/system/general/test_48_RCS_export.py
- tests/system/general/test_49_RCS_data_plotter.py
- tests/unit/test_monostatic_rcs_exporter.py
Add new functionalities to RCS classes
> FEAT: Improve RCS plotter class

- tests/unit/test_monostatic_rcs_exporter.py
> FIX: RCS export unit test

- src/ansys/aedt/core/modules/solve_setup.py
> FIX: Errors in main unresolved conflicts solve_setup.py

- src/ansys/aedt/core/twinbuilder.py
> CHORE: remove pragma no cover from twinbuilder method

- src/ansys/aedt/core/visualization/post/post_3dlayout.py
> FIX: comput power loss

- src/ansys/aedt/core/workflows/customize_automation_tab.py
> FIX: Remove site --system-site-packages

- doc/source/Resources/pyaedt_settings.yaml
- doc/source/User_guide/settings.rst
- src/ansys/aedt/core/desktop.py
- src/ansys/aedt/core/generic/general_methods.py
- src/ansys/aedt/core/generic/settings.py
> FEAT: Skip license check setting

- src/ansys/aedt/core/twinbuilder.py
Refactor to Pathlib applied to twinbulder.py. Issue #5180
> REFACTOR: Pathlib refactor in twinbuilder.py

- src/ansys/aedt/core/hfss.py
- tests/system/solvers/test_00_analyze.py
> FIX: Get_antenna_data when frequencies are not passed as a list

- src/ansys/aedt/core/aedt_logger.py
- src/ansys/aedt/core/circuit_netlist.py
- src/ansys/aedt/core/common_rpc.py
- tests/system/general/test_47_CircuitNetlist.py
> REFACTOR: Pathlib refactor: aedt_logger.py, common_rpc.py, circuit_netlist.py and test_47_CircuitNetlist.py 

- src/ansys/aedt/core/visualization/post/post_common_3d.py
- src/ansys/aedt/core/visualization/post/post_icepak.py
- tests/system/general/test_98_Icepak.py
Icepak users seldom need the field calculator due to the availability of the field summary. However, it proves efficient for determining the location of an object's maximum temperature.
> FEAT: Method to get max temp location

- .github/workflows/ci_cd.yml
- doc/changelog.d/5895.maintenance.md
As title says, see [ansys actions migration guide](https://actions.docs.ansys.com/version/stable/migrations/index.html#version-v8)
None
> CI: Add mandatory token to github release step

- doc/changelog.d/5917.miscellaneous.md
- src/ansys/aedt/core/__init__.py
- src/ansys/aedt/core/generic/design_types.py
**This PR removes the unused FilterSolutions class from design types.**
**NA**
> REFACTOR: FilterSolutions_class_refacoring

- doc/changelog.d/5942.fixed.md
- src/ansys/aedt/core/hfss.py
- src/ansys/aedt/core/visualization/advanced/rcs_visualization.py
- src/ansys/aedt/core/visualization/plot/matplotlib.py
- tests/system/visualization/test_48_RCS_export.py
> FIX: RCS postprocessing

- doc/changelog.d/5964.fixed.md
- src/ansys/aedt/core/application/analysis_hf.py
- tests/system/general/test_21_Circuit.py
Fix get_all_insertion_loss_list which was causing to return also return loss data in saome cases.
> FIX: Fix get insertion loss

- doc/changelog.d/5979.fixed.md
- src/ansys/aedt/core/visualization/post/post_common_3d.py
> FIX: make get_field_extremum more resilient

- doc/changelog.d/6023.fixed.md
- src/ansys/aedt/core/visualization/post/compliance.py
> FIX: Compliance contour BER check

- src/ansys/aedt/core/emit.py
- src/ansys/aedt/core/emit_core/nodes/EmitNode.py
- src/ansys/aedt/core/emit_core/results/revision.py
- src/ansys/aedt/core/modeler/circuits/primitives_emit.py
- tests/system/solvers/test_26_emit.py
Add a warning message for disconnected components when a revision is run
Also clean up some units code that is no longer needed since we assume unitless values are in SI units
> Add warning for disconnected comps

- doc/changelog.d/6076.added.md
- src/ansys/aedt/core/visualization/plot/pdf.py
- src/ansys/aedt/core/visualization/post/compliance.py
Added a new method called add_image_with_aspect_ration
Improved table format in case of landscape plot
> FEAT: improved pdf  image management

- doc/changelog.d/6077.added.md
- src/ansys/aedt/core/hfss.py
- tests/system/general/test_20_HFSS.py
Add assignment to plane wave boundary
Close #5982
> FEAT: Add assignment argument to plane wave

- doc/changelog.d/6088.fixed.md
- src/ansys/aedt/core/modeler/circuits/primitives_circuit.py
> FIX: Fix locale error that happens after matplotlib plot is created

- doc/changelog.d/6091.fixed.md
- tests/system/general/test_27_Maxwell2D.py
- tests/system/general/test_28_Maxwell3D.py
> FIX: Remove dummy project fixture

- doc/changelog.d/6102.maintenance.md
- src/ansys/aedt/core/__init__.py
> CHORE: Bump dev version into v0.17.dev0

- doc/changelog.d/6110.miscellaneous.md
- doc/source/User_guide/security_consideration.rst
- src/ansys/aedt/core/__init__.py
- src/ansys/aedt/core/application/analysis.py
- src/ansys/aedt/core/desktop.py
- src/ansys/aedt/core/examples/downloads.py
- src/ansys/aedt/core/extensions/customize_automation_tab.py
- src/ansys/aedt/core/extensions/project/create_report.py
- src/ansys/aedt/core/generic/file_utils.py
- src/ansys/aedt/core/generic/general_methods.py
- src/ansys/aedt/core/icepak.py
- src/ansys/aedt/core/modeler/cad/elements_3d.py
- src/ansys/aedt/core/rpc/rpyc_services.py
- src/ansys/aedt/core/visualization/advanced/touchstone_parser.py
- src/ansys/aedt/core/visualization/post/spisim.py
Extend docstring with warnings when needed and also update the code base. Also, notes 
Associated to #5524
> REFACTOR: Updates related to vulnerabilities and documentation

- .github/workflows/ci_cd.yml
- doc/changelog.d/6116.maintenance.md
- doc/source/Getting_started/Installation.rst
- pyproject.toml
Extend CI to perform smoke tests with python 3.13. Includes also documentation changes and classifier.
Related to #5524
> CI: Extend smoke tests with py313

- doc/changelog.d/6139.fixed.md
- src/ansys/aedt/core/q3d.py
- tests/system/solvers/test_31_Q3D.py
> FIX: Fix equivalent circuit export

- doc/changelog.d/6147.fixed.md
- doc/source/User_guide/extensions.rst
Fix documentation bug for the field distribution extension
Close #6146
> FIX: fields documentation extension

- .github/workflows/ci_cd.yml
- doc/changelog.d/6155.maintenance.md
Follow up of #6148 which introduced this wrong change.
None
> CI: Fix missing call to actions/doc-build

- .github/CODEOWNERS
- .github/dependabot.yml
- doc/changelog.d/6169.maintenance.md
Follow up of this dependabot's message https://github.com/ansys/pyaedt/pull/6166#issuecomment-2888064979
The PR removes the field to be removed in dependabot's config file and extend CODEOWNERS application.
Related to #5524
> CI: Update dependabot cfg and codeowners

- doc/changelog.d/6195.maintenance.md
- src/ansys/aedt/core/__init__.py
> CHORE: Update 0.18.dev0

- doc/changelog.d/6206.fixed.md
- src/ansys/aedt/core/modeler/circuits/object_3d_circuit.py
- src/ansys/aedt/core/modeler/circuits/primitives_circuit.py
> FIX: Improve circuit speed

- doc/changelog.d/6204.fixed.md
- src/ansys/aedt/core/visualization/advanced/touchstone_parser.py
> FIX: fix a bug in the reduce method

- doc/changelog.d/6220.miscellaneous.md
- src/ansys/aedt/core/modeler/cad/primitives.py
Improve primitievs `connect` method by removing unnecessary calls.
Close #6207
> REFACTOR: Improve primitives connect

- doc/changelog.d/6223.fixed.md
- src/ansys/aedt/core/maxwell.py
> FIX: edit_external_circuit move lists

- README.md
- doc/changelog.d/6305.documentation.md
> DOCS: Add space between badges.

- doc/changelog.d/6312.maintenance.md
- tests/system/solvers/test_26_emit.py
There are a few EMIT tests that breaks randomly the CICD. We will skip them and investigate the reason.
> CHORE: Skip not stable EMIT tests

- doc/changelog.d/6351.fixed.md
- src/ansys/aedt/core/modeler/schematic.py
> FIX: fixed the way to retrieve non_graphical variable

- doc/changelog.d/6353.fixed.md
- src/ansys/aedt/core/visualization/post/post_common_3d.py
Exposed file format in plot_animated_field function
#6350
> FIX: Exposed file format in plot_animated_field function

- doc/changelog.d/6349.miscellaneous.md
- src/ansys/aedt/core/generic/scheduler.py
- src/ansys/aedt/core/generic/settings.py
- src/ansys/aedt/core/misc/Job_Settings_Template.txt
@Devin-Crawford @Samuelopez-ansys this is a proposal for refactoring the changes already proposed in #6331.
None
> REFACTOR: Submit job class

- doc/changelog.d/6378.fixed.md
- src/ansys/aedt/core/visualization/report/common.py
Follow up of #6354 were a typo was introduced.
None
> FIX: Symbolstyle return value

- doc/changelog.d/6384.documentation.md
- doc/source/Getting_started/Contributing.rst
Follow up of #6303, the code snippet were not rendering correctly.
Related to #6138
> DOCS: Fix extension contribution code snippets

- doc/changelog.d/6418.fixed.md
- doc/source/Resources/pyaedt_installer_from_aedt.py
As title says. There was a typo in a previous refactoring.
None
> FIX: Subprocess call doesn't accept check

- doc/changelog.d/6388.miscellaneous.md
- src/ansys/aedt/core/extensions/hfss3dlayout/cutout.py
- src/ansys/aedt/core/extensions/icepak/power_map_from_csv.py
- src/ansys/aedt/core/extensions/icepak/toolkits_catalog.toml
- src/ansys/aedt/core/extensions/misc.py
- tests/system/extensions/test_45_extensions.py
- tests/system/extensions/test_power_map_from_csv.py
- tests/unit/extensions/test_power_map_from_csv.py
On top of the refactoring, some logic has been added to check the content of the provided file and warn the user if the data is incomplete.
Close #6377
Close #6405
> REFACTOR: Power map from csv extension

- doc/changelog.d/6458.fixed.md
- src/ansys/aedt/core/edb.py
- tests/system/extensions/test_cutout.py
> FIX:  edb import

- doc/changelog.d/6456.test.md
- tests/system/extensions/test_via_design.py
As title says, see https://github.com/ansys/pyedb/issues/1399 for more information.
https://github.com/ansys/pyedb/issues/1399
> TEST: Temporary skip test in linux 2025R2

- doc/changelog.d/6486.fixed.md
- src/ansys/aedt/core/visualization/post/post_common_3d.py
> FIX: Export model obj usage of relative path

- doc/changelog.d/6489.documentation.md
- src/ansys/aedt/core/modeler/circuits/primitives_maxwell_circuit.py
Adding examples and improving docstring of Maxwell circuit: primitives_maxwell_circuit.py
Issue #6136
> DOCS: improving primitives maxwell circuit documentation

- doc/changelog.d/6515.miscellaneous.md
- src/ansys/aedt/core/extensions/hfss/push_excitation_from_file.py
- tests/system/extensions/test_45_extensions.py
- tests/system/extensions/test_push_excitation_from_file.py
- tests/unit/extensions/test_push_excitation_from_file.py
Migrate push excitation from file HFSS
#6511
> REFACTOR: 6511 migrate push excitation from file

- doc/changelog.d/6567.miscellaneous.md
- doc/source/User_guide/pyaedt_extensions_doc/project/configure_layout.rst
- src/ansys/aedt/core/extensions/project/resources/configure_layout/master_ui.py
- tests/unit/extensions/test_configure_layout.py
Rename the created project with a unique name
> REFACTOR: Configure layout

- doc/changelog.d/6583.dependencies.md
- pyproject.toml
This is a follow up of https://github.com/ansys/pyaedt/pull/6579 so that the added tags are correctly converted into HTML and recognized. These tags will be used to identify and categorize pyaedt on the developer portal.
@Samuelopez-ansys Let me know once this is part of a new release so that I can double check a few things .
None
> BUILD(pip): Update ansys-sphinx-theme range from <1.6 to <1.7

- doc/changelog.d/6579.documentation.md
- doc/source/conf.py
- src/ansys/aedt/core/generic/configurations.py
- src/ansys/aedt/core/modeler/circuits/primitives_circuit.py
- tests/system/extensions/example_models/T45/circuit_config.json
> FIX: circuit config fixes

- doc/changelog.d/6608.maintenance.md
- src/ansys/aedt/core/__init__.py
> CHORE: Update v0.20.dev0

- doc/changelog.d/6605.fixed.md
- src/ansys/aedt/core/modeler/cad/primitives_3d.py
- tests/system/general/test_08_Primitives3D.py
Now when creating several layers, ports are aligned to the same plane
#6604
> FIX: Aligned ports to the same plane

- doc/changelog.d/6660.fixed.md
- src/ansys/aedt/core/q3d.py
- tests/system/general/test_30_Q2D.py
- tests/system/solvers/test_31_Q3D.py
> FIX: fixes and improvements in edit_sources() for q3d

- doc/changelog.d/6653.fixed.md
- src/ansys/aedt/core/visualization/post/common.py
- src/ansys/aedt/core/visualization/report/common.py
- src/ansys/aedt/core/visualization/report/eye.py
- tests/system/general/test_21_Circuit.py
> FIX: fixed bug in variations which prevented eye diagram plot

- .github/workflows/ci_cd.yml
- doc/changelog.d/6672.maintenance.md
As title says, followup of https://github.com/ansys/pyaedt/actions/runs/17879852341/job/50872377845
To be removed once the ecosystem is stabilizied 
None
> CI: Temporary fix doc-build

- doc/changelog.d/6702.maintenance.md
- doc/source/Resources/pyaedt_installer_from_aedt.py
Open a windows when something goes wrong with the installer script and  show the stderr.
Associate to #6701
> CHORE: Improve pyaedt installer script
