ansys/pyaedt

doc/source/Resources/Contributing.rst

Simple fix in contributing to have the right location for `index.html` with locally compiled docs.

Update Contributing.rst to have the correct directory for our built docs

---

MANIFEST.in
_setup_common.py
doc/source/Resources/Installation.rst
setup-distutils.py

Add a new distutils-compatible setup script to facilitate installation of PyAEDT with the AEDT-provided IronPython installation.  Move common setup data into a shared file so it has a single source location.  In local testing I confirmed that CPython 3.8 and IronPython from AEDT can run the install command of the setup.py and setup-distutils.py scripts, respectively.

distutils-compatible setup script

---

.github/workflows/ci-build.yml

This PR slighly modifies the doc build CI by only triggering the deployment step on nightly cron jobs.

fix doc ci deployment

---

_unittest/test_PostProcessing.py
pyaedt/modules/AdvancedPostProcessing.py
pyaedt/modules/PostProcessor.py

Added a Scratch to PostProcessor to allow for automatic generation of the path and filename
Refactored the inout arguments of export_model_picture()

Refactored PostProcessor.export_model_picture() to return file-path 

---

.github/workflows/nightly-docs.yml

Nightly docs aren't getting built, so I've rewritten the docbuild job to be split into a nightly cronjob and a PR light doc build.

split PR doc build and full doc build

---

doc/source/_templates/autosummary/base.rst

The method links in the left sidebar are often so long that the method name itself isn't visible without scrolling; this is undesired behavior.  This PR shortens the displayed links to just the method by overriding the `autosummary/base.rst` template.

Shorten method names in the API Reference

---

_unittest/test_01_Design.py
_unittest/test_08_Primitives3D.py
_unittest/test_09_Primitives2D.py
examples/01-advanced-postprocessing/Hfss_Icepak_Coupling.py
pyaedt/application/Analysis2D.py
pyaedt/application/Analysis3D.py
pyaedt/application/AnalysisIcepak.py
pyaedt/application/Design.py
pyaedt/modeler/Modeler.py
pyaedt/modeler/Primitives.py

- Fixed `get_group_bounding_box`.
- Reintroduced `assignmaterial` in Analysis3D (still useful -and faster- in case of material assignment to a list of objects). 
- Renamed `assignmaterial` in `assign_material`.
- Refactored `add_workbench_link` --> `set_object_deformation`.
- Fixed bug in `delete_design` not working with 3DLayout. 
- Fixed bug in `copy_design_from` not working with 3DLayout.
- Fixed bug in `copy_design_from` not correctly setting back the active design.

Reintroduced assign_material in Analysis3D, plus several bug fixes!

---

pyaedt/modeler/Modeler.py

Fix #320
Fix `explicitly `typo.

Fix explicitly typo.

---

pyaedt/hfss.py

Fix issue #349 .
The string returned when editing the source was repeating the power unit.

Do not repeat the name of power unit.

---

pyaedt/hfss.py

Fixed ``axisdir`` default value for ``create_circuit_port_between_objects`` method.
Corrected all docstrings for ``axisdir``.

Fixed axisdir default value for create_circuit_port_between_objects method.

---

.flake8
_unittest/test_01_Design.py
_unittest/test_02_2D_modeler.py
_unittest/test_02_3D_modeler.py
_unittest/test_05_Mesh.py
_unittest/test_06_MessageManager.py
_unittest/test_07_Object3D.py
_unittest/test_09_Primitives2D.py
_unittest/test_09_VariableManager.py
_unittest/test_3dlayout_modeler.py
_unittest/test_Circuit.py
_unittest/test_GeometryOperators.py
_unittest/test_Icepak.py
_unittest/test_Materials.py
_unittest/test_Maxwell2D.py
_unittest/test_PostProcessing.py
_unittest/test_SBR.py
_unittest/test_downloads.py
_unittest/test_emit.py
_unittest_ironpython/run_unittests.py
_unittest_ironpython/run_unittests_batchmode.cmd
_unittest_ironpython/test_00EDB.py
examples/00-basic-examples/Create_Netlist.py
examples/00-basic-examples/Polyline_Primitives.py
examples/00-basic-examples/SBR_Doppler_Example.py
examples/01-advanced-postprocessing/Advanced_Far_Field.py
examples/01-advanced-postprocessing/Touchstone_Management.py

Final refactor to unit test files to conform to unused module import policy. In the case when modules absolutely need to be imported but unused, the comment ` # noqa: F401 ` can be added at the end of that line to make it exempt from the policy. This is used in several places due to the need to import pytest in some cases for Iron Python.
The flake8 configuration is also updated to have this policy checked in the CI.
The style check CI for this PR will not pass until #448 is merged.

Apply flake8 policy for unused imports

---

_unittest/conftest.py
_unittest/test_20_HFSS.py
_unittest/test_24_3dlayout_modeler.py
examples/00-basic-examples/HFSS3DLayout_Via.py
examples/01-advanced-postprocessing/Hfss_Icepak_Coupling.py
pyaedt/generic/general_methods.py
pyaedt/hfss.py
pyaedt/hfss3dlayout.py
pyaedt/modeler/Modeler.py
pyaedt/modules/SetupTemplates.py
pyaedt/modules/SolveSetup.py

- refactored hfss.create_single_point_sweep()
- created hfss.create_linear_step_sweep()
- made hfss.create_frequency_sweep() deprecated
- fixed hfss.create_linear_count_sweep()
- Fixed modeler.get_excitations_name()
- Fixed hfss sweep template
- Fixed sweep.add_subrange()
- created hfss3dlayout.create_single_point_sweep()
- created hfss3dlayout.create_linear_step_sweep()
- made hfss3dlayout.create_frequency_sweep() deprecated
- created hfss3dlayout.create_linear_count_sweep()
- If sweep name exists, does not exit and create a unique name.
- added SweepHFSS3DLayout.change_type
- added SweepHFSS3DLayout.set_save_fields
- Fixed added and improved unit tests
- Fixed example
- introduced PYAEDT_ERROR_HANDLER env variable

Refactored Hfss  and HfssedLayout sweep creation

---

doc/source/Resources/Code_Guidelines.rst
doc/source/Resources/Contributing.rst

- Spelling mistake in "Contributing" section
- "Code Guidelines" section references a Fahrenheit to Kelvin function as Fahrenheit to Celsius

Fixed minor grammar mistakes

---

pyaedt/application/Design.py

The comments of the 3 logging methods suggest that the messages can only be logged at the design level, whereas it can also be done at either the 'global' or 'project' level.
'Design' is the default level and not the only valid level.

Improve the comment to be accurate regarding the code behavior.

---

pyaedt/application/MessageManager.py

Currently, for the `clear_messages` method in the `MessageManager`, if the arguments `proj_name` and `des_name` are empty string, we will delete the current project and current design messages which is the opposite behavior of the description exposed in the docstring.
We must check that these two arguments are None to assign them the current project and design, not if the string is empty.

Fix the behavior for none and empty string.

---

examples/00-basic-examples/03_5G_antenna_example.py

Fix issue #535.
When the doc is generated, a warning appears for the example 03_5G_antenna_example.
It is because the example does not have a title in its docstring.

Add a title '5G linear array antenna'.

---

pyaedt/modeler/Primitives3DLayout.py

Fix the issue #552 .
The `hole_diam` variable must be passed to the `arg_with_dim()` and not a string "hole_diam".

hole_diam cannot be a string to be passed to arg_with_dim.

---

pyaedt/edb_core/siwave.py

Duplicate GND pin groups were created when there were two positive pin groups on the same device.
It was because the positive pins were assigned to the negative node.
Fix #428 .

Fix #428 .

---

pyaedt/modeler/Object3d.py

The inner class `PDSHole` in the outer class `PDSLayer `is not necessary anymore. We can use the `PDSHole `class in `Padstack `directly.
Fix #574.

Remove the PDSHole class duplicate and use the outter one.

---

pyaedt/desktop.py

Encoding must be set to utf-8 because the full documentation will fail on the build agent otherwise.
Fix issue #623 .

Set the encoding to 'utf-8'.

---

pyaedt/application/Analysis.py

If Icepak Design then Auto Setup must be Disabled.

Add Icepak exception in HPC settings

---

pyaedt/modeler/PrimitivesNexxim.py

Fix issue #643.
`ypos` is not an argument of the method `create_resistor` anymore.

Remove unused argument description.

---

pyaedt/modeler/Primitives3D.py

Fix issue #662 .
Rename argument 'major_raidus' as 'major_radius' in the method create_ellipse() in the Primitives3D module.

Rename argument 'major_raidus' as 'major_radius'.

---

pyaedt/hfss3dlayout.py

Fix issue #77 .
It is a minor typo modification. It is without impact because it only concerns a default value string in a method's signature that has been deprecated.
All other issues (upper case uniformity across the entire package) have been resolved along the way.
@maxcapodi78 I checked that the `sweeptype` argument default values were upper case in different files.

All sweeptype default parameter value now starts with lower case.

---

pyaedt/edb_core/EDB_Data.py
pyaedt/edb_core/layout.py
pyaedt/edb_core/nets.py
pyaedt/third_party/ironpython/plumbum/cli/i18n.py
pyaedt/third_party/ironpython/plumbum/fs/atomic.py
pyaedt/third_party/ironpython/rpyc/lib/compat.py

Now Primitives and Nets from EDB are casted into a new data object. They both inherit the original EDB object so the functionalities and back compatibility is preserved.

Nets and Primitives Refactoring

---

pyaedt/modeler/Object3d.py

`Modeler3D` object has no attribute `_appp`
So when calling the `plot()` method in `Object3d`, an error was raised.
Attribute `_appp` is renamed as `_app`.
Fix issue #684 .

Correct the Object3d.plot() implementation.

---

pyaedt/modeler/Primitives3D.py

Add assertions inside the `Object3d` methods responsible for primitives creation.
Make sure that the primitives' parameter values are supported. Otherwise it raises an exception with an appropriate message.

Raise exceptions if primitives' parameter values are not supported.

---

_unittest/test_08_Primitives3D.py
pyaedt/modeler/Primitives3D.py

The current implementation was always assuming that the start position coordinates of the bond-wire were [0, 0, 0] when calculating the length of the bond-wire in each of its directions.
Fix #691 .

Improve bond-wire length calculation for each direction.

---

_unittest/test_01_Design.py
pyaedt/application/Design.py

`definition_manager` and `material_manager` private members are not exposed in the `Design` initializer anymore.
Add unit tests for Design's `definition_manager` and `material_manager`.
Fix #688 .

Remove some useless private members from the initializer.

---

_unittest/test_01_Design.py
pyaedt/application/Design.py

Expose `odesktop` through a read-only property from the `Design`.
Use the `odesktop` accessor instead of the private member. `_desktop`.
Fix #694

Expose odesktop property from Design class.

---

pyaedt/modules/LayerStackup.py
pyaedt/modules/Material.py
pyaedt/modules/MaterialLib.py

Fix broken examples to improve their display in the online generated documentation.
Fix #700

Restore broken examples because of a missing space.

---

README.rst
pyaedt/desktop.py

Raise an exception if the version specified is older than 2021.
Fix #703

Check the AEDT version specified by the user when launching the Desktop.

---

pyaedt/modules/SetupTemplates.py

In the `range` dictionary, correct the `RangeEnd` value to be a string and not a float.
Return `True` at the end of the method `add_subrange`.
Fix #707 .

Correct the add_range() method for sweep "LogScale" subrange.

---

pyaedt/modules/SetupTemplates.py

Add an example in the `add_subrange()` method to demonstrate how to add multiple sweep range.
Fix #677 .

Add an example of how to add multiple sweep range.

---

.github/workflows/unit_tests.yml

Copy `opengl32.dll` into `vtkmodules` folder in the `testenv`.

Handle vtk modules for the unit tests.

---

.github/workflows/unit_tests.yml
_unittest/test_12_PostProcessing.py
examples/01-Modeling-Setup/Optimetrics.py
examples/02-HFSS/HFSS_Dipole.py
examples/02-HFSS/HFSS_Spiral.py
examples/02-HFSS/SBR_Doppler_Example.py
examples/02-HFSS/SBR_Example.py
examples/02-Maxwell/Maxwell2D_Eddy.py
examples/02-Maxwell/Maxwell2D_Transient.py
examples/02-Maxwell/Maxwell3DTeam3.py
examples/02-Maxwell/Maxwell3D_TEAM7.py
examples/02-Maxwell/Maxwell_Magnet.py
examples/05-Q3D/Q3D_Example.py
examples/06-Multiphysics/Hfss_Icepak_Coupling.py
examples/06-Multiphysics/Hfss_Mechanical.py
pyaedt/application/Analysis.py
pyaedt/application/Analysis2D.py
pyaedt/application/Analysis3D.py
pyaedt/application/Analysis3DLayout.py
pyaedt/application/Design.py
pyaedt/application/Variables.py
pyaedt/circuit.py
pyaedt/hfss.py
pyaedt/hfss3dlayout.py
pyaedt/icepak.py
pyaedt/modeler/Object3d.py
pyaedt/modules/AdvancedPostProcessing.py
pyaedt/modules/PostProcessor.py

Working directory is "project path"\projectname.pyaedt\designname

Every Export is saved in working directory

---

pyaedt/modeler/Primitives.py

The list of coordinates provided for each point must have 3 values: x, y, z.
Add an example where the coordinates of the points are local variables. This could be a scenario where a user exports coordinates from a script.
Fix #741 .

Improve the description and example for the polyline creation.

---

examples/07-TwinBuilder/02-Wiring_A_Rectifier.py
pyaedt/modeler/PrimitivesSimplorer.py

Add Second TB example showing how to wire a schematic

- Add new Twin Builder wiring example for a rectifier

---

_unittest/test_20_HFSS.py
pyaedt/hfss.py
pyaedt/modeler/Modeler.py

_create_port_terminal had no "renorm" parameter. Consequently the renorm option was ignored if the solution type was Driven Terminal.

Fix, port renorm option is respected also in Driven Terminal

---

_unittest/test_27_Maxwell2D.py
pyaedt/application/Design.py
pyaedt/maxwell.py
pyaedt/modeler/Object3d.py

Model depth for Maxwell 2D transient analysis is now a property with getter/setter.
Fix #753 .

Model depth for Maxwell 2D transient analysis is now a property with getter/setter.

---

_unittest/test_00_EDB.py

Improve the test and its assertions for the component creation.
Make sure that the tuple returned by `create_component_from_pins` is correct.
Fix #783

Improve the test of create_component_from_pins()

---

pyaedt/application/Analysis3D.py
pyaedt/application/Design.py
pyaedt/desktop.py
pyaedt/modeler/Object3d.py

A new method to evaluate the object bounding box has been implemented. 
It exports the object as .sat file and reads the bounding box values from the .sat file. 
It is faster by a factor of 9 and safer because it does not change the object properties. 
The new implementation rolls back to the old method for the student version (no export available) and in case of errors.

Added new method for bounding box calculation

---

pyaedt/modeler/parts.py

Bug fixed assigning the specific Target CS. It was not specified and it didn't work as expected, the original CS was used instead of the new one created in the previous line.
Tested for both JSON files (1Tx_1Rx and 1Tx_4Rx)

Assign correct CS to the Antenna Inserted

---

_unittest/test_20_HFSS.py
pyaedt/modules/SetupTemplates.py

From now on, `add_subrange()` has a new `clear` argument.
It is possible to reset/delete all the existing and default sweeps of the setup.
Some new unit tests were added for the `add_subrange()`.
Fix #743 .

Add the clear option when creating a new HFSS sweep subrange.

---

_unittest/test_28_Maxwell3D.py
pyaedt/modeler/Primitives.py

It is now possible to update an existing geometry object that was originally created using UDP.
Add unit tests for the UDP updates.
Fix #847 .

Update an existing user-defined primitive (UDP).

---

README.rst

By adding comments in code snippets, the entire content of those code samples can be copy/paste directly.

Add comments in documentation code snippets

---

README.rst

Adds badges to our README.
Since it's in the README, this will also automatically be included within our online documentation at aedtdocs.pyansys.com on the next release.

add badges to readme

---

_unittest/test_28_Maxwell3D.py
pyaedt/modeler/Primitives.py

Change parameter name from 'udptye' to 'udp_type' in create_udp() method.

Change parameter name from 'udptye' to 'udp_type' in create_udp() method.

---

.coveragerc
_unittest/test_28_Maxwell3D.py
_unittest/test_29_Mechanical.py
_unittest/test_31_Q3D.py
_unittest/test_41_3dlayout_modeler.py

Add unit test for the Maxwell setup_ctrlprog with file.
Add test for the linear step sweep in HFSS 3d layout.
Add unit tests for Q3D discrete sweep.
Add unit test for mechanical fixed support.

Add unit tests for setup from different analysis.

---

_unittest/test_08_Primitives3D.py
_unittest_ironpython/run_unittests.py
pyaedt/modeler/Model3D.py

Now users could define specific Objets, CS, boundaries, and excitations from the HFSS Design. By default, it will export all the objects/boundaries available in the Design

3DComponent creation refactoring. 

---

doc/source/API/Primitives.rst
doc/source/API/Setup.rst
pyaedt/application/AnalysisTwinBuilder.py
pyaedt/modeler/Circuit.py
pyaedt/modeler/PrimitivesCircuit.py
pyaedt/modeler/PrimitivesTwinBuilder.py

Clean up related to older class names for Twin Builder
Renaming earlier classes referring to Simplorer

Clean up related to older class names for Twin Builder

---

codecov.yml

Recommend only enforcing patch coverage. There will be times when you remove source and come out with more efficient code by "lose" coverage. We should only worry about patch.
BTW, great job getting above 80%!

Do not enforce global threshold

---

_unittest/test_00_EDB.py
pyaedt/edb_core/EDB_Data.py

Fixed typo in the name of the newly created method create_reactangle_in_pad

Renamed method create_reactangle_in_pad -> create_rectangle_in_pad

---

_unittest/conftest.py
pyaedt/desktop.py
pyaedt/generic/general_methods.py
pyaedt/modeler/Object3d.py

- Fixed _bounding_box_unmodel for 2022R2
- Added non_graphical and aedt_version in settings
- oDesktop.ClearMessages has no effect in non graphical mode

Fixed bounding_box for 2022R2

---

_unittest/conftest.py
_unittest/test_08_Primitives3D.py
pyaedt/modeler/Primitives3D.py

The method named `create_helix` was not tested and did not work.
It is now working properly.
Tests have been added accordingly.
Fix #914

Create helix from a polyline.

---

_unittest/test_00_EDB.py
pyaedt/edb.py

Catch all exceptions raised when exporting ipc.
Previously we were not catching raised exception in the edlib assembly.
Fix #871.

Catch all exceptions raised when exporting ipc.

---

_unittest/test_00_downloads.py
examples/00-EDB/07_WPF_Merge_Utility.py
pyaedt/examples/downloads.py

It will now force download of wpf file to temp folder. It will also give guidance on how to run example

Updated the download method and the WPF example 

---

pyaedt/modeler/PrimitivesCircuit.py

Support touchstone file with more than 9 ports.
Previously we were only selecting the last digit to get the number of ports contained in the touchstone file.
Fix #928

Support touchstone file with more than 9 ports.

---

doc/source/conf.py

This PR adds breadcrumbs to the documentation and changes the link of the PyAnsys logo to return to docs.pyansys.com. This is to remain consistent with the rest of the pyansys documentation (and industry in general) and provide a better experience when navigating through our documentation.
For an example of the rendered breadcrumb trail, see https://mapdldocs.pyansys.com/api/index.html
Note that the top level is always "PyAnsys" and the next level is the current project ("PyAEDT") followed by the sub-pages.

Add breadcrumbs to documentation

---

pyaedt/edb_core/layout.py

`_get_edb_value()` only take one parameter.
`var_server` variable is not required and creating a crash if not removed.
The method named `calc_slope()` in the `edb_core\layout.py` module could not work properly.
Fix #957

Improve the polygon parametrization in the edb layout module.

---

_unittest/test_21_Circuit.py
pyaedt/application/Analysis.py
pyaedt/application/AnalysisTwinBuilder.py
pyaedt/edb.py
pyaedt/generic/TouchstoneParser.py
pyaedt/generic/plot.py
pyaedt/generic/process.py
pyaedt/modeler/Object3d.py
pyaedt/modeler/Primitives.py

- Fix several issues. The most important being the 'Parameter' option that was not exposed properly.
- Improve docstring for method `existing_analysis_setups`.
- Remove the `antipad` property that was duplicated in the class `PDSLayer`.
- Docstring example was incorrect in `ModelPlotter()` class in the `plot` module.

Expose the 'Parameter' option when reading the Touchstone file.

---

pyaedt/edb.py

Improved gds import with possibility to select different xml file location

---

pyaedt/application/Analysis.py
pyaedt/application/Analysis3D.py
pyaedt/application/AnalysisNexxim.py
pyaedt/circuit.py
pyaedt/edb_core/padstack.py
pyaedt/icepak.py
pyaedt/modeler/PrimitivesEmit.py
pyaedt/modeler/PrimitivesMaxwellCircuit.py
pyaedt/modeler/PrimitivesNexxim.py
pyaedt/modeler/PrimitivesTwinBuilder.py

Severe side effects can arose when using mutable objects as default argument.
Indeed the default values of the argument will be evaluated the first time the method is called.
In the subsequent method calls, the same value is used.

Remove the mutable from the defaults argument.

---

pyaedt/application/Analysis3D.py
pyaedt/application/AnalysisNexxim.py
pyaedt/circuit.py
pyaedt/icepak.py
pyaedt/modeler/PrimitivesEmit.py
pyaedt/modeler/PrimitivesMaxwellCircuit.py
pyaedt/modeler/PrimitivesNexxim.py
pyaedt/modeler/PrimitivesTwinBuilder.py

Mention in the methods docstring that the default value of mutable arguments is `None`.

The default value of mutable arguments is None.

---

_unittest/test_15_ibs_reader.py
pyaedt/circuit.py

It is now possible to extract all ibis file model info directly from `Circuit` class.
Fix #966 .

Read IBIS file from circuit class.

---

_unittest/test_00_EDB.py
pyaedt/edb_core/components.py

Making solderball_diam and solderball_height optional. When the two parameter not specified, pad diameter will be used as solderball diam and height.

enhancement set_solderball

---

_unittest/example_models/poc_scat_small.aedt
_unittest/test_12_PostProcessing.py
_unittest/test_17_SBR.py
examples/02-HFSS/SBR_Time_Plot.py
pyaedt/examples/downloads.py
pyaedt/generic/plot.py
pyaedt/modules/AdvancedPostProcessing.py
pyaedt/modules/PostProcessor.py

Added few methods to allow IFFT of SBR+ Frequency domain data

Added few methods to allow IFFT of SBR+ Frequency domain data

---

doc/source/API/CoreModules.rst

In DesignXPloration module, the name of the class is ParametricSetups.
It will fix the documentation generation warning.
Fix #1036

Improve the auto-generated documentation of ParametricSetups in DesignXPloration module.

---

pyaedt/modeler/Model3D.py
pyaedt/modeler/Model3DLayout.py
pyaedt/modeler/Primitives.py
pyaedt/modeler/PrimitivesCircuit.py
pyaedt/modeler/PrimitivesNexxim.py

- Replace posx,posy,posz in all methods less deprecated ones

posx and posy variable name replacement to standardization xpos and ypos

---

_unittest/test_28_Maxwell3D.py
pyaedt/application/design_solutions.py
pyaedt/modules/DesignXPloration.py

- Fixing bug in Maxwell 3D, for adding a calculation in optimetrics. Solution types Magnetostatic", "Electrostatic", "EddyCurrent", "DCConduction" should have Domain 'Sweep'

Fixing Maxwell 3D and optimetrics exceptions 

---

.github/workflows/releases.yml

Add a wheelhouse to support offline deployment.
zip artifacts are created and uploaded for each release. User can use them to install pyaedt when they have some limited access to network.
Fix #1110

Add a wheelhouse to support offline deployment.

---

pyaedt/generic/plot.py
pyaedt/modeler/PrimitivesCircuit.py

- Improve the behavior of the `ChangePageCallback `called when adding a button.
- Deprecated method create_iport was not working.

Improve the behavior of the `ChangePageCallback `called when adding a button.

---

_unittest/test_27_Maxwell2D.py
_unittest/test_28_Maxwell3D.py
pyaedt/maxwell.py

In this PR:
- Fix in assign_coil() -> polarity is now case insensitive.
- Fix in assign_winding() -> fix in coil_terminals if its None and voltage, current, res, ind fixes
- new 2D/3D tests implementation

fix assign_winding and assign_coil + update tests

---

_unittest/example_models/dm boundary test.aedt
_unittest/test_42_configuration_files.py
pyaedt/generic/configurations.py
pyaedt/hfss.py
pyaedt/modules/Boundary.py

import_configurations now handles integration lines for Lumped RLC and Ports.

Improved Robustness of import_configurations to handle integration lines for Lumped RLC and Ports.

---

_unittest/test_02_3D_modeler.py
_unittest/test_98_Icepak.py
pyaedt/application/Design.py
pyaedt/modeler/Modeler.py

Fix issue 1162

---

_unittest/test_12_PostProcessing.py
_unittest/test_21_Circuit.py
_unittest/test_41_3dlayout_modeler.py
pyaedt/application/Analysis.py
pyaedt/circuit.py
pyaedt/hfss.py
pyaedt/hfss3dlayout.py

In this PR export_touchstone() has been fixed for hfss, hfss3D and Circuit in order to make solution_name, sweep_name and file_name as default values and fix for variations.

hfss fixes for export_touchstone()

---

_unittest/test_11_Setup.py
_unittest/test_20_HFSS.py
pyaedt/modules/DesignXPloration.py
pyaedt/modules/SolveSetup.py

Added delete methods to parametrics, optimizations and setup classes.

---

.github/ISSUE_TEMPLATE/bug.yml

As opposed to most other PyANSYS projects, PyAEDT also supports IronPython.

Add IronPython to the python version available for the issue template.

---

_unittest/test_20_HFSS.py
pyaedt/hfss.py

This feature was not working because, and Renormalization was always checked which is 'dangerous' for a waveport in DrivenModal:
- If Renorm is false, RenormImp key must be not defined for a Waveport in DrivenModal
- If driven Terminal, renormalize is True by default. It has to be modifed after the creation of the port.

Renormalization uncheck for waveport in Driven Modal

---

_unittest/example_models/test_report_smith.rdat
_unittest/test_00_report_file_parser.py
pyaedt/generic/report_file_parser.py

If Smith Chart is detected, the output dictionary will have the info from the real and imag. part like 2 different traces

Refactoring RDAT parser to read Smith Chart report

---

_unittest/test_07_Object3D.py
_unittest/test_40_3dlayout_edb.py
pyaedt/modeler/Object3d.py
pyaedt/modeler/Primitives3DLayout.py
pyaedt/modeler/object3dlayout.py

Also added a method in Hfss3dLayout to filder objects by layer and by nets.

Added a method to find the face closest to bounding box (in case thee is no face touching the bounding box).

---

_unittest/test_00_grpc.py
pyaedt/application/Analysis3D.py
pyaedt/desktop.py
pyaedt/generic/general_methods.py
requirements.txt
setup.py

Added a method to check if there are active grpc session of aedt and on which port

Gprc checks

---

pyaedt/generic/python_optimizers.py

A bare import of numpy in python_optimizers.py would cause failures in
IronPython or AEDT.  Use the same logic from elsewhere to avoid.
Fixes #1291

Test for IronPython before importing numpy

---

_unittest/test_00_report_file_parser.py
_unittest/test_30_Q2D.py
_unittest/test_31_Q3D.py
pyaedt/generic/constants.py
pyaedt/q3d.py

- Allow unit value A_per_m and A_per_meter
- New Q3D and Q2D method for Edit Sources. Bug in AEDT API found. In Q3D it is not possible to modify the phase.

Edit Sources in Q3D and Q2D

---

_unittest/test_12_PostProcessing.py
pyaedt/modules/PostProcessor.py
pyaedt/modules/report_templates.py
pyaedt/modules/solutions.py

- Fixed Bug in report_templates for Spectrum report
- Add the option to define a dictionary in the context for solution_data. Useful to define the setup values in reports.
- Get units sweep
- Unittest

Add dictionary context in get_solution_data

---

pyaedt/modules/report_templates.py

When Log Scale is selected, the option Minor Tick is not taken into account, and the API returns an error even if it does not have an impact.

When Log report is selected, disabling Minor Tick Option

---

_unittest/test_02_3D_modeler.py
_unittest/test_05_Mesh.py
_unittest/test_11_Setup.py
_unittest/test_27_Maxwell2D.py
_unittest/test_41_3dlayout_modeler.py
examples/00-EDB/03_5G_antenna_example.py
examples/01-Modeling-Setup/Configurations.py
examples/01-Modeling-Setup/HFSS_CoordinateSystem.py
examples/02-HFSS/Flex_CPWG.py
examples/02-HFSS/HFSS_Choke.py
examples/02-HFSS/Machine_learning_applied_to_Patch.py
examples/02-HFSS/SBR_Example.py
examples/02-Maxwell/Maxwell3DTeam3.py
pyaedt/application/Analysis3DLayout.py
pyaedt/application/AnalysisNexxim.py
pyaedt/application/AnalysisTwinBuilder.py
pyaedt/generic/general_methods.py
pyaedt/icepak.py
pyaedt/modeler/Modeler.py
pyaedt/modules/Boundary.py
pyaedt/modules/DesignXPloration.py
pyaedt/modules/Mesh.py
pyaedt/modules/Mesh3DLayout.py
pyaedt/modules/SetupTemplates.py
pyaedt/modules/SolveSetup.py

Now user can get or set a property directly from the objects thanks to __getitem__ and setitem

Props getitem and setitem

---

_unittest/test_20_HFSS.py
pyaedt/hfss.py

Implement HFSS SetSolveInsideThreshold

Implement HFSS SetSolveInsideThreshold

---

pyaedt/edb_core/components.py

Improve log message when assigning a `Spice` model to a component.
Fix #1459 .

Improve log message when assigning a `Spice` model to a component.

---

_unittest/test_28_Maxwell3D.py
pyaedt/modules/Material.py

The method `set_bp_curve_coreloss()` was not allowing the creation of the the point coordinates properly and consequently, the core loss curve was not updated.
Now the curve is created properly.
Fix #1490

Set points coordinates for BP curve coreloss.

---

_unittest/test_28_Maxwell3D.py
pyaedt/modules/Material.py

Litz wires are now available in Maxwell.
It is now possible to specify the stacking type as "litz wire" for a material.
Then it is possible to set the wire type: round, square or rectangular.
Finally the user can defined the wire dimensions (width, thickness...).
Fix #1473

Add Litz wire in Maxwell.

---

requirements.txt
requirements_test.txt

Numpy is not supporting Python 3.7 starting with release 1.22.0
See: https://numpy.org/devdocs/release/1.22.0-notes.html
Fix #1437 .

Numpy stopped supporting Python 3.7 since release 1.22.0.

---

_unittest/test_16_3d_stackup.py
_unittest/test_26_emit.py
pyaedt/modeler/stackup_3d.py

You must provide the `thickness` when instantiating the `PadstackLayer`.
Fix #1505.

Provide thickness to a new pad stack layer while defining the start layer.

---

examples/07-TwinBuilder/03-Dynamic_ROM_Creation_And_Visualization.py

…  and restore it back at the end so that we find correct license for all regular AEDT users.

Add section to set Desktop Config to Twin Builder for the example

---

_unittest/conftest.py
_unittest/test_28_Maxwell3D.py
pyaedt/modeler/Primitives.py

Udp_dll_name extension should not end with *.py.dll

---

.github/workflows/unit_tests.yml

The license check actions must be updated. It is currently executing some shell commands.
We could have some cmd script performing it.

Remove licenses check.

---

_unittest/test_28_Maxwell3D.py
pyaedt/maxwell.py

For a current, the solid property was disabled for magnetostatic and transientaphi solutions.

---

_unittest/test_12_PostProcessing.py
pyaedt/modules/solutions.py

New feature for phased array post-processing. Add a phase offset on each element. Needed when one element has more than 1 port, the phase between both ports could not be the same, for example, to achieve circular polarization is needed 90 degrees offset.

Array phase offset

---

_unittest/test_30_Q2D.py
_unittest/test_31_Q3D.py
pyaedt/application/Variables.py
pyaedt/q3d.py

Export equivalent circuit Q3D/Q2D
@maxcapodi78 @MaxJPRey @Samuelopez-ansys 
there's a part of the method ExportCircuit not implemented.
It's the include Chip Package Control (include_cpp bool), I couldn't get my head around how to extract this info and apparently is not even accessible so I left it False. Maybe we should state it somewhere.
I'm going to open a defect in tfs for this.

Export equivalent circuit Q3D/Q2D

---

_unittest/test_21_Circuit.py
pyaedt/circuit.py

This is an interesting capability in Circuit which is not exposed in the API. This method saves the most recent Log file into a new path because sometimes if the project is saved, the log files could dissapear.

New method to export Circuit log file

---

pyaedt/modeler/PrimitivesNexxim.py

The import was working but the component was useless because the path format allowed by the API method is just allowing "/" and not "\\"
Close #1723

Fix import spice model in Circuit. 

---

pyaedt/modules/solutions.py

Fix bug when frequency sweep has more than 1 frequency and the user wants to plot the 3D FF.
Close #1750

Farfield 3D plot with more than 1 frequency sweep

---

pyaedt/application/design_solutions.py

Previously if a user was defining the value of the properties `hybrid` or `composite` with a script and then modified those properties interactively, then the value returned by those properties were not updated accordingly. The values set by the script were always returned.
This is due to the fact that those properties were based on `self._solution_options[self.solution_type]` which use a `copy.deepcopy` in the initialization of `DesignSolution` class. 
Fix #1730 .

'hybrid' and 'composite' properties value are always updated.

---

pyaedt/siwave.py

Relative paths that pass `os.path.exists` can still fail to open.
Added a return value so calling code can throw an error if the project fails to open.

Add return code to Siwave.open_project

---

_unittest/test_20_HFSS.py
pyaedt/modeler/Object3d.py

This float conversion was affecting rotation in Circuit. For example, for a Port created if you tried to rotate it, it was failing because it expected an int and not a float

Wrong float conversion

---

pyaedt/edb_core/EDB_Data.py

Note when importing zero values Rlc:
- Aedt will assign default values
- Siwave will keep zero values but deactivate the component.

Defaulting rlc value to zero when pinpairs are not present

---

.github/workflows/ci-build.yml

The two following files were missing for the dev portal documentation: `globalcontext.json` and `searchindex.json`.

Expose the globalcontext and searchindex files for the dev portal.

---

doc/source/API/index.rst
pyaedt/edb_core/edb_data/simulation_configuration.py
pyaedt/edb_core/stackup.py
pyaedt/generic/configurations.py
pyaedt/modeler/object3dlayout.py

Fix warnings in the documentation including one about the cable documentation.

Add CableModeling to the API index of the documentation.

---

_unittest/test_22_Circuit_DynamicLink.py
pyaedt/modeler/PrimitivesCircuit.py

Fix #1899 .
As described in the issue #1899, `name in self.components[el].composed_name` was matching both "PagePort@<net_name>" and "IPort@<net_name>".

Return the correct component when creating an interface port.

---

_unittest/test_00_EDB.py
pyaedt/aedt_logger.py
pyaedt/edb.py
pyaedt/edb_core/components.py
pyaedt/edb_core/edb_data/nets_data.py
pyaedt/edb_core/edb_data/padstacks_data.py
pyaedt/edb_core/edb_data/simulation_configuration.py
pyaedt/edb_core/layout.py
pyaedt/edb_core/nets.py
pyaedt/edb_core/padstack.py
pyaedt/generic/constants.py

Added new method to create cutout based on Edb only methods without using CreateCutout method. 
The method is:
- deleting all nets out of cutout
- create extent
- delete vias out of the extent
- cut polygon to extent
- delete components with less than 2 pins

Edb primitives enhancement - new create_cutout_multithread method

---

pyaedt/edb.py

there was a bug in extent computation that was preventing the usage of extent different from Conformal even if selected by the method arguments.

fixed small bug in create_extent method

---

pyaedt/__init__.py

If the decimal separator is the comma as in some .NET cultures (locales) then EDB operations using Value objects will interpret numbers that include the decimal separator incorrectly.  To resolve this, set the default culture to the .NET invariant culture as early as possible.
To reproduce the issue:
1. Set your system's decimal separator to the comma character
2. With PyAEDT prior to this commit, run _unittest/test_00_EDB.py::TestClass::test_50_set_padstack and note that it fails with a message that 0.0 != 0.3
3. Repeat with this commit and note that the test now passes
Fixes #1980

Set default culture to work around EDB bug

---

.github/workflows/full_documentation.yml

That should fix the current issue with the `FullDocumentation` workflow when generating new releases.

In a workflow, the same identifier cannot be used more than once within the same scope.

---

_unittest/test_00_EDB.py
_unittest/test_01_Advanced_EDB.py
_unittest_ironpython/test_01_Advanced_EDB.py
pyaedt/edb.py
pyaedt/edb_core/edb_data/padstacks_data.py
pyaedt/edb_core/nets.py
pyaedt/edb_core/padstack.py

Added new method find_and_fix_disjoint_nets to check for disjoint nets objects and clean or rename the disjoint parts.
#2045

Disjoint nets find_and_fix_disjoint_nets 

---

_unittest/test_00_EDB.py
pyaedt/edb_core/edb_data/padstacks_data.py

Edb now allows to convert viass from a padstack definition into 3d objects.

convert_to_microvias method added to EDB Padstack class

---

pyaedt/application/Design.py
pyaedt/desktop.py

Copy_design method is not tested in the unittest and there is an equivalent method 'copy_design_from'. I think we should deprecate it.

Deprecate method

---

.github/workflows/full_documentation.yml

The "deploy" action is primarily developed using Ubuntu.
As a workaround, we are using the artifacts generated from a Windows build agent.

Use an Ubuntu agent to deploy the json documentation.

---

_unittest/conftest.py

Creating a local_config.json with some options not present currently causes a failure. This change allows the defaults to be used for all options and only those found in the local_config.json (if present) are overridden. This is not only convenient, but also fixes an issue. Currently, if you copy the example in conf.py to your local_config.json, you will get missing key errors. This fix addresses that and makes the local_config.json more flexible.

Allow partial local_config.json

---

pyaedt/generic/DataHandlers.py
pyaedt/generic/plot.py
pyaedt/modules/SolveSetup.py
pyaedt/rpc/rpyc_services.py

By runing the following command, you can evaluate the time for imports in a python module:
`python -X importtime pyaedt_script.py`
In `rpc_services.py` the `site` import was never used.
Here is the time (in μs) required by this import.

Remove useless imports to improve performance.

---

pyaedt/application/AEDT_File_Management.py
pyaedt/modeler/Model3DLayout.py
pyaedt/modeler/Modeler.py

Since Python 3, all strings are unicode.
The `unicode()` function does not exist anymore.
`basestring` could be seen as a gateway to support both `unicode` and plain `str`.
Because PyAEDT is supporting Python>=3.7, there is no need to support anymore this structure for the `str`.
Fix #2206 .

Remove any usage of unicode and basestring.

---

examples/02-SBR+/SBR_Time_Plot.py
examples/07-Circuit/Touchstone_Management.py
pyaedt/application/Design.py
pyaedt/desktop.py
pyaedt/generic/general_methods.py

Now settings.non_graphical is evaluated directly from AEDT API

Changed way non-Graphical is evaluated when Desktop is initialized

---

.github/workflows/nightly-docs.yml

My feeling is that your workflow was failing because of this. It seems to me that the artifact is not accessible since you are still on the same stage/job. Separation of docs generation and upload into two jobs/stages will potentially solve the issue

Separate doc upload from generation into 2 stages

---

pyaedt/edb_core/nets.py

Actually plot method only works in case primitives have net name associated. Now it will work also for cases where no nets are defined

extend plots in case of primitives without net name gds

---

doc/source/Contributing.rst

With the usage of the multi-version documentation, those links were not working anymore.

Update the links for the 'contributing' section.

---

doc/source/_templates/sidebar-nav-bs.html
doc/source/conf.py

It is possible to turn off the expandable navigation entirely by setting the collapse_navigation config option to `True`:
```py
html_theme_options = {
"collapse_navigation": True
}
```
This tends to help improve documentation build times.
We previously did this in `sidebar-nav-bs.html`, but that option wasn't scalable as it didn't apply to all API pages. This PR removes that file and uses the cleaner option given by [pydata-sphinx-theme - Navigation](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/navigation.html).

Collapse navigation always

---

pyaedt/generic/general_methods.py

Fix a bug where Ansys EM 2022 R1 was assumed to be installed in a folder named like AnsysEM22.1, which did not match the default install location (e.g. v221).
Also, make version checking of running ansysedt processes more robust by attempting to read the version from the config/ProductList.txt file in the installation folder.  If this fails, fall back to the old method.
Fixes #2440

Make version checking more robust

---

_unittest/test_21_Circuit.py
pyaedt/generic/general_methods.py

Two tests in test_21_Circuit.py were failing:
- test_06b_add_3dlayout_component appears to expect a linear network analysis setup to exist by way of referencing self.aedtapp.nominal_adaptive but none exists
- test_07a_push_excitations appears to expect a linear network analysis named LNA to exist but none exists
Fixes #2460

Fix failing tests

---

pyaedt/application/Design.py

This error occurs when `_segment_array()` -> `value_in_object_units()` -> `evaluate_expression()` are called when creating an Angular Arc with a single variable name for one of the points. It does not get evaluated by `pyaedt_evaluator`, and instead of returning the variable value as the `else` branch of the if statement does, returns the `Vairable` instance. 
This results in an error `'my_z_valuemeter' is not a defined variable name in this context`
```
points = [[0,2,"my_z_value"],[0,0,"my_z_value"]]
arcline = app.modeler.create_polyline([points[0]],segment_type=PolylineSegment(type="AngularArc", arc_center=points[1], arc_angle="90deg", arc_plane="XY"))
```

Fixed bad return value when a single variable name used and evaluate_expression is called

---

pyaedt/modules/Boundary.py

Logic previously would only assign `Faces` array to `BoundaryObject`, even if `Objects` array contained items. It is possible to assign both in the UI. This fixes `update_assignment()` to allow both `Objects` and `Faces` to be assigned to the same `BoundaryObject`

allow adding both faces and objects to the same BoundaryObject

---

pyaedt/modules/MaterialLib.py

itervalues() has been removed in python 3.

fix itervalues() not existing in python 3

---

pyaedt/desktop.py
pyaedt/generic/general_methods.py

Starting from 2023.1 Pyaedt uses GRPC as default connection method to AEDT. Anyway user can still use COM and now it's possible to fallback to active COM session in case no GRPC sessions are found and new_aedt_session is set to False.

2023 R1 COM Fallback

---

pyaedt/modeler/modeler3d.py

Fix `create_3dcomponent`.` variables_to_include` argument now works like the other arguments. `None `leads to all variables to be exported and `[]` leads to no variables being exported
Close #2628

Fix variables_to_include argument in create_3dcomponent

---

_unittest/test_01_Design.py
_unittest/test_21_Circuit.py
_unittest/test_28_Maxwell3D.py
_unittest/test_41_3dlayout_modeler.py
_unittest_ironpython/run_unittests.py
_unittest_ironpython/test_26_emit.py
_unittest_ironpython/test_34_TwinBuilder.py
_unittest_ironpython/test_35_MaxwellCircuit.py
pyaedt/application/Analysis.py
pyaedt/application/Design.py
pyaedt/desktop.py
pyaedt/downloads.py
pyaedt/edb.py
pyaedt/generic/clr_module.py
pyaedt/generic/process.py
pyaedt/generic/toolkit.py
pyaedt/icepak.py
pyaedt/misc/Console.py_build
pyaedt/misc/Jupyter.py_build
pyaedt/misc/Run_PyAEDT_Script.py_build
pyaedt/misc/aedtlib_personalib_install.py
pyaedt/misc/console_setup.py
pyaedt/modeler/cad/components_3d.py
pyaedt/rpc/rpyc_services.py
pyaedt/siwave.py

Request #2688 
The [PR](https://github.com/pyansys/pyaedt/pull/2670/files) #2670 introduced `is_windows` and `is_linux` booleans. 
We can replace all `os.name == "posix"`, `os.name != "posix"`, `os.name == "nt"`, `os.name != "nt"` with the booleans

Replace all os.name checks with is_windows, is_linux booleans

---

pyaedt/misc/aedtlib_personalib_install.py

Bug on Linux 23.1 and before where Project level toolkits don't show up. Thus copying to individual design toolkits.

Toolkits don't show up on Linux and 23.1 or before. 

---

_unittest/conftest.py
_unittest/test_02_2D_modeler.py
_unittest/test_12_PostProcessing.py
_unittest/test_17_SBR.py
_unittest/test_22_Circuit_DynamicLink.py
_unittest/test_26_emit.py
_unittest/test_32_RMxprt.py
_unittest/test_34_TwinBuilder.py
pyaedt/misc/Run_PyAEDT_Script.py_build

Request #2688 
The [PR](https://github.com/pyansys/pyaedt/pull/2670/files) #2670 introduced `is_windows` and `is_linux` booleans. 
We can replace all `os.name == "posix"`, `os.name != "posix"`, `os.name == "nt"`, `os.name != "nt"` with the booleans

Replace all remaining os.name checks with is_windows, is_linux booleans Ref: #2689

---

_unittest/conftest.py
pyaedt/generic/filesystem.py

All IronPython unit tests are not running (they are practically jumped over) due to a bug in teardown method.

Fixed teardown for IronPython unit tests

---

pyaedt/misc/Console.py_build
pyaedt/misc/Jupyter.py_build
pyaedt/misc/Run_PyAEDT_Script.py_build

Graceful checks and Error dialogs if Toolkit files are missing.
Useful when a user Installs PyAEDT through one version of AEDT and then runs a different version of AEDT. In this case the virtual env. would not have been created for the second AEDT version.
The error message displayed will be `"<file_path>" does not exist. Please run the "Install PyAEDT" button in the Automation ribbon.`

Graceful checks and Error dialogs if Toolkit files are missing.

---

_unittest/test_98_Icepak.py
pyaedt/modules/MeshIcepak.py

- Close issue #2667 
- Check if the object belongs to 3DComponent
- If object is not 3D, then it is not included

Improve assign_priority method checking if passed objects are native

---

pyaedt/edb_core/padstack.py

Padstack instances were not deleted in delete_nets name because of wrong check

---

pyaedt/edb.py

When point list is passed, both signal and references are cutted on the bounding provided

fix minor issue on cutout method.

---

_unittest/test_00_EDB.py
pyaedt/edb_core/stackup.py

Replace method "import_stackup()" with "load()"
Replace method "export_stackup()" with "export()"

Simplify stackup import and export syntax.

---

pyaedt/emit_core/results/results.py
pyaedt/emit_core/results/revision.py

@jsalant22 Feel free to decline this PR. I just thought that using a property might be easier for the users to find when they are using the auto-completion tools.

Replace methods get/set_notes() by 'notes' property for emit revision.

---

_unittest/test_98_Icepak.py
pyaedt/icepak.py

New function for assigning the source boundary condition. The old one (`create_source_power`) is deprecated. The new function has clearer arguments, and it is more general: it supports both temperature dependent assignment and transient ones.

assign_source function

---

pyaedt/edb.py

Remove calls to sleep and gc.collect from Edb._init_objects and Edb.close_edb to dramatically improve performance for workloads that open and close a large number of EDBs, including portions of the PyAEDT test suite.
Closes #2825

Speed up edb_open and edb_close

---

doc/source/Resources/pyaedt_with_IDE.bat
pyaedt/misc/aedtlib_personalib_install.py
pyaedt_with_IDE.bat

Use argparse for toolkit installer; Fix new Desktop session; sync PyAEDT installer files; use tabs
```
C:\Junk>python C:\AnsysDEV\develop\pyaedt\pyaedt\misc\aedtlib_personalib_install.py --help
usage: aedtlib_personalib_install.py [-h] [--version XY.Z] [--student] [--sys_lib] [--new_session]
Install PyAEDT and setup PyAEDT toolkits in AEDT.
options:
-h, --help            show this help message and exit
--version XY.Z, -v XY.Z
AEDT three-digit version (e.g. 231). Default=231
--student             Install toolkits for AEDT Student Version.
--sys_lib             Install toolkits in SysLib.
--new_session         Start a new session of AEDT after installing PyAEDT.
```
Also confirmed it works when executing the file `pyaedt_with_IDE.bat` from the repo
```
Launching a new AEDT desktop session. …
```

Use argparse for toolkit installer; Fix new Desktop session; sync PyAEDT installer files; use tabs

---

_unittest/test_00_Advanced_EDB.py
_unittest/test_00_EDB.py
_unittest/test_01_Design.py
_unittest/test_08_Primitives3D.py
_unittest/test_09_VariableManager.py
_unittest/test_11_Setup.py
_unittest/test_12_PostProcessing.py
_unittest/test_17_SBR.py
_unittest/test_20_HFSS.py
_unittest/test_21_Circuit.py
_unittest/test_22_Circuit_DynamicLink.py
_unittest/test_35_MaxwellCircuit.py
_unittest/test_36_Q2D_PostProcessing.py
_unittest/test_41_3dlayout_modeler.py
_unittest/test_42_configuration_files.py
pyaedt/modeler/advanced_cad/oms.py

1. Clean up test outputs from Git working tree
2. Ensure all top-level pyaedt objects for tests specify either edbversion or specified_version
Fixes #2848 
Fixes #2851

Test cleanup

---

release/versions.json

Add ``release/version.json`` file, which currently points to an older format, with the correct link only for the switcher. This should allow the current release to function properly. For future releases, we can ensure that the file points to the correct file ``versions.json``  from the start, and we can remove the old ``release/version.json`` file at that time.

FIX: Create versions.json

---

_unittest/test_26_emit.py
pyaedt/emit.py
pyaedt/emit_core/results/results.py
pyaedt/emit_core/results/revision.py
pyaedt/modeler/circuits/PrimitivesEmit.py

- add test case for domain defined only by radio
- specify optional input params
- load the CurrentResult if its still valid when analyze() is called
- make sure old revisions can be retrieved by pyaedt even if they were created prior to the current session

misc fixes

---

examples/07-EMIT/ComputeChannelSeparation.py.back
examples/07-EMIT/ComputeProtectionLevels.py.back
pyaedt/emit_core/__init__.py
pyaedt/emit_core/results/results.py
pyaedt/emit_core/results/revision.py

Also:
- Use Revision constructor for _add_revision in Results
- Fix errors in ComputeChannelSeparation.py and ComputeProtectionLevels.py
- Add some logging output to EMIT API import

Use GetResultDirectory in Revision

---

_unittest/test_26_emit.py
pyaedt/emit_core/results/revision.py
pyaedt/modeler/circuits/PrimitivesEmit.py

B829904: only split the first instance of '=' when getting component node props
B829824: make tx_rx_mode non-optional for get_active_frequencies and raise an error if 'both' is specified.
also added a function to get the band_node when given the radio_node and the band_name

fix some emit bugs

---

_unittest/test_06_MessageManager.py
pyaedt/aedt_logger.py

Fix get_messages failing to get messages from projects stemming from the editing of 3d components. This happens because if a 3d component is open, oDesktop.GetMessages without the project name argument returns messages with "(3D Component)" appended to the project name.

fix issue 3007 (get_messages failing with 3dcomp)

---

pyaedt/emit_core/__init__.py

The override path variable was not getting used because it was being added to the end of the path.

fix EmitApiModule path

---

pyaedt/icepak.py

@PipKat I applied your suggestions from https://github.com/ansys/pyaedt/pull/3018
The only one I did not applied was the one regarding the introduction of a link to the Icepak documentation. I'm currently thinking of introducing one or more function that may help an unfamiliar user to build those dictionaries. In this way we can also shorten those explanations which are repeated on several functions (and will be repeated on others) and can potentially become annoying to maintain.

Improved docstring for block bc assignment functions

---

_unittest/test_00_EDB.py
pyaedt/edb.py
pyaedt/edb_core/edb_data/simulation_configuration.py
pyaedt/edb_core/hfss.py
pyaedt/edb_core/siwave.py

adding more flexibility with SimulationConfiguration class
- add_frequency_sweep[bool] allowing custom frequency sweep assignement
- include_only_selected_nets only available when du_cutou_subdesign = False, to remove only nets which are not selected in signal and power nets 
- generate_excitations allowing custom port definition after build project

Simulation configuration flexibility added

---

doc/source/API/Post.rst

The examples referenced functions that don't exist.
Also made some minor grammatical fixes.

Fix incorrect reporting examples

---

pyaedt/aedt_logger.py

This fix addresses a small mistake in the docstring of the reset_timer method. It looks like there was an extra docstring added that is redundant given the one above it.
Background: I'm doing a research study on function comments that may be incorrect. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!

Remove redundant docstring in reset_timer

---

_unittest/test_00_EDB.py
pyaedt/edb.py
pyaedt/edb_core/components.py

Added new argument to cutout method working only on pyaedt cutout which actually checks all components and find pins on components with associated models (spice, sparam, netlist) and preserve them to avoid errors in siwave simulation.
Option is set by default to False to preserve actual behaviour.
Added an argument to delete_single_pin_rlc to preserve the component and deactivate it
#3165 & #3164

Preserve Spice Pins during cutout in EDB

---

_unittest/test_41_3dlayout_modeler.py
pyaedt/application/Analysis.py
pyaedt/hfss3dlayout.py

Hi guys,
A customer was trying to use the function aedtapp.get_traces_for_plot() but this function only checks single-ended ports available on 3DL. Since he needed to check for differential pairs that were created via the UI, under Excitations > Differential Pairs..., I added two new functions that get the list of diff pairs defined and that uses this list as input to create traces for plot. 
Please consider.
Kind regards,
Felipe

two new functions to deal with diff pairs into 3DL

---

_unittest/test_98_Icepak.py
pyaedt/icepak.py

In this PR I have refactored a method edit_design_settings of Icepak to accept ambient temperature with different units maintaining the reverse compatibility.

Nnetake make flexible unit of ambient temp

---

pyaedt/hfss.py

rename impedance multiplier parameter for clear usage

---

pyaedt/edb_core/edb_data/simulation_configuration.py

I don't think this method is used anymore.
The protected attribute `_parse_signal_layer_properties` seems to be used instead.

Remove unused method _parse_signal_layer_properties().

---

README.md
doc/source/index.rst

Per Landon’s request in the PyAnsys Global AFT on 7/26/23, add links to the PyAEDT cheat sheets from this library's documentation.
Note: This library doesn't reuse the README content in the overall index.rst file for documentation (although I am unsure why it doesn't because the content is basically the same). Regardless, I added a new "Documentation and issues" section in both the README and the overall index.rst file.

Add links for doc and cheat sheets

---

pyaedt_with_IDE.bat

For version 2023 R2 
The installation buttons in AEDT are still `Beta` hence it is necessary to provide the batch file for the customers.
Added just comparison of Ansys versions to choose from either `3_7` or  `3_10`

added comparison of versions to choose the python version

---

pyaedt/modules/MeshIcepak.py

Mixed (2d and 3d) priority assignment is not supported, that's why checking the first element of the list should be enough.

Automatically detect obj type for mesh priority 

---

.github/workflows/nightly-docs.yml

- remove the conditional workflow and fix the typo in naming of nightly dev docs indexing

fix: typo in the ci-cd dev docs indexing

---

_unittest/test_00_EDB.py
pyaedt/edb_core/edb_data/primitives_data.py

Improve usability. Now user can create port from trace object.
```
sig = appedb.modeler.create_trace([[0, 0], ["9mm", 0]], "TOP", "1mm", "SIG", "Flat", "Flat")
sig.create_edge_port("pcb_port", "end", "Wave", None, 8, 8)
```

Create port on path

---

pyaedt/emit_core/results/revision.py

- Throw error for N-1 runs with multiple interferers specified because this wasn't supported in 23R2
- Set max_simultaneous_interferers to 1 to properly disable N-1 when only 1 interferer is specified

Two fixes for N-1 behavior in 2023 R2

---

pyaedt/modules/MeshIcepak.py

This PR was completed a while back to support setting priorities on 2D objects:
https://github.com/ansys/pyaedt/pull/3435/
However it still does not work, likely because *new_obj_list* will be empty if we send in a list of all 2D objects, due to the check further up: 
<pre>
for comp in obj_list:
if comp != "Region" and comp in non_user_defined_component_parts and <b>self._app.modeler[comp].is3d</b>:
new_obj_list.append(comp)
</pre>
This PR removes the is3D check.

Fix issue with setting Object Priorities on 2D objects in Icepak

---

pyaedt/application/Analysis3D.py
pyaedt/application/Analysis3DLayout.py
pyaedt/application/AnalysisMaxwellCircuit.py
pyaedt/application/Design.py
pyaedt/circuit.py
pyaedt/desktop.py
pyaedt/edb.py
pyaedt/emit.py
pyaedt/generic/design_types.py
pyaedt/generic/general_methods.py
pyaedt/hfss.py
pyaedt/hfss3dlayout.py
pyaedt/icepak.py
pyaedt/maxwell.py
pyaedt/maxwellcircuit.py
pyaedt/mechanical.py
pyaedt/q3d.py
pyaedt/rmxprt.py
pyaedt/rpc/rpyc_services.py
pyaedt/siwave.py
pyaedt/twinbuilder.py

Now specified_version and edbversion supports strings, float or int as input.
Example:
- Hfss(specified_version="2023.2")
- Hfss(specified_version=2023.2)
- Hfss(specified_version=23.2)
- Hfss(specified_version=232)

Improved documentation and support for number as AEDT version

---

_unittest/test_00_EDB.py
pyaedt/edb.py
pyaedt/edb_core/edb_data/padstacks_data.py

New Edb cutout supports 2 options for padstack cutout:
- simple pad check based on padstack center (inside or outside extent)
- complete pad check (bounding box inside or outside extent or partially)
Complex pad check is much slower but provides a behaviour more similar to original edb api cutout method
Default is simple pad check to keep back compatibility.

Edb cutout improvements

---

pyaedt/edb_core/nets.py
pyaedt/edb_core/stackup.py
pyaedt/generic/plot.py

Fixed an error in edb.net plot function which was preventing the correct axis scale of the plot. Now the plot is automatically scaled based on the board dimensions.
Also the x and y axis of the plot were scaled differently and this resulted in plots that were out of proportion. This has been fixed too.

Fixed error in edb net plot.

---

_unittest/test_00_EDB.py
pyaedt/edb.py
pyaedt/edb_core/edb_data/connectable.py
pyaedt/edb_core/edb_data/nets_data.py
pyaedt/edb_core/edb_data/padstacks_data.py
pyaedt/edb_core/edb_data/primitives_data.py
pyaedt/edb_core/edb_data/terminals.py
pyaedt/edb_core/general.py
pyaedt/edb_core/layout_validation.py
pyaedt/edb_core/nets.py
pyproject.toml

New class LayoutValidation for layout check. 
```
assert len(edbapp.nets["DDR4_DM3"].find_dc_short()) > 0
edbapp.layout_validation.dc_shorts()
```

layout validation

---

pyaedt/desktop.py
pyaedt/generic/settings.py

#3730 
Implemented waitforlicense flag into settings
```
from pyaedt import settings, Desktop
settings.wait_for_license=True
d = Desktop()
```

added waitforlicense options to settings

---

_unittest/test_12_1_PostProcessing.py
pyaedt/modules/PostProcessor.py

Methods now support the export of uniform points data give a specified start, end and step values.

Implemented uniform points exports into methods export_report_to_csv and export_report_to_file

---

pyproject.toml

Use ansys-pythonnet (ansys fork) rc 2 to provide consistant libraries as a bundle.
Closes ansys/pyansys#384

bugfix: compatibility with pymechanical

---

.github/labeler.yml

Update the Github workflow labeler to track changes related to `edb` (based on specific modified files).
This could me removed later on but would be of great help for the split between AEDT and EDB.

CI: Add edb label to labeler

---

_unittest/test_08_Primitives3D.py
pyaedt/modeler/cad/elements3d.py

fillet and chamfer methods docstring correction

Fillet chamfer docstring update

---

.github/labels.yml

Previous PR (#3761) was missing an item in `.github/labels.yml` which resulted in:
- the deletion of the `edb` label on github (cf #3745) and the removal from each issue / PR
- no label added on PRs touching targeted files
This addition should patch it (tested on a fork cf https://github.com/SMoraisAnsys/pyaedt/pull/2)

CI: Add edb label to labels.yml

---

pyaedt/modeler/circuits/PrimitivesMaxwellCircuit.py

Add component name

---

_unittest/test_00_EDB.py
pyaedt/edb.py
pyaedt/edb_core/dotnet/primitive.py

Now PyAEDT Cutout keeps the path as lines after the cutout instead of converting them to polygon data.

Now PyAEDT Cutout keeps the path as lines after the cutout

---

_unittest/example_models/T13/phased_array.aedt
_unittest/test_13_LoadAEDTFile.py
pyaedt/generic/LoadAEDTFile.py

The AEDT parsing has been updated to get info about the 3d component array definition, which are not available through the API.

Updated LoadAEDT method to support array definition

---

.github/workflows/build_documentation.yml
doc/styles/Vocab/ANSYS/accept.txt

At least since version 2.29.3 of vale, titles are also checked by vale. Thus, multiple warning started appearing due to non deterministic behavior when using multiple (differently-cased) entries for the same terme.
The proposed solution consists in reworking the accept.txt file until no more warnings are generated.

CI: remove potential vale warnings

---

pyaedt/modeler/cad/Modeler.py

The bug appears when `PLANE.YZ` is used as input for the `plane` argument.
Since `PLANE.YZ=0`, all the if statements like `if not plane` were evaluating as `True`. In the method implementation, it was supposed to happen only when `plane` argument was not provided, so when `plane=None`.

Fix "split" method in Modeler.py

---

_unittest/example_models/T98/3d_comp_mesh_prio_test.aedt
_unittest/test_98_Icepak.py
pyaedt/modules/MeshIcepak.py

In the current code, to add mesh priority using def add_priority for the 3d user-defined component, it did not consider 2d objects in the user-defined components. Added capability to consider 3d, 2d, and its combination. 
Fix #3577 .

fix: Issue 3577 mesh priority for 3d comp

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
CONTRIBUTORS.md

Adding a list of the main contributors.
Obviously names can be added and/or removed based on contributors will.
**Thanks you all for your commitment and hard work.**

Add files related to contributions.

---

_unittest/example_models/syslib/Materials.amat
_unittest/test_00_EDB.py
doc/source/Getting_started/Troubleshooting.rst
doc/source/conf.py
pyaedt/edb_core/materials.py
pyaedt/generic/LoadAEDTFile.py
pyproject.toml

This PR is a proposition to refact how EDB reads materials file
Problem
Current implementation leverages load_entire_aedt_file from pyaedt.generic.LoadAEDTFile.
Solution
The proposed solution consists in reworking the way amat are read and loaded. First, we only allow to load amat that are located in AEDT's syslib directory. By default, the file that is read is "Materials.amat".
Since we only work with syslib, the code related to personallib has been removed.
Note
The proposed solutions is inspired from https://github.com/ansys/pyaedt/pull/3711. The resulting code refacts the PR's code to have fewers LOC and fixes many errors that were part of the PR.

Refact edb load amat

---

pyaedt/edb_core/edb_data/primitives_data.py

Setting layer_name on primitive gives key error: "TOP"; this seems like an easy fix. [Closes 3846](https://github.com/ansys/pyaedt/issues/3846)

Edited code to reflect passed function value

---

_unittest/test_03_Materials.py
pyaedt/modules/Material.py

Add is used flag to material

---

pyaedt/generic/touchstone_parser.py

on big touchstone files it was taking too much time to compute insertion losses indexes.

improve the speed of IL computation in Touchstone parser

---

_unittest/test_98_Icepak.py
pyaedt/icepak.py
pyaedt/modules/Boundary.py

Add recirculation boundary function

---

_unittest/test_09_VariableManager.py
pyaedt/application/Variables.py
pyaedt/modules/LayerStackup.py

Deprecate is_used_variable method
Reduce default Roughness nodule radius
Close #3360

Reduce default Roughness nodule radius

---

_unittest/conftest.py
_unittest/test_01_Design.py
_unittest/test_03_Materials.py
_unittest/test_09_VariableManager.py
_unittest_solvers/conftest.py
pyaedt/generic/configurations.py
pyaedt/icepak.py
pyaedt/modules/MaterialLib.py

Regression in `add_material_sweep` method in class `Materials` has been fixed.
Unit tests are improved.

Fixed bug in SweepMaterial creation

---

_unittest/test_44_TouchstoneParser.py
pyaedt/generic/touchstone_parser.py

Fix touchstone deepcopy issue

---

_unittest/test_20_HFSS.py
_unittest/test_98_Icepak.py
pyaedt/desktop.py
pyaedt/generic/configurations.py
pyaedt/hfss.py
pyaedt/icepak.py
pyaedt/modules/Boundary.py

Initializing pythoncom after import. 
I have launched all tests locally with COM, and some tests are failing with COM enabled, we should consider adding an "skipif" or fixing the problems. Most of them are in Icepak unit test. But this Pull request does not affect the current performance of PyAEDT with COM.

Fix pythoncom issue

---

_unittest/test_00_EDB.py
pyaedt/edb.py
pyaedt/edb_core/components.py
pyaedt/edb_core/edb_data/obj_base.py
pyaedt/edb_core/edb_data/padstacks_data.py
pyaedt/edb_core/edb_data/primitives_data.py
pyaedt/edb_core/layout_validation.py
pyaedt/modules/SolveSetup.py

Fix bug in disjoint_nets method due to a regression in the net_name setter

---

pyaedt/modules/PostProcessor.py

At the moment if variations is not provided as input to the method and there are no available variations in the design, report is empty.

Improve variations in create_report

---

_unittest/test_11_Setup.py
pyaedt/modules/SolveSetup.py

`props["MultipleAdaptiveFreqsSetup"]` could potentially be nonexistent.
A known case is the setup automatically created by setting auto-open region.
Related test case added.

Fix `KeyError` in `enable_adaptive_setup_multifrequency`

---

_unittest/test_03_Materials.py
_unittest/test_05_Mesh.py
_unittest/test_28_Maxwell3D.py
_unittest/test_41_3dlayout_modeler.py
_unittest/test_98_Icepak.py

Some unit tests will fail when opening desktop with COM, because some methods are only supported when AEDT runs in GRPC mode. 
This PR add a skip decorator for unit tests that fail when running AEDT with COM.
NOTE that CI unit tests run **always** in GRPC mode, so this modification is only necessary when running tests locally for development purposes.

Added skip for unit tests that fail when running AEDT with COM

---

_unittest/test_12_1_PostProcessing.py
pyaedt/modules/SolveSweeps.py

Return basis frequencies with the default units.

---

doc/source/conf.py
pyaedt/generic/grpc_plugin_dll.py
pyaedt/generic/process.py

Replace all os.name with boolean checks is_windows, is_linux

---

_unittest_solvers/test_26_emit.py

Before, the license session test compared times in different scenarios. This relies on the license checkout/checkin times being consistent, which caused some intermittent failures depending on machine and license setup. The new test counts the number of checkout/checkins instead.

Make license session test more consistent and meaningful

---

pyaedt/generic/ibis_v7.json

It seemed like a typo, confirmed in latest IBIS spec https://ibis.org/ver7.2/

Fix typo in IBIS spec, 'seeries' to 'series'

---

pyaedt/generic/plot.py

enable_parallel_projection() gives a traditional view of the object.
Traditional view
compare to

pyvista parallel projection

---

pyaedt/modules/SetupTemplates.py

-. add key for NexximAMI setup
-. "InputType": 1, @line# 565

modified \pyaedt\pyaedt\modules\SetupTemplates.py

---

doc/source/User_guide/intro.rst
doc/source/User_guide/pyaedt_file_data/project.rst
examples/00-EDB/03_5G_antenna_example_parametrics.py
examples/00-EDB/13_edb_create_component.py
examples/00-EDB/14_edb_create_parametrized_design.py
examples/02-HFSS/Array.py
examples/02-HFSS/Flex_CPWG.py
pyaedt/desktop.py

Fix release example
Add release all True for Documentation

Fix Examples documentation

---

.github/workflows/build_documentation.yml
.github/workflows/full_documentation.yml
.github/workflows/nightly-docs.yml
.github/workflows/wheelhouse.yml
.github/workflows/wheelhouse_linux.yml

The release of v0.7.9 got canceled because the new examples seems to have increased the total execution time to reach 8 hours. This commit adds 4 extra hours to finish the full_documentation job.
Note: we should reconsider the strategy to build our documentation (I know that moving the example to another project was a discussion and it might really be helpfull here).

CI: extend full documentation timeout

---

.github/workflows/build_documentation.yml
.github/workflows/full_documentation.yml
.github/workflows/nightly-docs.yml

Problem: it seems that using the new version (v4) of upload-artifact adds some upper bound on the number of files to be uploaded.
Solution: reverting our actions to use v3 and make changes compatible with other ansys actions, i.e. changing some ansys/action/... to v4
Associated issue : https://github.com/actions/upload-artifact/issues/485

CI: fix full documentation upload step

---

_unittest/test_01_Design.py
pyaedt/application/Design.py
pyaedt/circuit.py
pyaedt/desktop.py
pyaedt/emit.py
pyaedt/hfss.py
pyaedt/hfss3dlayout.py
pyaedt/icepak.py
pyaedt/maxwell.py
pyaedt/maxwellcircuit.py
pyaedt/mechanical.py
pyaedt/q3d.py
pyaedt/rmxprt.py
pyaedt/twinbuilder.py

Increment the desktop instance's "application reference count" in `Design.__enter__` instead of `Design.__init__` to avoid increasing the reference count incorrectly when, for example, `Hfss.set_active_design` is called.
Also remove unnecessarily duplicated `__enter__` definitions in each application subclass, leaving only `Design.__enter__`.
Fixes #4092

Fix desktop reference counting

---

pyaedt/modules/PostProcessor.py

The simplified implementation GetTopEntryValue works fine in small models but it is failing in the big model (mesh ~27M). Therefore I am reverting this implementation to the previous one with temp file exporting and reading it to extract value which we verified that works fine with bigger models. GetTopEntryValue was working fine with versions <=22R2 but something happened in later versions on the native scripting side.

issue-4102-reverting-implementation-in-get_scalar_field_value

---

_unittest/test_00_EDB.py
pyaedt/edb_core/layout.py
pyproject.toml

There is a side effect on scikit-rf 0.30.0 as it uses scipy without bounding the version and that method linspace, used by scikit-rf is no longuer available through scipy import in scipy 1.12.0. (see https://github.com/scikit-rf/scikit-rf/issues/1005)
**Note**: this should be 'reverted' later on to use scikit-rf new version as it should fix the current issue.
**Extra note**: a commit revert is also added to this PR as it was added on main by mistake and is failing (see https://github.com/ansys/pyaedt/commit/37218a5c6d1da2b8149a40abf8e4655c0011d2a3)

MAINT: fix CI by fixing scipy and scikit-rf versions

---

pyproject.toml

This change happens following the fix on scikit-rf side.
Reminder: scikit-rf was trying to import a specific function from scipy while not bounding the version of scipy. The newest version of scipy had no longer the required function leading to CI breaks on our side as we no longer could run the tests.
Btw, I was able to test this change on a container with python 3.7 and it was working fine.
Closes #4137

MAINT: use scikit-rf 0.31.0

---

pyaedt/modules/Material.py

Resetting _color_id  to 0 when _color_id is greater than or **equal to** number of CSS4_COLORS.
Close #4170

issue_4170_bug_resolution

---

pyaedt/desktop.py

sDesktopinstallDirectory was not set in case of remote session, resulting in some failure. 
This is fixed now.

sDesktopinstallDirectory is now set also for remote sessions

---

.github/labeler.yml
.github/labels.yml

Note: this will help us greatly with the maintenance of the new pyaedt-examples projects. At short term it will alleviate the pain of tracking changes in the examples while working on the repo. In the long term, it could be leveraged to trigger specific workflows on the pyaedt-examples repo

CI: track changes in examples

---

pyaedt/application/Variables.py

Declare regex as raw string to avoid escape sequence deprecation.

fix: declare regex as raw string to avoid escape sequence deprecation

---

.github/labeler.yml
.github/labels.yml
.github/workflows/full_documentation.yml
.github/workflows/nightly-docs.yml

Currently, some workflows still try to interact with pieces of EDB documentation that is no longer created while building pyaedt documentation. On top of this cleanup, the automatic labeler leveraged to synchronize changes from pyaedt and pyedb is being removed.

CI: Fix documentation workflow

---

_unittest/test_warnings.py
pyaedt/__init__.py

This PR consists in triggering a deprecation warning when one uses PyAEDT with a python version <= 3.7
It is tested and implemented to be easily extended to any new python version.

MAINT: Depecrate python version 3.7

---

.github/workflows/full_documentation.yml
.github/workflows/ironpython.yml
.github/workflows/unit_tests.yml
.github/workflows/unit_tests_solvers.bkp

Notes: to refact the CI/CD we need to avoid using pyaedt self-hosted runners when not needed. However, the current workflow files leverage "windows-latest" and "pyaedt" which leads to using pyaedt self-hosted runners instead of github runners. Here we remove the use of "windows-latest" when the CI/CD should run on self-hosted runners.
On top of these changes, the self-hosted runners tag are going to be update to remove "windows-latest" from their labels. It does not make sense to keep it and might be confusing with Github runners.

CI: Update workflows runs-on

---

pyaedt/common_rpc.py

enables operation in all deployment types.
required for SAF integration

use 0.0.0.0 as hostname for rpyc servers

---

pyproject.toml

For some reasons, pyedb version 0.4.2 was not published in pypi. Therefore, when one wants to work with Python 3.7, we must specify version 0.4.0 instead.
NB: Caught this error while refactoring the CI/CD. Once used, we'll avoid such error to happen !

MAINT: Fix wrong version of pyedb

---

pyaedt/icepak.py
pyaedt/modeler/cad/Primitives.py
pyaedt/modeler/cad/elements3d.py
pyaedt/modeler/cad/polylines.py
pyaedt/modules/Boundary.py
pyaedt/modules/MaterialLib.py

Prior to merge #4331, let's merge this one. It will make the removal of details exception as suggested by @SMoraisAnsys [here](https://github.com/ansys/pyaedt/pull/4331#issuecomment-1983528231) easier and less error prone.

Remove the exception details -as e- when not needed.

---

README.md
README_CN.md
doc/source/Resources/PyAEDTInstallerFromDesktop.py
pyproject.toml

We have two install targets expressing the same dependencies but it seems that only all is used and leveraged in our CI/CD.
I feel like there is no reason to keep the `full` target anymore.
Note: This is also more compliant with how other pyansys projects are working.

MAINT: Remove install target full

---

.github/workflows/nightly-docs.yml

Note: There was an incompatibility between the actions to download and upload artifacts. The versions being different, the artifact generated was not compatible.

CI: Fix nightly documentation build

---

_unittest_solvers/test_00_analyze.py
pyaedt/modules/PostProcessor.py

Add export option to export_file and export_on_grid

---

pyaedt/generic/touchstone_parser.py

Sometimes, touchstone files has no or wrong dc point. So it can be useful to check also the 2nd point. The method check the DC point and if it retuns a value lower than -90dB it checks the 2nd value.

right now Insertion loss is computed on first frequency point.

---

pyaedt/generic/plot.py

With this change, the pyvista Plotter object will be assigned to the pv property of the pyaedt ModelPlotter class, and it won't be shown. In this way, the user can further manipulate the pyvista plot before exporting it.

Add argument to skip showing pyvista plot

---

_unittest/test_01_3dlayout_edb.py
pyaedt/desktop.py
pyaedt/hfss3dlayout.py
pyaedt/modeler/modelerpcb.py
pyaedt/modeler/pcb/Primitives3DLayout.py
pyaedt/modeler/pcb/object3dlayout.py

add few methods to hfss3dlayout.py:
- dissolve_component
- create_pec_on_component_by_nets
- modeler.create_components_on_pins
Added new property to set_solderball method to add an offset for the port in component solderball.
added method create_components_on_pins

Improve h3d layout methods

---

_unittest/test_01_3dlayout_edb.py
pyaedt/modeler/pcb/Primitives3DLayout.py

Just renaming the method from `create_components_on_pins()` to `create_component_on_pins()` because based on the code, only one component can be created.

FIX: Only one component per pins is created.

---

.github/workflows/build_documentation.yml
doc/Makefile
doc/source/conf.py

Previous fix #4482 didn't cover all the problems. This one should fix the issue to download PDF file and adds a fix to the doc Makefile.

DOC: Fix related to PDF assets

---

.github/workflows/build_documentation.yml
.github/workflows/nightly-docs.yml
doc/source/_static/assets/download/.gitignore

Note: the dev doc is uploaded nightly but the download button PDF asset was not uploaded during the nightly index update.
Follow up of #4486
Should close #4496

DOC: Fix PDF download button

---

.github/workflows/nightly-docs.yml

Recent updates didn't follow expected input of doc-deploy action (wrong file name uploaded).
On top of that, the PDF was inserted after the upload step was performed :/

CI: Fix nightly docs

---

doc/source/User_guide/index.rst
doc/source/User_guide/intro.rst

In the "User guide" section of the doc, the left nav bar had different headings than for some of the cards on the landing page for this section. This PR makes them consistent.

Match headings in left nav pane and card titles

---

pyaedt/application/design_solutions.py
pyaedt/circuit.py

REFACT: Clean design solution and circuit

---

doc/source/index.rst

@SMoraisAnsys I've updated the doc landing page, removing the "EDB API reference" card but adding a note before all the cards telling readers that they might also want to view the PyEDB documentation. I've moved the future cheat sheet updates to a different (new) issue: [Issue #4574](https://github.com/ansys/pyaedt/issues/4574).

Update the doc landing page per Issue #4524

---

_unittest_solvers/test_26_emit.py
pyaedt/emit.py

If the project and design names are not specified, the active project and active design are supposed to be used. However, a new project is always being created when the Emit() object is created.

Fix active design selection behavior for Emit designs

---

_unittest_solvers/test_00_analyze.py

Seems like #4589 did not handle this tests and that it might be worth it to reopen #4590.
The skipped tests are currently blocking #4284 from passing CICD as tests would be performed on Linux.

TESTS: Temporary disabling SPISIM test with linux

---

doc/source/conf.py
doc/source/index.rst
pyproject.toml

On top of fixing the blank area, this PR also drops the dependency to sphinx-jinja which is no longer required / leveraged.

DOC: Fix blank area

---

examples/03-Maxwell/Maxwell2D_Transformer_LL.py

Otherwise the example is great! Thanks @IreneWoyna.

DOC: Fix typo in Maxwell transformer example.

---

pyaedt/__init__.py
pyaedt/generic/clr_module.py
pyaedt/generic/filesystem.py
pyaedt/generic/general_methods.py

As title says.
Changes:
- use 'secrets' module instead of random values created through 'random' module
- remove unused code, e.g. `xml.etree.cElementTree`

REFACTOR: Generic modules to avoid bad practices

---

.github/workflows/nightly-docs.yml

Currently the dev documentation is uploaded without any example.
Since we have fixed multiple things to be able to build the documentation with examples in HTML and PDF format, we should include them in the nightly documentation.

CI: Add examples to nightly doc build

---

doc/source/conf.py

When the CICD refactoring was performed, doing the PDF file took too long and was not performed.
However this got fixed and we are even able to have this PDF file as an artifact.
Thus, we should also provide a download button for stable releases

DOCS: Add download PDF button for release

---

pyproject.toml

As of now, you cannot use together the main branches of PyAEDT and PyEDB. This will allow you to do so

CHORE: allow latest PyEDB version

---

pyaedt/desktop.py

For the case when the `design_name` argument is provided to `design_type()`, the wrong arguments were being provided to `self.active_design()`. It expects a project object as the first object and design_name string as the second argument.

FIX: design_type in desktop.py

---

_unittest/test_41_3dlayout_modeler.py
pyaedt/application/Design.py
pyaedt/modules/Boundary.py

With this implementation, you can get the boundaries in a HFSS 3DLayout design, and then with the object_properties, you can manipulate these boundaries.
For instance:
aedtapp.boundaries[0].object_properties.props["Boundary Type"] = "PEC"
It was not possible before.
Close #3251

FEAT: Add layout boundaries

---

README.md

Minor changes to README.md
Added a note about the sematic PR convention.

DOCS: Update readme

---

_unittest/test_utils.py
pyaedt/generic/general_methods.py

Following https://github.com/ansys/pyaedt/pull/4463, it seems that the `pyaedt_function_handler` function was not working correctly. Indeed, if an exception was raised and the settings were such that one would want the function handler to return False, no value was returned by the function (leading to a None return).
Some tests have been added to ensure that the behavior of the function does not changes without notice. They cover the following behaviors of the function handler:
- enable error handler;
- release on exception;
- argument deprecation mechanism.
Closes #4707

FIX: Function handler to return False

---

pyaedt/modeler/cad/components_3d.py
pyaedt/modeler/cad/object3d.py

Mirroring #4714 from https://github.com/marcobiasizzo (who cannot access secrets)
"""
In the mirror function of components_3d and object3d one of the argument is called position. To be coherent with other functions (also with mirror in primitives), the variable name is updated to origin.
"""
@marcobiasizzo Thanks again for your contribution !

REFACTOR: Update mirror argument from "position" to "origin"

---

pyaedt/application/Analysis3D.py
pyaedt/modeler/cad/Primitives3D.py
pyaedt/modeler/cad/components_3d.py
pyaedt/modeler/modeler3d.py

Hardcoding a default password is considered bad practice because it degrades security (easy to target for attackers and reverse engineering), flexibility (harder to rotate password), ....
As an alternative approach, we could use config files secrets or environment variables. This PR follows the environment variables that was used in #4672 to handle codacy warning.

REFACTOR: Encryption password handling

---

pyproject.toml

This pull-request fixes the metadata included in the `pyproject.toml` file. In addition, new classifiers have been added. Related with #4775.

FIX: metadata in pyproject.toml

---

pyaedt/generic/general_methods.py

Close #4753 
@MelanieMichon We have implemented this method to check if the license server is down or if the license increment is available. The user should first check it, because for now is dangerous to add it inside the Desktop initialization.

FEAT: Check License feature

---

pyproject.toml

Seems like changes in #4784 introduced a typo in the package classifier which lead to [release failure](https://github.com/ansys/pyaedt/actions/runs/9518607641/job/26260047110) when uploading to PyPI.
Here is a fix following [PyPI's classifiers](https://pypi.org/classifiers/).

FIX: Project classifier to be PyPI compatible

---

pyaedt/circuit.py

As title says.
Found this problem while working on the pyaedt-examples repo.

FIX: Circuit argument deprecation miss

---

pyaedt/hfss.py

As title says.
Like #4827, this PR should fix missing argument deprecation from #4777
Note: found this problem while working on the pyaedt-examples repo.

FIX: HFSS argument deprecation miss

---

pyaedt/modules/report_templates.py
pyaedt/modules/solutions.py
pyaedt/rmxprt.py

As title says.
Note: contrary to previous refactoring, I used the following approach to be more compliant with what was expected to happen:
- logging at debug level in try: .. except: pass;
- raising `AssertionError` when calling assert in the code.
The first ensures that we can log information and don't confuse users.
The second ensures that the tolerant approach used through the function handler is kept and used.

REFACTOR: Cleanup rmxprt and pyaedt.modules files

---

_unittest/test_21_Circuit.py
pyaedt/modeler/circuits/object3dcircuit.py

This is correctly working in 2024.1

REFACTOR: Angle property getter in aedt 2023.2 and below is broken in GRPC and has to be bypassed.

---

pyaedt/common_rpc.py

This is an attempt to fix #4844.
@maxcapodi78 The main change is that we both handle `None` and `0` as the same kind of result. Indeed, `0` seems to be the default value obtained if `_desktop_sessions` is empty. Note that I'm not sure if, in the case of existing desktop sessions, we shouldn't use directly `client.root.check_port()` to define `cl.aedt_port` directly.
Also, I was wondering how we could try to leverage `_desktop_sessions` from `pyaedt.generic.desktop_sessions` but I have the feeling that this shouldn't be updated unless a `Desktop` is created (which isn't performed right through the call `create_session` right ?)

FIX: AEDT port value in create_session

---

_unittest/test_27_Maxwell2D.py
_unittest_solvers/test_00_analyze.py
pyaedt/modules/PostProcessor.py

replaced argument output_dir with output_file for method export_field_file as it requires to specify a file path, not a dir.

FIX: replaced argument output_dir with output_file for method export_field_file

---

_unittest/test_98_Icepak.py
pyaedt/application/Design.py
pyaedt/icepak.py

- Added `clear_linked_data` method to Icepak.
- Changed the return type of `odesign`, to avoid warning in the IDE.

FEAT: `clear_linked_data` method to Icepak

---

_unittest/test_03_Materials.py
pyaedt/modules/Material.py

- added the possibility to set thermal modifier and spatial modifier to `None`
- fix: when setting the `thermalmodifier` and `spatialmodifier` properties, the material was changed properly, but PyAEDT property did not show the change.
- fix: if the thermal or spatial modifier was set to `None` (EITHER in the UI or in PyAEDT), further changes in the property modifiers would be ignored.

FEAT: set thermal modifier and spatial modifier to None

---

pyaedt/generic/plot.py
pyaedt/modules/solutions.py
pyaedt/sbrplus/plot.py

Changes consists in handling the fact that some methods are using/returning a plotter and calling `show` on it. However, the default behavior leads to automatically closing the plotting session when user close the plot.
This PR changes this behavior by using `auto_close=False` in `pyvista`'s plotter call to method `show`.
Closes #4730

FIX: plotter show exiting plotting session

---

_unittest/test_21_Circuit.py
pyaedt/modeler/circuits/object3dcircuit.py

Cherry pick: https://github.com/ansys/pyaedt/pull/4896
@HaiwenZhang

FEAT: Change symbol pin

---

pyaedt/hfss3dlayout.py

Metho `create_linear_count_sweep` was not passing the sweep type correctly. Leading to one example using the wrong sweep type. This should fix it.
Closes #4970

FIX: Sweep type not setted up at creation

---

pyaedt/modules/MaterialLib.py
pyaedt/modules/Mesh.py
pyaedt/modules/Mesh3DLayout.py
pyaedt/modules/MeshIcepak.py

REFACTOR: Cleanup bandit warnings in modules

---

examples/02-HFSS/Array.py
examples/02-HFSS/HFSS_Dipole.py
pyaedt/generic/farfield_visualization.py
pyaedt/hfss.py
pyaedt/icepak.py
pyaedt/modules/PostProcessor.py
pyaedt/modules/report_templates.py
pyaedt/q3d.py
pyaedt/sbrplus/hdm_parser.py
pyaedt/sbrplus/plot.py
pyproject.toml

When merging https://github.com/ansys/pyaedt/pull/4893 the step `doc-build` was not performed because it requires `doc-style` which couldn't run because too many changes were performed.
This led to a main branch with documentation extended and missing `pyista` dependency.

FIX: Pyvista not included in doc-no-examples dependencies

---

pyaedt/modules/AdvancedPostProcessing.py
pyaedt/modules/Boundary.py
pyaedt/modules/DesignXPloration.py

This PR should be the last batch of changes related to handling `bandit` warnings on `pyaedt.modules`.

REFACTOR: Last bandit refact on pyaedt.modules

---

.gitignore
.pre-commit-config.yaml

The new pre-commit release has [improvement](https://github.com/ansys/pre-commit-hooks/pull/217) on the licenser-header hook which should GREATLY reduce the overhead associated to that hook when doing a commit.
@dcrawforAtAnsys This is not the enhancement I mentioned previously as we were waiting for https://github.com/fsfe/reuse-tool/pull/1055 to be merged. However, this is a complementary approach that will save us a lot of time !

CHORE: Update pre-commit to v0.4.3

---

_unittest/test_98_Icepak.py
pyaedt/modules/MaterialLib.py

FIX: Set emissivity value in surface material

---

.github/dependabot.yml

Add myself as a default reviewer and also modify the default PR prefix to BUILD.

CI: Update dependabot configuration

---

doc/source/index.rst
doc/source/release_1_0.rst

As we are approaching release `1.0` it would be great to notify users that some breaking changes are expected to happend when migration to this new major version.
This PR addresses this aspect by mentioning the argument deprecation and the expected directory restructuration.
On top of it, other changes are mentioned as the naming consistency, data encapsulation, examples extraction, ...
I hope to link this PR with another one to warn users of this incoming changes when they import pyaedt.

DOCS: Add v1.0 expected breaking changes

---

pyaedt/generic/settings.py

Changed the default global log filename to use a unique id to avoid conflicts in concurrent sessions.

FIX: Changed the default global log filename to use a unique id

---

doc/source/User_guide/postprocessing.rst
pyaedt/generic/general_methods.py

FIX: Linux licenseclient path

---

doc/source/release_1_0.rst
src/ansys/aedt/core/modeler/cad/primitives_2d.py
src/ansys/aedt/core/modeler/circuits/primitives_circuit.py
src/ansys/aedt/core/modeler/circuits/primitives_nexxim.py

As for the farfield refactoring, the CICD does not run the doc-build due to doc-style not being triggered.
While cleaning up some documentation paths, it seems that an error got discovered and is currently blocking our CICD.
This PR aims at partially removing the doc warnings to allow the doc-build to pass the CICD.

DOCS: Fix blocking doc-build warnings

---

src/ansys/aedt/core/generic/general_methods.py

Ignore psutil.NoSuchProcess exceptions in
`pyaedt.generic.general_methods.active_sessions` to avoid issuing a spurious error when a process exits during the loop body.  Also improve reporting when another type of exception does occur to allow for easier debugging.
Fixes #5055

FIX: gracefully handle exited processes

---

_unittest/test_warnings.py
src/ansys/aedt/core/__init__.py

Since we want to follow other scientific Python packages, see [SPEC-0000](https://scientific-python.org/specs/spec-0000/), this PR adds a warning depending on the Python version detected. Currently, if one has version <= 3.9 then a `FutureWarning` is triggered.

CHORE: Add warning on python version

---

pyproject.toml

Recent development in pyedb made it difficult to work with recent version of pyedb and older one.
This should ensure that no one gets strange error due to the use of an old version of pyedb.

CHORE: Update pyedb dependency

---

_unittest/test_warnings.py
src/ansys/aedt/core/__init__.py
src/pyaedt/__init__.py

Previously the test on `pyaedt` alias deprecation warning was randomly failing. I have a guess that it is related to the fact that, some times, the process dealing with `test_alias_deprecation_warning` has already imported `pyaedt` previously, leading to a warning not being raised since the module was already loaded and the warning was recorded.
This PR propose a hardcoded test that will cleanup the warning registry and force the load of pyaedt. This way, we are sure that the warning is triggered. However, the check requires to use the line associated to calling the warning in `pyaedt.__init__.py`...
Unfortunately I wasn't able to obtain a better result with mocking OR with `pytest.warns`. I'll open an issue about this.

TEST: Fix alias deprecation warning

---

_unittest/test_warnings.py
src/pyaedt/__init__.py

Follow up of #5073 which used an hardcoded test. This changes ensure that `pytest` handles correctly the warning which was not caught previsouly due to the modification to `warnings.showwarning`.

TEST: Improve test delegation warning

---

.github/workflows/ci_cd.yml

Last release had the deploy stable docs index job failing due to the changes in build backend (temporary `setuptools`).
See https://github.com/ansys/pyaedt/actions/runs/10474990009/job/29041977423
This PR aims at fixing that job.

CI: Fix deploy stable docs index

---

.git-blame-ignore-revs

This PR consist in adding a `.git-blame-ignore-revs` file. The interest of this file is that it allows to ignore specific revisions. For example, I'm discarding a few old commits that were mainly focused on formatting such that when you try to see what was the last change on a line of code, you have more chance to retrieve data associated to the commit which added the line of code (or modified the logic in it) and not the last format commit which updated the line.
The file name is important as it is the standard one and it can be leveraged by your IDE and Github. For example, with Visual Studio Code, I didn't have to do any configuration to make that work correctly (you just need to restart you IDE though).
Also it can be leveraged through Github in a Web browser ! See [Viewing a file - …

CHORE: Add git blame ignore revs file

---

doc/source/User_guide/settings.rst

As title says. The latest added setting was missing from the user guide documentation.

DOCS: Add aedt log file in settings

---

.gitignore

A specific filename was mentioned before. Make it a general ignore for this extension.

FIX: Generalize .code-workspace in .gitignore

---

README.md

Following [Roberto](https://github.com/ansys/pyansys-geometry/pull/1420) comment on `pyansys-geometry`'s pypi landing page, here is a fix for our own.
Below is the current page rendering:

DOCS: Fix pypi landing page

---

src/ansys/aedt/core/emit.py
src/ansys/aedt/core/emit_core/results/revision.py

Instead of only forcing an EMIT API-level save on run, create an EMIT design-level save that saves both the AEDT project and the EMIT API-level save, and force both on run.

FEAT: Force an EMIT save after analysis

---

.github/dependabot.yml

I'm glad that dependabot opens PR to ease how we upgrade our dependencies to new versions.
However, when this happens during the week, it consumes our VM while we might required them.
One option would be to schedule them early in the morning but that would just move the problem to people trying to contribute from USA / APAC.
This PR proposes to move those updates to saturday so that the impact on development is lowered. Ofc, this could be updated later on when we'll have access to containers !

CI: Schedule dependabot on saturday

---

src/ansys/aedt/core/desktop.py

Removing the call to the debug log because it always end up failing if the desktop is already closed. Indeed, by triggering that log call at exit, we end up trying to write something but the log handler is closed/deleted.

FIX: Wrong call to logging atexit

---

.github/workflows/ci_cd.yml
.github/workflows/manual_draft.yml

Following a discussion with @Alberto-DM, this PR aims at reducing the use of our self hosted runners.
AFAIK, the best we can do with the current capabilities of Github is to avoid using our self hosted runners when one is working on a draft. This will allow other PRs, marked as ready to review, to use the self hosted runners instead of waiting for a draft PR finishing "wasting" resources. Since one could still want to trigger the jobs using our self hosted runners none the less, we should also allow people to run them by manually clicking on the run button.

CI: Avoid using self-hosted runners in drafts

---

.github/workflows/ci_cd.yml

The problem that was preventing us to use `download/upload-artifact` actions seems to be [fixed](https://github.com/actions/upload-artifact/issues/485#issuecomment-2397660452.), see https://github.com/actions/upload-artifact/pull/625.
If that's correct, it will be a really good news because we'll be able to leverage ansys actions even more !
> Note: Remind that v3 and v4 have incompatible format and that was preventing us to use ansys actions.

CI: Upgrade artifact actions

---

_unittest/test_45_FilterSolutions/test_filter/test_multiple_bands_table.py
_unittest/test_45_FilterSolutions/test_filter/test_transmission_zeros.py
src/ansys/aedt/core/filtersolutions_core/multiple_bands_table.py
src/ansys/aedt/core/filtersolutions_core/transmission_zeros.py

This PR updates the Trap topology condition to accept multiple band filters.

FIX: Trap topology condition update for multiband filters

---

src/ansys/aedt/core/desktop.py

Solves a bug preventing AEDT from opening when only a pre-release is installed on the system.
Solves #5258

FIX: Case where only a prerelease is installed on system

---

_unittest/test_45_FilterSolutions/test_filter/test_attributes.py
src/ansys/aedt/core/filtersolutions_core/attributes.py

This PR renames order to filter_order to make it more meaningful.

REFACTOR: Renaming filter into filter_order

---

_unittest_solvers/test_26_emit.py
src/ansys/aedt/core/modeler/schematic.py

Preparing EMIT to provide Python 3.12 starting with AEDT 2025.1.

FEAT: Prepare for EMIT Python 3.12 support.

---

.github/workflows/ci_cd.yml
.github/workflows/nightly-docs.yml

Bumping actions related to artifact download / upload requires to bump ansys/doc-deploy-* actions.
Currently we are uploading with upload-artifact@v4 (which requires download@v4) however the doc-deploy actions use v3 :/

CI: Fix conflict in artifact action version

---

.github/workflows/ci_cd.yml

Update doc-style action to latest version in order to fix the new changes in errata-ai/vale-action@1262efa.
See https://github.com/ansys/actions/pull/614

CI: Bump doc-style action version

---

.github/workflows/ci_cd.yml
.github/workflows/nightly-docs.yml
doc/Makefile
doc/source/conf.py

As title say.
We've been left behind with ansys/actions due to various reasons - the biggest one being the artifact compatibility issue.
Now that all the issues that slowed us down are solved, we can update our CICD !
Notable changes:
- To be compatible with `ansys/actions/doc-build` I'm removing the name of the pdf in `conf.py`. This should lead to the creation of a pdf named `pyaedt.pdf`. In the process we lose the version in the pdf file name but this is a requirement for the `doc-build` action. I don't think this is a problem though.
- Meilisearch is being deprecated so I dropped the indexing jobs. I'll update our documentation to remove meilisearch and leverage static search in another PR.

CI: Bump ansys actions version

---

src/ansys/aedt/core/hfss.py

Fixed typo in 'output_dir' argument of method hfss\validate_full_design

FIX: typo in output_dir argument of method hfss\validate_full_design

---

src/ansys/aedt/core/visualization/advanced/touchstone_parser.py

Fix error in the refactoring of #5339
This is currently breaking the CICD of [pyaedt-examples](https://github.com/ansys/pyaedt-examples).

FIX: Wrong import in touchstone parser

---

.github/workflows/manual_draft.yml

As title says. A typo got merged ... Sry about that !

CI: Remove needs from manual_draft workflow

---

.github/workflows/nightly-docs.yml

Fix error introduced while refactoring the CICD to use recent ansys/actions.

CI: Remove needs to doc-build

---

doc/source/Resources/pyaedt_installer_from_aedt.py

The script file `pyaedt_installer_from_aedt.py` is supposed to be executed in an IronPython environment and therefore is not compatible with f-string.

FIX: Remove f-string from IronPython script

---

src/ansys/aedt/core/workflows/installer/extension_manager.py
src/ansys/aedt/core/workflows/templates/run_pyaedt_toolkit_script.py_build
src/pyaedt/workflows/templates/run_pyaedt_toolkit_script.py_build

As title says.
On top of this change, I also fixed a problem of import when when tried to use `run_pyaedt_toolkit_script.py`.

FEAT: Add disclaimer to the extension manager

---

src/ansys/aedt/core/workflows/project/kernel_converter.py

Remove the clipboard isolation env variable if present. 
Setting the env variable "ANS_USE_ISOLATED_CLIPBOARD" prevents the converter from working.

FIX: Remove the clipboard isolation env variable in the kernel_converter script

---

src/ansys/aedt/core/modeler/schematic.py
src/ansys/aedt/core/modules/material_workbench.py
src/ansys/aedt/core/modules/solve_setup.py
src/ansys/aedt/core/visualization/advanced/farfield_visualization.py
src/ansys/aedt/core/workflows/templates/pyaedt_utils.py

Changes include:
- use of `defusedxml` to safely parse an XML file;
- use of `secrets` to generate random values between 0 and 255;
- raise `RuntimeError` instead of using `assert` in code.

REFACTOR: General code improvements

---

src/ansys/aedt/core/workflows/installer/extension_manager.py

Without this check, the extension manager could delete the content of directories by mistake

FIX: Check valid name and file

---

src/ansys/aedt/core/workflows/hfss3dlayout/parametrize_edb.py

- Release desktop as soon as necessary information is extracted from active design
- The old implementation creates a new parametrized design even the user click X to close the window

FIX: close UI by click X should not trigger parametrization

---

src/ansys/aedt/core/modeler/cad/object_3d.py
src/ansys/aedt/core/modeler/cad/primitives.py
tests/system/general/test_07_Object3D.py
tests/system/general/test_08_Primitives3D.py

FEAT: Material appearance

---

src/ansys/aedt/core/modeler/cad/elements_3d.py
src/ansys/aedt/core/modeler/cad/object_3d.py
tests/system/general/test_07_Object3D.py
tests/system/general/test_08_Primitives3D.py

Changes include:
- fixing the aedt code in `object_3d.py` and `element_3d.py`
- refactoring the `chamfer` method (f-string, check in symmetric case, improve error msg)
- removing test duplicate
- improve test on chamfer
Follow up of #5394
Close #5423

FIX: Create chamfer

---

doc/source/API/visualization/report.rst
src/ansys/aedt/core/visualization/report/field.py

Changes include:
- fixing the documentation error;
- refactoring the `Fields`'s `__init__` method to use `post_app` as input argument name instead of `app`.
The second point would have helped to understand that one must provide a post application and not an app like `Hfss`, ...

DOCS: Fix python code error in visualization report

---

src/ansys/aedt/core/modules/design_xploration.py

The functions add() and add_variation() within the ParametricSetup and SetupParam classes expect to be overloaded with variation_type variable of type str. However, initially it was int or float. This generated a warning when passing this argument as shown in the image below
The change in the docstring removes these warnings 
No issue linked to this

DOCS: Correct variation_type data type in parametric setup documentation

---

src/ansys/aedt/core/modules/solve_setup.py
tests/system/general/test_12_1_PostProcessing.py

Set tuning offset was not setting the value of the variable correctly
#5497

FIX: Apply value to derivative variable

---

src/ansys/aedt/core/modeler/cad/primitives.py
tests/system/general/test_07_Object3D.py

Model_units property allows you to get or set the model units. When setting the model units, you can specify whether to rescale the model by adjusting the ``rescale_model`` attribute.
Close #5541 
Close #5533

FEAT: Rescale property in model units

---

src/ansys/aedt/core/visualization/post/common.py
src/ansys/aedt/core/visualization/post/post_common_3d.py

create_report now automatically get the first Sphere if no argument is passes and set Theta and Phi to All in case they are not defined as variaton dictionary.
plot_field is automatically skipping PML objects.
create_report now automatically get the first Sphere if no argument is passes and set Theta and Phi to All in case they are not defined as variaton dictionary.
plot_field is automatically skipping PML objects.

FIX: Improve create_report 

---

doc/source/release_1_0.rst
doc/styles/config/vocabularies/ANSYS/accept.txt
src/ansys/aedt/core/__init__.py
src/ansys/aedt/core/generic/clr_module.py
tests/unit/test_clr_module.py

To improve compatibility with system libraries in Linux, the Python package `dotnetcore2` should be removed from PyAEDT's dotnet installation target. Indeed, the embedded version of `.NET` associated to `dotnetcore2` is old and has **incompatibilities** with recent versions of `openssl` such as the one installed by default in Ubuntu 22.04.
This PR propose to add this modification to the breaking changes of release v1.0 and, in the mean time, to allow users to:
- use a .NET runtime that they have installed instead of the one embedded in `dotnetcore2`
- fallback to the `dotnetcore2` approach if no .NET runtime is detected / provided through environment variable (DOTNET_ROOT).
See #5554
---
> [!NOTE]  
Tests implementation differs from pyedb since pyaedt has a `filterwarnings` option for …

REFACTOR: Loading dotnet runtime

---

pyproject.toml

Temporary solution for the packaging issue in CICD. This PR should be reverted at some point once `attrs` gets a new release with license available on PyPI.
Here is the issue associated to our CICD failure  https://github.com/python-attrs/attrs/issues/1386

FIX: Temporary avoid attrs v24.3.0

---

src/ansys/aedt/core/application/analysis_3d.py
tests/system/general/test_20_HFSS.py

From 2024R1, AEDT API allows the import of GDSII in non-graphical mode.
Close #5567

FIX: Allow non graphical mode for Import GDSII in 3D

---

src/ansys/aedt/core/icepak.py
src/ansys/aedt/core/modeler/cad/elements_3d.py
src/ansys/aedt/core/modules/mesh.py

Changes to fix maxwell icepak example.
@maxcapodi78 @Samuelopez-ansys  Feel free to close this PR if you have something working. I need to drop now.

FIX: Maxwell icepak example

---

doc/source/Resources/pyaedt_installer_from_aedt.py

The current installer script file is not working with wheel house argument. This PR should fix it and also improve the code of the script.
Close #5591

FIX: PyAEDT installer with wheelhouse

---

src/ansys/aedt/core/application/design.py
src/ansys/aedt/core/modules/boundary/common.py
src/ansys/aedt/core/modules/boundary/hfss_boundary.py
src/ansys/aedt/core/modules/boundary/layout_boundary.py
src/ansys/aedt/core/modules/boundary/maxwell_boundary.py
src/ansys/aedt/core/modules/mesh.py
src/ansys/aedt/core/modules/mesh_icepak.py
src/ansys/aedt/core/modules/solve_setup.py
src/ansys/aedt/core/visualization/report/common.py

Use BinaryTreeNode in Icepak Mesh too.

FIX: Icepak Mesh Binary Tree

---

src/ansys/aedt/core/modules/design_xploration.py

The ParametricSetup docstring was updated to allow strings as passed
parameters in the correct context.
Close Issue #5616
This is a documentation issue.

DOCS: Update ParametricSetups docstring

---

src/ansys/aedt/core/application/aedt_objects.py
src/ansys/aedt/core/circuit.py
src/ansys/aedt/core/hfss.py
src/ansys/aedt/core/hfss3dlayout.py

Move onetwork_data_explorer to general AEDT objects instead of initializing it on every application.
Close #5637

FIX: Move onetwork_data_explorer to AedtObjects

---

doc/source/Resources/pyaedt_installer_from_aedt.py

REFACTOR: Add possibility to specify python venv directory

---

src/ansys/aedt/core/modules/boundary/layout_boundary.py
src/ansys/aedt/core/modules/mesh_icepak.py

Fix issue with 2024R1. API method was not supported.
Close #5653

FIX: Use Get3DComponentDefinitionNames to obtain 3DComponent instances

---

src/ansys/aedt/core/modules/solve_setup.py

**This default intrinsics weren't correctly populated for HFSS design since the latest refactoring of the GetDataModel PR.
Hence a new check for frequency was needed in properties.**
**Closes #5650**

FIX: default intrinsics

---

src/ansys/aedt/core/application/analysis_3d.py
src/ansys/aedt/core/application/design.py
src/ansys/aedt/core/application/variables.py
src/ansys/aedt/core/emit_core/couplings.py
src/ansys/aedt/core/generic/checks.py
src/ansys/aedt/core/generic/configurations.py
src/ansys/aedt/core/generic/errors.py
src/ansys/aedt/core/generic/general_methods.py
src/ansys/aedt/core/generic/grpc_plugin_dll_class.py
src/ansys/aedt/core/hfss3dlayout.py
src/ansys/aedt/core/icepak.py
src/ansys/aedt/core/modeler/cad/component_array.py
src/ansys/aedt/core/modeler/cad/object_3d.py
src/ansys/aedt/core/modeler/modeler_3d.py
src/ansys/aedt/core/modules/boundary/layout_boundary.py
src/ansys/aedt/core/modules/mesh.py
src/ansys/aedt/core/modules/mesh_icepak.py
src/ansys/aedt/core/visualization/post/field_data.py
src/ansys/aedt/core/visualization/post/post_icepak.py
tests/system/solvers/test_00_analyze.py
tests/unit/test_utils.py

This feature adds the ability to decorate a method with a check on AEDT version.
This way, check the version inside the method is no longer required and one can see right away that there is a limitation on the method.
The decorator should be compatible in many classes of PyAEDT. However, there is a limitation which requires the decorated object to be able to access the AEDT desktop.
Current ways to achieve such check is to leverage any existing attribute among `odesktop`, `_odesktop` and `_desktop`.
Associated to #5504 
The test are performed on a mock object to simplify things but I also tested it on a fake Desktop and it worked just fine, here is the class I used to test with real AEDT object
```python
class DummyDesktop(Desktop):
"""Dummy class to test min version."""
def __new__(cls, …
```

FEAT: Add min version decorator

---

src/ansys/aedt/core/modeler/cad/polylines.py
src/ansys/aedt/core/modeler/cad/primitives.py
src/ansys/aedt/core/modeler/cad/primitives_2d.py
src/ansys/aedt/core/modeler/cad/primitives_3d.py
src/ansys/aedt/core/modeler/circuits/object_3d_circuit.py

As title says, various changes to cleanup variable names, methods implementation, logging, removing assert in non test code, ...
Associated to #5504

REFACTOR: General clean up of modeler modules

---

src/ansys/aedt/core/visualization/advanced/misc.py

Depeding on OS, the file list order could change, and the files could contain different size data. With this PR, if the field does not contain information, it is filled with a 0 value, because it means that there is no field value at this field component.
Close #5664

FIX: Convert near field list name order

---

pyproject.toml
tests/system/general/test_01_3dlayout_edb.py
tests/system/general/test_12_1_PostProcessing.py

Improve unit test to make them independent each other.

REFACTOR: Improved tests

---

src/ansys/aedt/core/q3d.py

Running some PyAEDT tests in Linux with `numpy>=2.Y` leads to errors when a test requires to load a Desktop and then uses `PyEDB` and tries to load .NET Core.
This changes will ensure that if one uses `ansys.aedt.core`, `numpy` is not loaded by default before the Desktop.
Otherwise, there is a side effect and .NET Core can't be loaded...
This should be further investigated.

FIX: Load numpy lazily

---

src/ansys/aedt/core/generic/data_handlers.py
src/ansys/aedt/core/modeler/cad/components_3d.py
src/ansys/aedt/core/modeler/cad/modeler.py
src/ansys/aedt/core/modeler/cad/object_3d.py
src/ansys/aedt/core/modeler/cad/polylines.py
tests/unit/test_object_3d.py
tests/unit/test_polyline.py

General improvements which include:
- removal of useless try: ... except: ...
- removal of assert in non test code and raise of `AEDTRuntimeError` instead
- refactor some part of the code to make it more readable (might be subjective :D)
Associated to #5504

REFACTOR: General improvements

---

pyproject.toml

The tool used to check license is not yet able to work with PEP 639, I just proposed a PR to fix that (https://github.com/raimon49/pip-licenses/pull/226) but in the mean time we must avoid the latests versions of `attrs`.

BUILD: Avoid new attrs release

---

src/ansys/aedt/core/workflows/hfss3dlayout/generate_arbitrary_wave_ports.py

FIX: Conformal waveport extension bug fix

---

src/ansys/aedt/core/workflows/installer/jupyter_template.ipynb

Use GRPC by default in Jupyter template
Close #5685

FIX: Use GPRC API by default in Jupyter template

---

doc/source/Getting_started/Troubleshooting.rst
doc/styles/config/vocabularies/ANSYS/accept.txt

Add a troubleshooting section for numpy issue.
Close #5675

DOCS: Add Numpy issues

---

src/ansys/aedt/core/modeler/circuits/primitives_circuit.py

Enables the creation of more complex circuit topologies. Namely, using multiple schematics pages. create_component already enabled this, but the wire and gnd components wouldn't enable new pages as it was fixed to page 1.

REFACTOR: Add schematics Page option on create_gnd/create_wire

---

src/ansys/aedt/core/modeler/circuits/primitives_circuit.py

Adding documentation to create_component method within circuit_primitives.py 
Issue #5722

DOCS: Add docstring for Page in create_component

---

src/ansys/aedt/core/application/aedt_objects.py

Changed the behaviour with GetEditor method to remain in schematic

FIX: layout editor from circuit designer is loaded when layouteditor is called

---

src/ansys/aedt/core/modeler/modeler_pcb.py
src/ansys/aedt/core/modules/setup_templates.py
tests/system/general/test_01_3dlayout_edb.py

Added a new method called set_touchstone model in HFSS 3D Layout to assign a touchstone to a component in the layout. Still missing the possibility to assign a pin mapping to the terminals. Those advanced functionalities are available anyway in PyEDB.
Close #4363
Close #4391

FIX: add set_touchstone_model to Hfss3dLayout

---

src/ansys/aedt/core/application/aedt_objects.py
src/ansys/aedt/core/application/design.py
src/ansys/aedt/core/desktop.py
tests/system/general/test_20_HFSS.py

When initializing an application without defining a design name actually is taking the existing design only if the number of designs into the projects are only 1. We are changing this behaviour. If design name is not provided:
- It checks for active design if is of the type we are looking for and eventually set it to active
- If not if it takes the first alphabetically ordered design and makes it active.

REFACTOR: Design initialization in PyAEDT APP 

---

.github/workflows/ci_cd.yml

While migrating to AEDT 25.1 we faced an issue while testing `FilterSolutions`.
The first work around was to skip the tests with https://github.com/ansys/pyaedt/pull/5752/commits/84ae970d74ae86066cec661b5cbdf63249fcb144
However, it seems that the transition is still having some side effects.
We assume that this is related to the filter solutions dll and this PR deselects all test files related to filter solutions to avoid having any import performed.
None yet but on might be opened soon.

CI: Temporary deselect FilterSolutions testing

---

src/ansys/aedt/core/hfss.py
src/ansys/aedt/core/icepak.py
src/ansys/aedt/core/maxwell.py
src/ansys/aedt/core/mechanical.py
src/ansys/aedt/core/mixins.py
src/ansys/aedt/core/modules/boundary/icepak_boundary.py
src/ansys/aedt/core/q3d.py
tests/system/general/test_27_Maxwell2D.py
tests/system/general/test_28_Maxwell3D.py
tests/system/general/test_98_Icepak.py
tests/unit/conftest.py
tests/unit/test_maxwell_3d.py

Using Mixin is a good practice, we should try to refactor the code and follow this kind of approach. This PR is a starting point in that direction and is currently only adding a CreateBoundaryMixin class.
A Mixin is used to add reusable functionality to multiple classes without creating deep inheritance hierarchies. Typically, such class are small, contain additional methods and **should not be instantiated on its own.**
> [!NOTE]
Currently the changes are not applied to all main classes of PyAEDT as it is more a proof of concept. I'm only applying it in classes where the idea of a method used to create a boundary was already implemented.
Associated to #5504

REFACTOR: Use Mixin to create boundary

---

tests/system/solvers/test_45_FilterSolutions/test_export_to_aedt/test_export_to_aedt.py

**This PR adds error messages for properties not applicable to the defined design.**
**NA**

FEAT: Update export page to give error for properties not in common for lumped and distributed export pages

---

src/ansys/aedt/core/workflows/hfss/shielding_effectiveness.py
src/ansys/aedt/core/workflows/templates/run_pyaedt_toolkit_script.py_build

Shielding Effectiveness extension was not working correctly when it was launched from AEDT. So, launching the extension script in a second process was the solution to fix it.
Close #5805

FIX: Launch extension from a CPython process instead of Ironpython process

---

.github/workflows/ci_cd.yml
doc/changelog.d/5888.fixed.md
src/ansys/aedt/core/application/__init__.py
src/ansys/aedt/core/application/analysis.py
src/ansys/aedt/core/generic/constants.py
src/ansys/aedt/core/icepak.py
src/ansys/aedt/core/mechanical.py
src/ansys/aedt/core/modeler/cad/primitives.py
src/ansys/aedt/core/modeler/cad/primitives_2d.py
src/ansys/aedt/core/modeler/cad/primitives_3d.py
src/ansys/aedt/core/modeler/circuits/primitives_nexxim.py
src/ansys/aedt/core/modules/design_xploration.py
src/ansys/aedt/core/modules/solve_setup.py

FIX:  Back compatibility with Example repository

---

.github/workflows/ci_cd.yml
doc/changelog.d/5899.maintenance.md

As title says. This will avoid the pyansys bot to create a PR like https://github.com/ansys/pyaedt/pull/5897
None

CI: Ensure bot uses upper case

---

.github/workflows/ci_cd.yml
doc/changelog.d/5900.maintenance.md

Currently the CICD is stuck when releasing due to the `needs` we have added following the changelog addition. Indeed, to avoid wasting time on the VMs we decided to not run jobs unless the `pr-title` job was passing. However, this backfires when doing a release because this job is not run (we are not in a PR).
Therefore, the early jobs `doc-style` and `smoke-tests` are not launched and nothing is performed when we push a tag. 
The proposed changes consist in keeping the logic of not wasting our VMs when the `pr-title` job fails and to allow this job to succeed when running on a push commit / tag. This is the least intrusive change I can think of to make the workflow back on track.
Another approach would be to have a workflow dedicated to releasing. It would contain almost the same amount …

CI: Fix release workflow

---

.github/workflows/ci_cd.yml
doc/changelog.d/5906.maintenance.md

Add the possibility to verify the source distribution and wheel from the release page / PyPI / workflow artifacts.
Extend the release notes in Github with information on how to verify the release's artifact attestations using [GitHub CLI tool](https://cli.github.com/).
None

CI: Add attestation to release notes

---

doc/changelog.d/5923.fixed.md
src/ansys/aedt/core/icepak.py

No need to set the material for network block. Setting the material will turn on solve inside which will deactivate the network boundary condition.
Close #5864 
removed 
self.modeler.primitives[object_name].material_name = "Ceramic_material"
not necessary
issue 5864
- [ x] I have tested my changes locally.
- [ x] I have added necessary documentation or updated existing documentation.
- [x ] I have followed the coding style guidelines of this project.
- [x ] I have added appropriate tests (unit, integration, system).
- [x ] I have reviewed my changes before submitting this pull request.
- [x ] I have linked the issue or issues that are solved by the PR if any.
- [ x] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

FIX: issue 5864. Solve inside ON for Network objects 

---

doc/changelog.d/5939.miscellaneous.md
src/ansys/aedt/core/modules/material.py

**Add a new argument to get_core_loss to be able to setup coefficient**

REFACTOR: add arg coefficient in core loss mat

---

doc/changelog.d/5949.dependencies.md
pyproject.toml

Seems like the latest versions of setuptools are using PEP 639 which still induces bugs in our actions.
This is a temporary fix that should be reverted once ansys/actions@v9 is released.
Reference: https://github.com/pypa/setuptools/blob/main/NEWS.rst#v7700
None

BUILD: Add setuptools bound to avoid PEP639 issues

---

doc/changelog.d/5945.miscellaneous.md
src/ansys/aedt/core/desktop.py

Improve security of launch_aedt method by removing threading and os.environment collect and assignment.

REFACTOR: Remove aedt threading

---

doc/changelog.d/5972.fixed.md
src/ansys/aedt/core/visualization/post/post_common_3d.py

FIX: Compatibility with Python 3.8

---

.github/workflows/ci_cd.yml
doc/.vale.ini
doc/changelog.d/5974.maintenance.md

Follow up of https://github.com/ansys/pyaedt/pull/4881 and https://github.com/ansys/actions/pull/545. We don't need to manually change the level of some google rues.
The latest release of the actions (8.2.Z) contains the changes to leverage a recent version of reviewdog in vale. This was performed through https://github.com/errata-ai/vale-action/pull/132 and https://github.com/errata-ai/vale-action/pull/140.
Related to #4881

CI: Update vale logic to leverage reviewdog20

---

doc/changelog.d/5976.fixed.md
src/ansys/aedt/core/circuit.py
src/ansys/aedt/core/visualization/post/compliance.py
src/ansys/aedt/core/visualization/post/spisim.py

Added environment variable to fix Spisim error when multiple releases where present in machine.
Fixed compute_erl 

FIX: Fix spisim.py in compute_erl

---

doc/changelog.d/5997.dependencies.md
doc/source/Getting_started/Installation.rst
doc/source/Resources/pyaedt_installer_from_aedt.py
pyproject.toml
src/ansys/aedt/core/workflows/project/version_manager.py

Update install targets by:
- removing `installer` target (this target was added at the begining to only install pyaedt but later evolved into something close to `all`)
- updating `all` target with jupyter related dependencies
- adding `examples` target install (copy of the pyaedt-examples requirements)
Also, some clean up has been performed where `installer` was used and backward compatibility has been added for the version extension.
> [!NOTE] 
Once merged, pyaedt-examples requirements should evolve to use the `examples` target.
Associated to #5978

BUILD: Update install targets and dependencies

---

doc/changelog.d/6002.dependencies.md
pyproject.toml

Package `wheel` latest release (v0.46.0) is breaking the build process of pyaedt because the new release of `wheel` no longer contain the implementation of `setuptools` `bdist_wheel` command, see https://github.com/pypa/wheel?tab=readme-ov-file#historical-note.
This should be reverted once ansys/actions v9 is released.
None

BUILD: Temporary add bound to wheel

---

.github/dependabot.yml
doc/changelog.d/5999.maintenance.md

Add a cooldown to updates associated to pip. This would mitigate, to some extent, exposure to supply chain attacks since dependabot wouldn't run CICD in our self hosted runners until 7 days after the release has been published. During those 7 days, if a vulnerability is found, we can hope for a new release fixing the vulnerability and avoiding us to be exposed.
> [!NOTE]
This cooldown feature is not yet available for github actions. See https://github.com/dependabot/dependabot-core/issues/3651
Associated to https://github.com/ansys/pyaedt/issues/5524

CI: Add dependabot cooldown for pip

---

doc/changelog.d/6001.documentation.md
doc/source/Resources/pyaedt_installer_from_aedt.py
doc/source/Resources/toolkit_installer_from_aedt.py

Just checked the files used to be executed as python script to install things through AEDT.
Adding a log message when using a specific environment variable and `# nosec` on subprocess calls otherwise.
#5504

DOCS: Add log and nosec in checked subprocess calls

---

doc/changelog.d/6017.miscellaneous.md
src/ansys/aedt/core/maxwell.py

Little follow up to https://github.com/ansys/pyaedt/pull/6011#discussion_r2029817588
On top of updating the docstring (content and typo), I added a warning when the option is used for non Electrostatic solution type.
Associated to #5991

REFACTOR: Improve assign balloon method

---

doc/changelog.d/6024.miscellaneous.md
src/ansys/aedt/core/modeler/circuits/primitives_circuit.py

Continuation of pathlib refactoring
Issue #5180

REFACTOR: pathlib refactor primitives_circuit.py

---

.github/workflows/ci_cd.yml
doc/changelog.d/6032.dependencies.md
pyproject.toml

Now that ansys/action@v9 is available, we should leverage it to remove all the patches we had to apply to work in the changing python ecosystem. This is related to how evolved the PyPA action to release on PyPI and also to the new metadata version (2.4) that is used in multiple projects.
None

BUILD: Remove patch on build

---

doc/changelog.d/6079.fixed.md
src/ansys/aedt/core/workflows/hfss3dlayout/cutout.py

speedup UI startup in case of very complex mo…

FIX: Speedup extension cutout 

---

doc/changelog.d/6083.fixed.md
src/ansys/aedt/core/examples/downloads.py

As title says. The previous behavior was to recreate the folder even if a specific file was passed as input.
None

FIX: Only force download file if specified

---

doc/changelog.d/6092.fixed.md
src/ansys/aedt/core/maxwell.py
tests/system/general/test_35_MaxwellCircuit.py

**In this PR I made the schematic name as an optional argument because is not always needed to be provided.**

FIX: Schematic name argument optional in edit_external_circuit method

---

doc/changelog.d/6096.fixed.md
src/ansys/aedt/core/modeler/circuits/object_3d_circuit.py
src/ansys/aedt/core/visualization/plot/pdf.py
src/ansys/aedt/core/visualization/post/compliance.py

FIX: Added some improvement to VirtualCompliance class 

---

doc/changelog.d/6125.fixed.md
src/ansys/aedt/core/circuit.py

The name 'Transient' was being applied to both AMI and Transient setups which could cause confusion. This fix names an AMI setup 'AMI' and a transient setup 'Transient'.
- [ N/A ] I have added necessary documentation or updated existing documentation.
- [ X ] I have followed the coding style guidelines of this project.
- [ N/A ] I have added appropriate tests (unit, integration, system).
- [ X ] I have reviewed my changes before submitting this pull request.
- [ N/A ] I have linked the issue or issues that are solved by the PR if any.
- [ X ] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

FIX: Fix name of setup to match setup type

---

doc/changelog.d/6130.fixed.md
src/ansys/aedt/core/modules/material.py
tests/system/general/test_03_Materials.py

Make method public to change the units if needed
Close #6097

FIX: Change units in non linear properties

---

doc/changelog.d/6132.fixed.md
src/ansys/aedt/core/application/analysis.py
tests/system/general/test_21_Circuit.py
tests/system/solvers/test_00_analyze.py

FIX: Output variable with differential pairs

---

.github/workflows/ci_cd.yml
SECURITY.md
doc/changelog.d/6112.maintenance.md

After multiple PRs, the repo is in a state where it is compatible with our [vulnerability action](https://actions.docs.ansys.com/version/stable/vulnerability-actions/index.html). For information on how to handle multiple situations like a vulnerability source, discovery, tracking, remediation, ... have a look at our [dev guide documentation](https://dev.docs.pyansys.com/how-to/vulnerabilities.html#vulnerabilities).
>[!WARNING]
We can configure `Bandit` to ignore specific advisories (for example, using `# nosec`). This can be due to the code not being ready yet to be fixed or that the advisory is not relevant to the codebase. However, it is important to note that ignoring advisories should be done with caution, and we should be aware of the potential risks involved. Also, we should …

CI: Add vulnerability checking

---

doc/changelog.d/6135.fixed.md
src/ansys/aedt/core/modules/design_xploration.py

FIX: Add blocking to optimetrics analyze method

---

doc/changelog.d/6162.fixed.md
src/ansys/aedt/core/visualization/advanced/farfield_visualization.py
src/ansys/aedt/core/visualization/advanced/frtm_visualization.py
src/ansys/aedt/core/visualization/advanced/rcs_visualization.py
src/ansys/aedt/core/visualization/plot/matplotlib.py
tests/system/visualization/test_49_RCS_data_plotter.py

ISAR 2D calculations were not coded correctly.
Add a pcolor-like capability to pyaedt. Switch some hardwired values to SpeedOfLight.
Corrects ISAR 2D calculations for ISAR images on the xy plane.
Adds pcolor plots to pyaedt for, e.g., rendering ISAR 2D images.
- [ v] I have tested my changes locally.
- [v ] I have added necessary documentation or updated existing documentation.
- [ v] I have followed the coding style guidelines of this project.
- [v ] I have added appropriate tests (unit, integration, system).
- [ v] I have reviewed my changes before submitting this pull request.
- [v ] I have linked the issue or issues that are solved by the PR if any.
- [v ] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

FIX: ISAR 2D range extents

---

doc/changelog.d/6181.fixed.md
src/ansys/aedt/core/generic/ibis_reader.py

Ibisreader was unecessarly reloading the file every buffer.

FIX: improved ibis pin load time

---

doc/changelog.d/6185.fixed.md
src/ansys/aedt/core/visualization/post/compliance.py

…ith y axis value for lna analysis and tdr

FIX: fixed the issue where the freq/time column got interchanged with y axis value for lna analysis and tdr

---

.github/workflows/ci_cd.yml
doc/changelog.d/6190.maintenance.md

CI: Minor changes to update jobs name

---

doc/changelog.d/6231.documentation.md
src/ansys/aedt/core/extensions/hfss/move_it.py
src/ansys/aedt/core/visualization/post/field_summary.py
src/ansys/aedt/core/visualization/post/post_3dlayout.py
src/ansys/aedt/core/visualization/post/post_icepak.py
src/ansys/aedt/core/visualization/post/post_maxwell.py

DOCS: Fix docstrings to comply with numpydoc style.

---

.github/workflows/ci_cd.yml
doc/changelog.d/6227.miscellaneous.md
src/ansys/aedt/core/extensions/misc.py
src/ansys/aedt/core/extensions/project/import_nastran.py
src/ansys/aedt/core/visualization/advanced/misc.py
tests/system/extensions/test_45_extensions.py
tests/system/extensions/test_import_nastran.py
tests/unit/extensions/test_import_nastran.py
tests/unit/test_import_nastran_extension.py

Refactoring of the import nastran extension where the extension has been updated to allow testing with tkinter direct interaction.
Associated to #6228

REFACTOR: Import nastran extension and tests

---

doc/changelog.d/6242.dependencies.md
pyproject.toml
src/ansys/aedt/core/application/design.py
src/ansys/aedt/core/q3d.py
src/ansys/aedt/core/visualization/post/common.py
src/ansys/aedt/core/visualization/post/post_common_3d.py
src/ansys/aedt/core/visualization/post/solution_data.py
tests/system/solvers/test_31_Q3D.py

Import graphic dependencies if needed.
Fix Q3D regression in 2025R2
Close #6241

FIX: Import graphic dependencies if needed

---

doc/changelog.d/6303.documentation.md
doc/source/Getting_started/Contributing.rst

Adds documentation on how to create a PyAEDT extension.
Close #6285

DOCS: Add guide line on how to develop an extension

---

doc/changelog.d/6318.fixed.md
src/ansys/aedt/core/desktop.py

This PR is fixing lsf job submission failure due to Pathlib.Path passed as argument into AEDT native api instead of string causing failure.
closing #6319 

FIX: lsf-job-submission-failure

---

doc/changelog.d/6324.fixed.md
src/ansys/aedt/core/internal/clr_module.py

Follow up of https://github.com/ansys/pyedb/pull/1307
It seems that the loading of dotnet was not correctly handled when leveraging the DOTNET_ROOT env variable.
None

FIX: Dotnet use runtime spec

---

README.md
doc/changelog.d/6352.maintenance.md
doc/source/Getting_started/ClientServer.rst
doc/source/Getting_started/Installation.rst
doc/source/release_1_0.rst
pyproject.toml
src/ansys/aedt/core/examples/downloads.py
tests/integration/test_monostatic_rcs_data.py
tests/unit/extensions/test_via_design.py

As title says.
As extra information, note that this decision has been made for two major reasons:
- End of life has been reached for Python 3.8 and it is close to be the case for Python 3.9, see the [status of python versions](https://devguide.python.org/versions/#status-of-python-versions).
- We should aligh with the Python Scientific Community's best practices and for security reasons. It is important to note that many packages within the Scientific Python Community have dropped support for these Python versions a while ago. Therefore, dropping support for these versions is also a step towards maintaining compatibility, enhancing security and taking full advantage of these scientific packages. For further information on this topic, see [SPEC …

CHORE: Update minimum python version

---

doc/changelog.d/6358.added.md
src/ansys/aedt/core/hfss.py
tests/system/general/test_20_HFSS.py

Assign wave port in driven terminal is available since 2024R1.
Close #6357

FEAT: Assign wave port in Driven Terminal

---

.github/workflows/ci_cd.yml
.github/workflows/manual_draft.yml
doc/Makefile
doc/changelog.d/6407.maintenance.md
doc/make.bat

Pin vtk-osmesa version. Seems like something went wrong on vtk side as CI was using `vtk-osmesa-900.548.751`, see https://github.com/ansys/pyaedt/actions/runs/16275229761/job/45961814797
Related to #5524

CI: Temporary fix for vtk-osmesa

---

doc/changelog.d/6436.fixed.md
src/ansys/aedt/core/hfss3dlayout.py

If the control file (xml_path) is None, then Path raises an exception. Now it is checking if the value is None.

FIX: Import CAD with None value in control file

---

doc/changelog.d/6452.fixed.md
doc/changelog.d/6453.fixed.md
src/ansys/aedt/core/internal/aedt_versions.py

Using regex to check for installed ansysem version will prevent unexpected issues.
For example, when an env var named ANSYSEM_ROOT_PATH is present, instantiating a Hfss3dLayout or a desktop object was failing. This is now fixed
Fixes #6452
Fixes #6430

FIX: Use regex to check installed ansysem versions

---

doc/changelog.d/6454.fixed.md
src/ansys/aedt/core/emit_core/results/revision.py

Fix indentation typo in revision class constructor causing revisions to not be loaded after path is set

FIX: Fix indentation when loading EMIT revision

---

doc/changelog.d/6483.fixed.md
src/ansys/aedt/core/generic/configurations.py

boundary is not updated even after the properties are changed. So the project still shows the old value.
Close #6482 
- [x ] I have tested my changes locally.
- [x ] I have added necessary documentation or updated existing documentation.
- [x ] I have followed the coding style guidelines of this project.
- [x ] I have added appropriate tests (unit, integration, system).
- [x ] I have reviewed my changes before submitting this pull request.
- [ x] I have linked the issue or issues that are solved by the PR if any.
- [ x] I have agreed with the Contributor License Agreement ([CLA](https://developer.ansys.com/form/cla-acceptance)).

FIX: Icepak boundary update is missing

---

doc/changelog.d/6577.fixed.md
src/ansys/aedt/core/extensions/project/resources/configure_layout/template.py

Remove below content from configure file. 
```
"instances": [
{
"name": "Via313",
"backdrill_parameters": {
"from_bottom": {"drill_to_layer": "Inner3", "diameter": "1mm", "stub_length": "0.2mm"}
},
},
{
"name": "Via314",
"backdrill_parameters": {
"from_bottom": {"drill_to_layer": "Inner3", "diameter": "1mm", "stub_length": "0.2mm"}
},
},
],
```
The the vias in a fresh EDB don't have names. When it is imported, pyedb will give them names by their IDs. However, the their IDs are not guaranteed the same on different machine. This leads to Via313 not found.

FIX: configure layout test

---

.github/workflows/ci_cd.yml
.github/workflows/label.yml
.github/workflows/nightly-docs.yml
doc/changelog.d/6592.dependencies.md

As title says. This will avoid `safety`'s dependence issue, fixed in https://github.com/ansys/actions/pull/971
None

BUILD(ci): Bump ansys/actions into v10.0.15

---

.github/workflows/ci_cd.yml
doc/changelog.d/6617.maintenance.md

Modification to improve how linux visualization tests can some time consuming a lot of CI time resource.
The PR marks the test step as failed as soon as a test is failing and reduce the timeout to 60 minutes.
The timeout could be reduced further but, since each suite test completion can get up to ~25-27 minutes, we should be clear with the retry ability.
#5524

CI: Improve visualization failure handling

---

doc/changelog.d/6647.fixed.md
pyproject.toml

fpdf2 and rpyc are two packages that are used only in a specific class of pyaedt.
Moved them to optional

FIX: moved fpdf2 and rpyc in optional dependencies

---

doc/changelog.d/6696.fixed.md
doc/source/Resources/pyaedt_installer_from_aedt.py

~`uv` does not support the `-y` flag directly when running `pip` commands. To correctly pass options like `-y`, one need to separate them from the `uv pip ...` command using `--`. This PR handles those required changes.~
~> Note: everything after `--` is meant for the internal `pip` call, not for `uv` itself.~
The solution to the problem is that `uv` doesn't require an interactive confirmation and simply uninstalls
Close #6695

FIX: Add -- to uv to pass options to pip

---

doc/changelog.d/6738.fixed.md
src/ansys/aedt/core/generic/settings.py
src/ansys/aedt/core/internal/grpc_plugin_dll_class.py

(cherry picked from commit 7e10edf2591714026705322d9614724e1399a243)
Because of a recent change in settings.py, when importing the lib from MacOS, it fails because it tries to get an env variable not defined on this OS.
Close #6704

FIX: enable to import the lib again from MacOS
